/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthedTenantRouteImport } from './routes/_authed/_tenant'
import { Route as AuthedTenantSettingsRouteImport } from './routes/_authed/_tenant/settings'
import { Route as AuthedTenantPerformanceRouteImport } from './routes/_authed/_tenant/performance'
import { Route as AuthedTenantOrgRouteImport } from './routes/_authed/_tenant/org'
import { Route as AuthedTenantDashboardRouteImport } from './routes/_authed/_tenant/dashboard'
import { Route as AuthedTenantCostsRouteImport } from './routes/_authed/_tenant/costs'
import { Route as AuthedTenantActivityRouteImport } from './routes/_authed/_tenant/activity'
import { Route as AuthedTenantWebhooksIndexRouteImport } from './routes/_authed/_tenant/webhooks/index'
import { Route as AuthedTenantThreadsIndexRouteImport } from './routes/_authed/_tenant/threads/index'
import { Route as AuthedTenantSkillsIndexRouteImport } from './routes/_authed/_tenant/skills/index'
import { Route as AuthedTenantSecurityIndexRouteImport } from './routes/_authed/_tenant/security/index'
import { Route as AuthedTenantScheduledJobsIndexRouteImport } from './routes/_authed/_tenant/scheduled-jobs/index'
import { Route as AuthedTenantRoutinesIndexRouteImport } from './routes/_authed/_tenant/routines/index'
import { Route as AuthedTenantMemoryIndexRouteImport } from './routes/_authed/_tenant/memory/index'
import { Route as AuthedTenantKnowledgeBasesIndexRouteImport } from './routes/_authed/_tenant/knowledge-bases/index'
import { Route as AuthedTenantInboxIndexRouteImport } from './routes/_authed/_tenant/inbox/index'
import { Route as AuthedTenantHumansIndexRouteImport } from './routes/_authed/_tenant/humans/index'
import { Route as AuthedTenantArtifactsIndexRouteImport } from './routes/_authed/_tenant/artifacts/index'
import { Route as AuthedTenantAgentsIndexRouteImport } from './routes/_authed/_tenant/agents/index'
import { Route as AuthedTenantAgentTemplatesIndexRouteImport } from './routes/_authed/_tenant/agent-templates/index'
import { Route as AuthedTenantWebhooksWebhookIdRouteImport } from './routes/_authed/_tenant/webhooks/$webhookId'
import { Route as AuthedTenantThreadsThreadIdRouteImport } from './routes/_authed/_tenant/threads/$threadId'
import { Route as AuthedTenantSkillsBuilderRouteImport } from './routes/_authed/_tenant/skills/builder'
import { Route as AuthedTenantSkillsSlugRouteImport } from './routes/_authed/_tenant/skills/$slug'
import { Route as AuthedTenantScheduledJobsScheduledJobIdRouteImport } from './routes/_authed/_tenant/scheduled-jobs/$scheduledJobId'
import { Route as AuthedTenantRoutinesRoutineIdRouteImport } from './routes/_authed/_tenant/routines/$routineId'
import { Route as AuthedTenantKnowledgeBasesKbIdRouteImport } from './routes/_authed/_tenant/knowledge-bases/$kbId'
import { Route as AuthedTenantInboxInboxItemIdRouteImport } from './routes/_authed/_tenant/inbox/$inboxItemId'
import { Route as AuthedTenantAgentsNewRouteImport } from './routes/_authed/_tenant/agents/new'
import { Route as AuthedTenantAgentsInvitesRouteImport } from './routes/_authed/_tenant/agents/invites'
import { Route as AuthedTenantAgentsAgentIdRouteImport } from './routes/_authed/_tenant/agents/$agentId'
import { Route as AuthedTenantAgentTemplatesDefaultsRouteImport } from './routes/_authed/_tenant/agent-templates/defaults'
import { Route as AuthedTenantAgentTemplatesTemplateIdRouteImport } from './routes/_authed/_tenant/agent-templates/$templateId'
import { Route as AuthedTenantAgentsAgentIdWorkspacesRouteImport } from './routes/_authed/_tenant/agents/$agentId_.workspaces'
import { Route as AuthedTenantAgentsAgentIdWorkspaceRouteImport } from './routes/_authed/_tenant/agents/$agentId_.workspace'
import { Route as AuthedTenantAgentsAgentIdSubAgentsRouteImport } from './routes/_authed/_tenant/agents/$agentId_.sub-agents'
import { Route as AuthedTenantAgentsAgentIdSkillsRouteImport } from './routes/_authed/_tenant/agents/$agentId_.skills'
import { Route as AuthedTenantAgentsAgentIdMemoryRouteImport } from './routes/_authed/_tenant/agents/$agentId_.memory'
import { Route as AuthedTenantAgentsAgentIdKnowledgeRouteImport } from './routes/_authed/_tenant/agents/$agentId_.knowledge'
import { Route as AuthedTenantAgentTemplatesTemplateIdSyncRouteImport } from './routes/_authed/_tenant/agent-templates/$templateId_.sync'
import { Route as AuthedTenantAgentsAgentIdScheduledJobsIndexRouteImport } from './routes/_authed/_tenant/agents/$agentId_.scheduled-jobs.index'
import { Route as AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRouteImport } from './routes/_authed/_tenant/agents/$agentId_.scheduled-jobs.$scheduledJobId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTenantRoute = AuthedTenantRouteImport.update({
  id: '/_tenant',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTenantSettingsRoute = AuthedTenantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantPerformanceRoute = AuthedTenantPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantOrgRoute = AuthedTenantOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantDashboardRoute = AuthedTenantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantCostsRoute = AuthedTenantCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantActivityRoute = AuthedTenantActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantWebhooksIndexRoute =
  AuthedTenantWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantThreadsIndexRoute =
  AuthedTenantThreadsIndexRouteImport.update({
    id: '/threads/',
    path: '/threads/',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantSkillsIndexRoute = AuthedTenantSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantSecurityIndexRoute =
  AuthedTenantSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantScheduledJobsIndexRoute =
  AuthedTenantScheduledJobsIndexRouteImport.update({
    id: '/scheduled-jobs/',
    path: '/scheduled-jobs/',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantRoutinesIndexRoute =
  AuthedTenantRoutinesIndexRouteImport.update({
    id: '/routines/',
    path: '/routines/',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantMemoryIndexRoute = AuthedTenantMemoryIndexRouteImport.update({
  id: '/memory/',
  path: '/memory/',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantKnowledgeBasesIndexRoute =
  AuthedTenantKnowledgeBasesIndexRouteImport.update({
    id: '/knowledge-bases/',
    path: '/knowledge-bases/',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantInboxIndexRoute = AuthedTenantInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantHumansIndexRoute = AuthedTenantHumansIndexRouteImport.update({
  id: '/humans/',
  path: '/humans/',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantArtifactsIndexRoute =
  AuthedTenantArtifactsIndexRouteImport.update({
    id: '/artifacts/',
    path: '/artifacts/',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsIndexRoute = AuthedTenantAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantAgentTemplatesIndexRoute =
  AuthedTenantAgentTemplatesIndexRouteImport.update({
    id: '/agent-templates/',
    path: '/agent-templates/',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantWebhooksWebhookIdRoute =
  AuthedTenantWebhooksWebhookIdRouteImport.update({
    id: '/webhooks/$webhookId',
    path: '/webhooks/$webhookId',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantThreadsThreadIdRoute =
  AuthedTenantThreadsThreadIdRouteImport.update({
    id: '/threads/$threadId',
    path: '/threads/$threadId',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantSkillsBuilderRoute =
  AuthedTenantSkillsBuilderRouteImport.update({
    id: '/skills/builder',
    path: '/skills/builder',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantSkillsSlugRoute = AuthedTenantSkillsSlugRouteImport.update({
  id: '/skills/$slug',
  path: '/skills/$slug',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantScheduledJobsScheduledJobIdRoute =
  AuthedTenantScheduledJobsScheduledJobIdRouteImport.update({
    id: '/scheduled-jobs/$scheduledJobId',
    path: '/scheduled-jobs/$scheduledJobId',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantRoutinesRoutineIdRoute =
  AuthedTenantRoutinesRoutineIdRouteImport.update({
    id: '/routines/$routineId',
    path: '/routines/$routineId',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantKnowledgeBasesKbIdRoute =
  AuthedTenantKnowledgeBasesKbIdRouteImport.update({
    id: '/knowledge-bases/$kbId',
    path: '/knowledge-bases/$kbId',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantInboxInboxItemIdRoute =
  AuthedTenantInboxInboxItemIdRouteImport.update({
    id: '/inbox/$inboxItemId',
    path: '/inbox/$inboxItemId',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsNewRoute = AuthedTenantAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthedTenantRoute,
} as any)
const AuthedTenantAgentsInvitesRoute =
  AuthedTenantAgentsInvitesRouteImport.update({
    id: '/agents/invites',
    path: '/agents/invites',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsAgentIdRoute =
  AuthedTenantAgentsAgentIdRouteImport.update({
    id: '/agents/$agentId',
    path: '/agents/$agentId',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentTemplatesDefaultsRoute =
  AuthedTenantAgentTemplatesDefaultsRouteImport.update({
    id: '/agent-templates/defaults',
    path: '/agent-templates/defaults',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentTemplatesTemplateIdRoute =
  AuthedTenantAgentTemplatesTemplateIdRouteImport.update({
    id: '/agent-templates/$templateId',
    path: '/agent-templates/$templateId',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsAgentIdWorkspacesRoute =
  AuthedTenantAgentsAgentIdWorkspacesRouteImport.update({
    id: '/agents/$agentId_/workspaces',
    path: '/agents/$agentId/workspaces',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsAgentIdWorkspaceRoute =
  AuthedTenantAgentsAgentIdWorkspaceRouteImport.update({
    id: '/agents/$agentId_/workspace',
    path: '/agents/$agentId/workspace',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsAgentIdSubAgentsRoute =
  AuthedTenantAgentsAgentIdSubAgentsRouteImport.update({
    id: '/agents/$agentId_/sub-agents',
    path: '/agents/$agentId/sub-agents',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsAgentIdSkillsRoute =
  AuthedTenantAgentsAgentIdSkillsRouteImport.update({
    id: '/agents/$agentId_/skills',
    path: '/agents/$agentId/skills',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsAgentIdMemoryRoute =
  AuthedTenantAgentsAgentIdMemoryRouteImport.update({
    id: '/agents/$agentId_/memory',
    path: '/agents/$agentId/memory',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsAgentIdKnowledgeRoute =
  AuthedTenantAgentsAgentIdKnowledgeRouteImport.update({
    id: '/agents/$agentId_/knowledge',
    path: '/agents/$agentId/knowledge',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentTemplatesTemplateIdSyncRoute =
  AuthedTenantAgentTemplatesTemplateIdSyncRouteImport.update({
    id: '/agent-templates/$templateId_/sync',
    path: '/agent-templates/$templateId/sync',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsAgentIdScheduledJobsIndexRoute =
  AuthedTenantAgentsAgentIdScheduledJobsIndexRouteImport.update({
    id: '/agents/$agentId_/scheduled-jobs/',
    path: '/agents/$agentId/scheduled-jobs/',
    getParentRoute: () => AuthedTenantRoute,
  } as any)
const AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRoute =
  AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRouteImport.update({
    id: '/agents/$agentId_/scheduled-jobs/$scheduledJobId',
    path: '/agents/$agentId/scheduled-jobs/$scheduledJobId',
    getParentRoute: () => AuthedTenantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/activity': typeof AuthedTenantActivityRoute
  '/costs': typeof AuthedTenantCostsRoute
  '/dashboard': typeof AuthedTenantDashboardRoute
  '/org': typeof AuthedTenantOrgRoute
  '/performance': typeof AuthedTenantPerformanceRoute
  '/settings': typeof AuthedTenantSettingsRoute
  '/agent-templates/$templateId': typeof AuthedTenantAgentTemplatesTemplateIdRoute
  '/agent-templates/defaults': typeof AuthedTenantAgentTemplatesDefaultsRoute
  '/agents/$agentId': typeof AuthedTenantAgentsAgentIdRoute
  '/agents/invites': typeof AuthedTenantAgentsInvitesRoute
  '/agents/new': typeof AuthedTenantAgentsNewRoute
  '/inbox/$inboxItemId': typeof AuthedTenantInboxInboxItemIdRoute
  '/knowledge-bases/$kbId': typeof AuthedTenantKnowledgeBasesKbIdRoute
  '/routines/$routineId': typeof AuthedTenantRoutinesRoutineIdRoute
  '/scheduled-jobs/$scheduledJobId': typeof AuthedTenantScheduledJobsScheduledJobIdRoute
  '/skills/$slug': typeof AuthedTenantSkillsSlugRoute
  '/skills/builder': typeof AuthedTenantSkillsBuilderRoute
  '/threads/$threadId': typeof AuthedTenantThreadsThreadIdRoute
  '/webhooks/$webhookId': typeof AuthedTenantWebhooksWebhookIdRoute
  '/agent-templates/': typeof AuthedTenantAgentTemplatesIndexRoute
  '/agents/': typeof AuthedTenantAgentsIndexRoute
  '/artifacts/': typeof AuthedTenantArtifactsIndexRoute
  '/humans/': typeof AuthedTenantHumansIndexRoute
  '/inbox/': typeof AuthedTenantInboxIndexRoute
  '/knowledge-bases/': typeof AuthedTenantKnowledgeBasesIndexRoute
  '/memory/': typeof AuthedTenantMemoryIndexRoute
  '/routines/': typeof AuthedTenantRoutinesIndexRoute
  '/scheduled-jobs/': typeof AuthedTenantScheduledJobsIndexRoute
  '/security/': typeof AuthedTenantSecurityIndexRoute
  '/skills/': typeof AuthedTenantSkillsIndexRoute
  '/threads/': typeof AuthedTenantThreadsIndexRoute
  '/webhooks/': typeof AuthedTenantWebhooksIndexRoute
  '/agent-templates/$templateId/sync': typeof AuthedTenantAgentTemplatesTemplateIdSyncRoute
  '/agents/$agentId/knowledge': typeof AuthedTenantAgentsAgentIdKnowledgeRoute
  '/agents/$agentId/memory': typeof AuthedTenantAgentsAgentIdMemoryRoute
  '/agents/$agentId/skills': typeof AuthedTenantAgentsAgentIdSkillsRoute
  '/agents/$agentId/sub-agents': typeof AuthedTenantAgentsAgentIdSubAgentsRoute
  '/agents/$agentId/workspace': typeof AuthedTenantAgentsAgentIdWorkspaceRoute
  '/agents/$agentId/workspaces': typeof AuthedTenantAgentsAgentIdWorkspacesRoute
  '/agents/$agentId/scheduled-jobs/$scheduledJobId': typeof AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRoute
  '/agents/$agentId/scheduled-jobs/': typeof AuthedTenantAgentsAgentIdScheduledJobsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/activity': typeof AuthedTenantActivityRoute
  '/costs': typeof AuthedTenantCostsRoute
  '/dashboard': typeof AuthedTenantDashboardRoute
  '/org': typeof AuthedTenantOrgRoute
  '/performance': typeof AuthedTenantPerformanceRoute
  '/settings': typeof AuthedTenantSettingsRoute
  '/agent-templates/$templateId': typeof AuthedTenantAgentTemplatesTemplateIdRoute
  '/agent-templates/defaults': typeof AuthedTenantAgentTemplatesDefaultsRoute
  '/agents/$agentId': typeof AuthedTenantAgentsAgentIdRoute
  '/agents/invites': typeof AuthedTenantAgentsInvitesRoute
  '/agents/new': typeof AuthedTenantAgentsNewRoute
  '/inbox/$inboxItemId': typeof AuthedTenantInboxInboxItemIdRoute
  '/knowledge-bases/$kbId': typeof AuthedTenantKnowledgeBasesKbIdRoute
  '/routines/$routineId': typeof AuthedTenantRoutinesRoutineIdRoute
  '/scheduled-jobs/$scheduledJobId': typeof AuthedTenantScheduledJobsScheduledJobIdRoute
  '/skills/$slug': typeof AuthedTenantSkillsSlugRoute
  '/skills/builder': typeof AuthedTenantSkillsBuilderRoute
  '/threads/$threadId': typeof AuthedTenantThreadsThreadIdRoute
  '/webhooks/$webhookId': typeof AuthedTenantWebhooksWebhookIdRoute
  '/agent-templates': typeof AuthedTenantAgentTemplatesIndexRoute
  '/agents': typeof AuthedTenantAgentsIndexRoute
  '/artifacts': typeof AuthedTenantArtifactsIndexRoute
  '/humans': typeof AuthedTenantHumansIndexRoute
  '/inbox': typeof AuthedTenantInboxIndexRoute
  '/knowledge-bases': typeof AuthedTenantKnowledgeBasesIndexRoute
  '/memory': typeof AuthedTenantMemoryIndexRoute
  '/routines': typeof AuthedTenantRoutinesIndexRoute
  '/scheduled-jobs': typeof AuthedTenantScheduledJobsIndexRoute
  '/security': typeof AuthedTenantSecurityIndexRoute
  '/skills': typeof AuthedTenantSkillsIndexRoute
  '/threads': typeof AuthedTenantThreadsIndexRoute
  '/webhooks': typeof AuthedTenantWebhooksIndexRoute
  '/agent-templates/$templateId/sync': typeof AuthedTenantAgentTemplatesTemplateIdSyncRoute
  '/agents/$agentId/knowledge': typeof AuthedTenantAgentsAgentIdKnowledgeRoute
  '/agents/$agentId/memory': typeof AuthedTenantAgentsAgentIdMemoryRoute
  '/agents/$agentId/skills': typeof AuthedTenantAgentsAgentIdSkillsRoute
  '/agents/$agentId/sub-agents': typeof AuthedTenantAgentsAgentIdSubAgentsRoute
  '/agents/$agentId/workspace': typeof AuthedTenantAgentsAgentIdWorkspaceRoute
  '/agents/$agentId/workspaces': typeof AuthedTenantAgentsAgentIdWorkspacesRoute
  '/agents/$agentId/scheduled-jobs/$scheduledJobId': typeof AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRoute
  '/agents/$agentId/scheduled-jobs': typeof AuthedTenantAgentsAgentIdScheduledJobsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_authed/_tenant': typeof AuthedTenantRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authed/_tenant/activity': typeof AuthedTenantActivityRoute
  '/_authed/_tenant/costs': typeof AuthedTenantCostsRoute
  '/_authed/_tenant/dashboard': typeof AuthedTenantDashboardRoute
  '/_authed/_tenant/org': typeof AuthedTenantOrgRoute
  '/_authed/_tenant/performance': typeof AuthedTenantPerformanceRoute
  '/_authed/_tenant/settings': typeof AuthedTenantSettingsRoute
  '/_authed/_tenant/agent-templates/$templateId': typeof AuthedTenantAgentTemplatesTemplateIdRoute
  '/_authed/_tenant/agent-templates/defaults': typeof AuthedTenantAgentTemplatesDefaultsRoute
  '/_authed/_tenant/agents/$agentId': typeof AuthedTenantAgentsAgentIdRoute
  '/_authed/_tenant/agents/invites': typeof AuthedTenantAgentsInvitesRoute
  '/_authed/_tenant/agents/new': typeof AuthedTenantAgentsNewRoute
  '/_authed/_tenant/inbox/$inboxItemId': typeof AuthedTenantInboxInboxItemIdRoute
  '/_authed/_tenant/knowledge-bases/$kbId': typeof AuthedTenantKnowledgeBasesKbIdRoute
  '/_authed/_tenant/routines/$routineId': typeof AuthedTenantRoutinesRoutineIdRoute
  '/_authed/_tenant/scheduled-jobs/$scheduledJobId': typeof AuthedTenantScheduledJobsScheduledJobIdRoute
  '/_authed/_tenant/skills/$slug': typeof AuthedTenantSkillsSlugRoute
  '/_authed/_tenant/skills/builder': typeof AuthedTenantSkillsBuilderRoute
  '/_authed/_tenant/threads/$threadId': typeof AuthedTenantThreadsThreadIdRoute
  '/_authed/_tenant/webhooks/$webhookId': typeof AuthedTenantWebhooksWebhookIdRoute
  '/_authed/_tenant/agent-templates/': typeof AuthedTenantAgentTemplatesIndexRoute
  '/_authed/_tenant/agents/': typeof AuthedTenantAgentsIndexRoute
  '/_authed/_tenant/artifacts/': typeof AuthedTenantArtifactsIndexRoute
  '/_authed/_tenant/humans/': typeof AuthedTenantHumansIndexRoute
  '/_authed/_tenant/inbox/': typeof AuthedTenantInboxIndexRoute
  '/_authed/_tenant/knowledge-bases/': typeof AuthedTenantKnowledgeBasesIndexRoute
  '/_authed/_tenant/memory/': typeof AuthedTenantMemoryIndexRoute
  '/_authed/_tenant/routines/': typeof AuthedTenantRoutinesIndexRoute
  '/_authed/_tenant/scheduled-jobs/': typeof AuthedTenantScheduledJobsIndexRoute
  '/_authed/_tenant/security/': typeof AuthedTenantSecurityIndexRoute
  '/_authed/_tenant/skills/': typeof AuthedTenantSkillsIndexRoute
  '/_authed/_tenant/threads/': typeof AuthedTenantThreadsIndexRoute
  '/_authed/_tenant/webhooks/': typeof AuthedTenantWebhooksIndexRoute
  '/_authed/_tenant/agent-templates/$templateId_/sync': typeof AuthedTenantAgentTemplatesTemplateIdSyncRoute
  '/_authed/_tenant/agents/$agentId_/knowledge': typeof AuthedTenantAgentsAgentIdKnowledgeRoute
  '/_authed/_tenant/agents/$agentId_/memory': typeof AuthedTenantAgentsAgentIdMemoryRoute
  '/_authed/_tenant/agents/$agentId_/skills': typeof AuthedTenantAgentsAgentIdSkillsRoute
  '/_authed/_tenant/agents/$agentId_/sub-agents': typeof AuthedTenantAgentsAgentIdSubAgentsRoute
  '/_authed/_tenant/agents/$agentId_/workspace': typeof AuthedTenantAgentsAgentIdWorkspaceRoute
  '/_authed/_tenant/agents/$agentId_/workspaces': typeof AuthedTenantAgentsAgentIdWorkspacesRoute
  '/_authed/_tenant/agents/$agentId_/scheduled-jobs/$scheduledJobId': typeof AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRoute
  '/_authed/_tenant/agents/$agentId_/scheduled-jobs/': typeof AuthedTenantAgentsAgentIdScheduledJobsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/auth/callback'
    | '/invite/$token'
    | '/activity'
    | '/costs'
    | '/dashboard'
    | '/org'
    | '/performance'
    | '/settings'
    | '/agent-templates/$templateId'
    | '/agent-templates/defaults'
    | '/agents/$agentId'
    | '/agents/invites'
    | '/agents/new'
    | '/inbox/$inboxItemId'
    | '/knowledge-bases/$kbId'
    | '/routines/$routineId'
    | '/scheduled-jobs/$scheduledJobId'
    | '/skills/$slug'
    | '/skills/builder'
    | '/threads/$threadId'
    | '/webhooks/$webhookId'
    | '/agent-templates/'
    | '/agents/'
    | '/artifacts/'
    | '/humans/'
    | '/inbox/'
    | '/knowledge-bases/'
    | '/memory/'
    | '/routines/'
    | '/scheduled-jobs/'
    | '/security/'
    | '/skills/'
    | '/threads/'
    | '/webhooks/'
    | '/agent-templates/$templateId/sync'
    | '/agents/$agentId/knowledge'
    | '/agents/$agentId/memory'
    | '/agents/$agentId/skills'
    | '/agents/$agentId/sub-agents'
    | '/agents/$agentId/workspace'
    | '/agents/$agentId/workspaces'
    | '/agents/$agentId/scheduled-jobs/$scheduledJobId'
    | '/agents/$agentId/scheduled-jobs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/auth/callback'
    | '/invite/$token'
    | '/activity'
    | '/costs'
    | '/dashboard'
    | '/org'
    | '/performance'
    | '/settings'
    | '/agent-templates/$templateId'
    | '/agent-templates/defaults'
    | '/agents/$agentId'
    | '/agents/invites'
    | '/agents/new'
    | '/inbox/$inboxItemId'
    | '/knowledge-bases/$kbId'
    | '/routines/$routineId'
    | '/scheduled-jobs/$scheduledJobId'
    | '/skills/$slug'
    | '/skills/builder'
    | '/threads/$threadId'
    | '/webhooks/$webhookId'
    | '/agent-templates'
    | '/agents'
    | '/artifacts'
    | '/humans'
    | '/inbox'
    | '/knowledge-bases'
    | '/memory'
    | '/routines'
    | '/scheduled-jobs'
    | '/security'
    | '/skills'
    | '/threads'
    | '/webhooks'
    | '/agent-templates/$templateId/sync'
    | '/agents/$agentId/knowledge'
    | '/agents/$agentId/memory'
    | '/agents/$agentId/skills'
    | '/agents/$agentId/sub-agents'
    | '/agents/$agentId/workspace'
    | '/agents/$agentId/workspaces'
    | '/agents/$agentId/scheduled-jobs/$scheduledJobId'
    | '/agents/$agentId/scheduled-jobs'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/sign-in'
    | '/_authed/_tenant'
    | '/auth/callback'
    | '/invite/$token'
    | '/_authed/_tenant/activity'
    | '/_authed/_tenant/costs'
    | '/_authed/_tenant/dashboard'
    | '/_authed/_tenant/org'
    | '/_authed/_tenant/performance'
    | '/_authed/_tenant/settings'
    | '/_authed/_tenant/agent-templates/$templateId'
    | '/_authed/_tenant/agent-templates/defaults'
    | '/_authed/_tenant/agents/$agentId'
    | '/_authed/_tenant/agents/invites'
    | '/_authed/_tenant/agents/new'
    | '/_authed/_tenant/inbox/$inboxItemId'
    | '/_authed/_tenant/knowledge-bases/$kbId'
    | '/_authed/_tenant/routines/$routineId'
    | '/_authed/_tenant/scheduled-jobs/$scheduledJobId'
    | '/_authed/_tenant/skills/$slug'
    | '/_authed/_tenant/skills/builder'
    | '/_authed/_tenant/threads/$threadId'
    | '/_authed/_tenant/webhooks/$webhookId'
    | '/_authed/_tenant/agent-templates/'
    | '/_authed/_tenant/agents/'
    | '/_authed/_tenant/artifacts/'
    | '/_authed/_tenant/humans/'
    | '/_authed/_tenant/inbox/'
    | '/_authed/_tenant/knowledge-bases/'
    | '/_authed/_tenant/memory/'
    | '/_authed/_tenant/routines/'
    | '/_authed/_tenant/scheduled-jobs/'
    | '/_authed/_tenant/security/'
    | '/_authed/_tenant/skills/'
    | '/_authed/_tenant/threads/'
    | '/_authed/_tenant/webhooks/'
    | '/_authed/_tenant/agent-templates/$templateId_/sync'
    | '/_authed/_tenant/agents/$agentId_/knowledge'
    | '/_authed/_tenant/agents/$agentId_/memory'
    | '/_authed/_tenant/agents/$agentId_/skills'
    | '/_authed/_tenant/agents/$agentId_/sub-agents'
    | '/_authed/_tenant/agents/$agentId_/workspace'
    | '/_authed/_tenant/agents/$agentId_/workspaces'
    | '/_authed/_tenant/agents/$agentId_/scheduled-jobs/$scheduledJobId'
    | '/_authed/_tenant/agents/$agentId_/scheduled-jobs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  SignInRoute: typeof SignInRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_tenant': {
      id: '/_authed/_tenant'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedTenantRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_tenant/settings': {
      id: '/_authed/_tenant/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedTenantSettingsRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/performance': {
      id: '/_authed/_tenant/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthedTenantPerformanceRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/org': {
      id: '/_authed/_tenant/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof AuthedTenantOrgRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/dashboard': {
      id: '/_authed/_tenant/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedTenantDashboardRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/costs': {
      id: '/_authed/_tenant/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AuthedTenantCostsRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/activity': {
      id: '/_authed/_tenant/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedTenantActivityRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/webhooks/': {
      id: '/_authed/_tenant/webhooks/'
      path: '/webhooks'
      fullPath: '/webhooks/'
      preLoaderRoute: typeof AuthedTenantWebhooksIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/threads/': {
      id: '/_authed/_tenant/threads/'
      path: '/threads'
      fullPath: '/threads/'
      preLoaderRoute: typeof AuthedTenantThreadsIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/skills/': {
      id: '/_authed/_tenant/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof AuthedTenantSkillsIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/security/': {
      id: '/_authed/_tenant/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AuthedTenantSecurityIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/scheduled-jobs/': {
      id: '/_authed/_tenant/scheduled-jobs/'
      path: '/scheduled-jobs'
      fullPath: '/scheduled-jobs/'
      preLoaderRoute: typeof AuthedTenantScheduledJobsIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/routines/': {
      id: '/_authed/_tenant/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof AuthedTenantRoutinesIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/memory/': {
      id: '/_authed/_tenant/memory/'
      path: '/memory'
      fullPath: '/memory/'
      preLoaderRoute: typeof AuthedTenantMemoryIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/knowledge-bases/': {
      id: '/_authed/_tenant/knowledge-bases/'
      path: '/knowledge-bases'
      fullPath: '/knowledge-bases/'
      preLoaderRoute: typeof AuthedTenantKnowledgeBasesIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/inbox/': {
      id: '/_authed/_tenant/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthedTenantInboxIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/humans/': {
      id: '/_authed/_tenant/humans/'
      path: '/humans'
      fullPath: '/humans/'
      preLoaderRoute: typeof AuthedTenantHumansIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/artifacts/': {
      id: '/_authed/_tenant/artifacts/'
      path: '/artifacts'
      fullPath: '/artifacts/'
      preLoaderRoute: typeof AuthedTenantArtifactsIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/': {
      id: '/_authed/_tenant/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedTenantAgentsIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agent-templates/': {
      id: '/_authed/_tenant/agent-templates/'
      path: '/agent-templates'
      fullPath: '/agent-templates/'
      preLoaderRoute: typeof AuthedTenantAgentTemplatesIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/webhooks/$webhookId': {
      id: '/_authed/_tenant/webhooks/$webhookId'
      path: '/webhooks/$webhookId'
      fullPath: '/webhooks/$webhookId'
      preLoaderRoute: typeof AuthedTenantWebhooksWebhookIdRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/threads/$threadId': {
      id: '/_authed/_tenant/threads/$threadId'
      path: '/threads/$threadId'
      fullPath: '/threads/$threadId'
      preLoaderRoute: typeof AuthedTenantThreadsThreadIdRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/skills/builder': {
      id: '/_authed/_tenant/skills/builder'
      path: '/skills/builder'
      fullPath: '/skills/builder'
      preLoaderRoute: typeof AuthedTenantSkillsBuilderRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/skills/$slug': {
      id: '/_authed/_tenant/skills/$slug'
      path: '/skills/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof AuthedTenantSkillsSlugRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/scheduled-jobs/$scheduledJobId': {
      id: '/_authed/_tenant/scheduled-jobs/$scheduledJobId'
      path: '/scheduled-jobs/$scheduledJobId'
      fullPath: '/scheduled-jobs/$scheduledJobId'
      preLoaderRoute: typeof AuthedTenantScheduledJobsScheduledJobIdRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/routines/$routineId': {
      id: '/_authed/_tenant/routines/$routineId'
      path: '/routines/$routineId'
      fullPath: '/routines/$routineId'
      preLoaderRoute: typeof AuthedTenantRoutinesRoutineIdRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/knowledge-bases/$kbId': {
      id: '/_authed/_tenant/knowledge-bases/$kbId'
      path: '/knowledge-bases/$kbId'
      fullPath: '/knowledge-bases/$kbId'
      preLoaderRoute: typeof AuthedTenantKnowledgeBasesKbIdRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/inbox/$inboxItemId': {
      id: '/_authed/_tenant/inbox/$inboxItemId'
      path: '/inbox/$inboxItemId'
      fullPath: '/inbox/$inboxItemId'
      preLoaderRoute: typeof AuthedTenantInboxInboxItemIdRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/new': {
      id: '/_authed/_tenant/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthedTenantAgentsNewRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/invites': {
      id: '/_authed/_tenant/agents/invites'
      path: '/agents/invites'
      fullPath: '/agents/invites'
      preLoaderRoute: typeof AuthedTenantAgentsInvitesRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/$agentId': {
      id: '/_authed/_tenant/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthedTenantAgentsAgentIdRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agent-templates/defaults': {
      id: '/_authed/_tenant/agent-templates/defaults'
      path: '/agent-templates/defaults'
      fullPath: '/agent-templates/defaults'
      preLoaderRoute: typeof AuthedTenantAgentTemplatesDefaultsRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agent-templates/$templateId': {
      id: '/_authed/_tenant/agent-templates/$templateId'
      path: '/agent-templates/$templateId'
      fullPath: '/agent-templates/$templateId'
      preLoaderRoute: typeof AuthedTenantAgentTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/$agentId_/workspaces': {
      id: '/_authed/_tenant/agents/$agentId_/workspaces'
      path: '/agents/$agentId/workspaces'
      fullPath: '/agents/$agentId/workspaces'
      preLoaderRoute: typeof AuthedTenantAgentsAgentIdWorkspacesRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/$agentId_/workspace': {
      id: '/_authed/_tenant/agents/$agentId_/workspace'
      path: '/agents/$agentId/workspace'
      fullPath: '/agents/$agentId/workspace'
      preLoaderRoute: typeof AuthedTenantAgentsAgentIdWorkspaceRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/$agentId_/sub-agents': {
      id: '/_authed/_tenant/agents/$agentId_/sub-agents'
      path: '/agents/$agentId/sub-agents'
      fullPath: '/agents/$agentId/sub-agents'
      preLoaderRoute: typeof AuthedTenantAgentsAgentIdSubAgentsRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/$agentId_/skills': {
      id: '/_authed/_tenant/agents/$agentId_/skills'
      path: '/agents/$agentId/skills'
      fullPath: '/agents/$agentId/skills'
      preLoaderRoute: typeof AuthedTenantAgentsAgentIdSkillsRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/$agentId_/memory': {
      id: '/_authed/_tenant/agents/$agentId_/memory'
      path: '/agents/$agentId/memory'
      fullPath: '/agents/$agentId/memory'
      preLoaderRoute: typeof AuthedTenantAgentsAgentIdMemoryRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/$agentId_/knowledge': {
      id: '/_authed/_tenant/agents/$agentId_/knowledge'
      path: '/agents/$agentId/knowledge'
      fullPath: '/agents/$agentId/knowledge'
      preLoaderRoute: typeof AuthedTenantAgentsAgentIdKnowledgeRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agent-templates/$templateId_/sync': {
      id: '/_authed/_tenant/agent-templates/$templateId_/sync'
      path: '/agent-templates/$templateId/sync'
      fullPath: '/agent-templates/$templateId/sync'
      preLoaderRoute: typeof AuthedTenantAgentTemplatesTemplateIdSyncRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/$agentId_/scheduled-jobs/': {
      id: '/_authed/_tenant/agents/$agentId_/scheduled-jobs/'
      path: '/agents/$agentId/scheduled-jobs'
      fullPath: '/agents/$agentId/scheduled-jobs/'
      preLoaderRoute: typeof AuthedTenantAgentsAgentIdScheduledJobsIndexRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
    '/_authed/_tenant/agents/$agentId_/scheduled-jobs/$scheduledJobId': {
      id: '/_authed/_tenant/agents/$agentId_/scheduled-jobs/$scheduledJobId'
      path: '/agents/$agentId/scheduled-jobs/$scheduledJobId'
      fullPath: '/agents/$agentId/scheduled-jobs/$scheduledJobId'
      preLoaderRoute: typeof AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRouteImport
      parentRoute: typeof AuthedTenantRoute
    }
  }
}

interface AuthedTenantRouteChildren {
  AuthedTenantActivityRoute: typeof AuthedTenantActivityRoute
  AuthedTenantCostsRoute: typeof AuthedTenantCostsRoute
  AuthedTenantDashboardRoute: typeof AuthedTenantDashboardRoute
  AuthedTenantOrgRoute: typeof AuthedTenantOrgRoute
  AuthedTenantPerformanceRoute: typeof AuthedTenantPerformanceRoute
  AuthedTenantSettingsRoute: typeof AuthedTenantSettingsRoute
  AuthedTenantAgentTemplatesTemplateIdRoute: typeof AuthedTenantAgentTemplatesTemplateIdRoute
  AuthedTenantAgentTemplatesDefaultsRoute: typeof AuthedTenantAgentTemplatesDefaultsRoute
  AuthedTenantAgentsAgentIdRoute: typeof AuthedTenantAgentsAgentIdRoute
  AuthedTenantAgentsInvitesRoute: typeof AuthedTenantAgentsInvitesRoute
  AuthedTenantAgentsNewRoute: typeof AuthedTenantAgentsNewRoute
  AuthedTenantInboxInboxItemIdRoute: typeof AuthedTenantInboxInboxItemIdRoute
  AuthedTenantKnowledgeBasesKbIdRoute: typeof AuthedTenantKnowledgeBasesKbIdRoute
  AuthedTenantRoutinesRoutineIdRoute: typeof AuthedTenantRoutinesRoutineIdRoute
  AuthedTenantScheduledJobsScheduledJobIdRoute: typeof AuthedTenantScheduledJobsScheduledJobIdRoute
  AuthedTenantSkillsSlugRoute: typeof AuthedTenantSkillsSlugRoute
  AuthedTenantSkillsBuilderRoute: typeof AuthedTenantSkillsBuilderRoute
  AuthedTenantThreadsThreadIdRoute: typeof AuthedTenantThreadsThreadIdRoute
  AuthedTenantWebhooksWebhookIdRoute: typeof AuthedTenantWebhooksWebhookIdRoute
  AuthedTenantAgentTemplatesIndexRoute: typeof AuthedTenantAgentTemplatesIndexRoute
  AuthedTenantAgentsIndexRoute: typeof AuthedTenantAgentsIndexRoute
  AuthedTenantArtifactsIndexRoute: typeof AuthedTenantArtifactsIndexRoute
  AuthedTenantHumansIndexRoute: typeof AuthedTenantHumansIndexRoute
  AuthedTenantInboxIndexRoute: typeof AuthedTenantInboxIndexRoute
  AuthedTenantKnowledgeBasesIndexRoute: typeof AuthedTenantKnowledgeBasesIndexRoute
  AuthedTenantMemoryIndexRoute: typeof AuthedTenantMemoryIndexRoute
  AuthedTenantRoutinesIndexRoute: typeof AuthedTenantRoutinesIndexRoute
  AuthedTenantScheduledJobsIndexRoute: typeof AuthedTenantScheduledJobsIndexRoute
  AuthedTenantSecurityIndexRoute: typeof AuthedTenantSecurityIndexRoute
  AuthedTenantSkillsIndexRoute: typeof AuthedTenantSkillsIndexRoute
  AuthedTenantThreadsIndexRoute: typeof AuthedTenantThreadsIndexRoute
  AuthedTenantWebhooksIndexRoute: typeof AuthedTenantWebhooksIndexRoute
  AuthedTenantAgentTemplatesTemplateIdSyncRoute: typeof AuthedTenantAgentTemplatesTemplateIdSyncRoute
  AuthedTenantAgentsAgentIdKnowledgeRoute: typeof AuthedTenantAgentsAgentIdKnowledgeRoute
  AuthedTenantAgentsAgentIdMemoryRoute: typeof AuthedTenantAgentsAgentIdMemoryRoute
  AuthedTenantAgentsAgentIdSkillsRoute: typeof AuthedTenantAgentsAgentIdSkillsRoute
  AuthedTenantAgentsAgentIdSubAgentsRoute: typeof AuthedTenantAgentsAgentIdSubAgentsRoute
  AuthedTenantAgentsAgentIdWorkspaceRoute: typeof AuthedTenantAgentsAgentIdWorkspaceRoute
  AuthedTenantAgentsAgentIdWorkspacesRoute: typeof AuthedTenantAgentsAgentIdWorkspacesRoute
  AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRoute: typeof AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRoute
  AuthedTenantAgentsAgentIdScheduledJobsIndexRoute: typeof AuthedTenantAgentsAgentIdScheduledJobsIndexRoute
}

const AuthedTenantRouteChildren: AuthedTenantRouteChildren = {
  AuthedTenantActivityRoute: AuthedTenantActivityRoute,
  AuthedTenantCostsRoute: AuthedTenantCostsRoute,
  AuthedTenantDashboardRoute: AuthedTenantDashboardRoute,
  AuthedTenantOrgRoute: AuthedTenantOrgRoute,
  AuthedTenantPerformanceRoute: AuthedTenantPerformanceRoute,
  AuthedTenantSettingsRoute: AuthedTenantSettingsRoute,
  AuthedTenantAgentTemplatesTemplateIdRoute:
    AuthedTenantAgentTemplatesTemplateIdRoute,
  AuthedTenantAgentTemplatesDefaultsRoute:
    AuthedTenantAgentTemplatesDefaultsRoute,
  AuthedTenantAgentsAgentIdRoute: AuthedTenantAgentsAgentIdRoute,
  AuthedTenantAgentsInvitesRoute: AuthedTenantAgentsInvitesRoute,
  AuthedTenantAgentsNewRoute: AuthedTenantAgentsNewRoute,
  AuthedTenantInboxInboxItemIdRoute: AuthedTenantInboxInboxItemIdRoute,
  AuthedTenantKnowledgeBasesKbIdRoute: AuthedTenantKnowledgeBasesKbIdRoute,
  AuthedTenantRoutinesRoutineIdRoute: AuthedTenantRoutinesRoutineIdRoute,
  AuthedTenantScheduledJobsScheduledJobIdRoute:
    AuthedTenantScheduledJobsScheduledJobIdRoute,
  AuthedTenantSkillsSlugRoute: AuthedTenantSkillsSlugRoute,
  AuthedTenantSkillsBuilderRoute: AuthedTenantSkillsBuilderRoute,
  AuthedTenantThreadsThreadIdRoute: AuthedTenantThreadsThreadIdRoute,
  AuthedTenantWebhooksWebhookIdRoute: AuthedTenantWebhooksWebhookIdRoute,
  AuthedTenantAgentTemplatesIndexRoute: AuthedTenantAgentTemplatesIndexRoute,
  AuthedTenantAgentsIndexRoute: AuthedTenantAgentsIndexRoute,
  AuthedTenantArtifactsIndexRoute: AuthedTenantArtifactsIndexRoute,
  AuthedTenantHumansIndexRoute: AuthedTenantHumansIndexRoute,
  AuthedTenantInboxIndexRoute: AuthedTenantInboxIndexRoute,
  AuthedTenantKnowledgeBasesIndexRoute: AuthedTenantKnowledgeBasesIndexRoute,
  AuthedTenantMemoryIndexRoute: AuthedTenantMemoryIndexRoute,
  AuthedTenantRoutinesIndexRoute: AuthedTenantRoutinesIndexRoute,
  AuthedTenantScheduledJobsIndexRoute: AuthedTenantScheduledJobsIndexRoute,
  AuthedTenantSecurityIndexRoute: AuthedTenantSecurityIndexRoute,
  AuthedTenantSkillsIndexRoute: AuthedTenantSkillsIndexRoute,
  AuthedTenantThreadsIndexRoute: AuthedTenantThreadsIndexRoute,
  AuthedTenantWebhooksIndexRoute: AuthedTenantWebhooksIndexRoute,
  AuthedTenantAgentTemplatesTemplateIdSyncRoute:
    AuthedTenantAgentTemplatesTemplateIdSyncRoute,
  AuthedTenantAgentsAgentIdKnowledgeRoute:
    AuthedTenantAgentsAgentIdKnowledgeRoute,
  AuthedTenantAgentsAgentIdMemoryRoute: AuthedTenantAgentsAgentIdMemoryRoute,
  AuthedTenantAgentsAgentIdSkillsRoute: AuthedTenantAgentsAgentIdSkillsRoute,
  AuthedTenantAgentsAgentIdSubAgentsRoute:
    AuthedTenantAgentsAgentIdSubAgentsRoute,
  AuthedTenantAgentsAgentIdWorkspaceRoute:
    AuthedTenantAgentsAgentIdWorkspaceRoute,
  AuthedTenantAgentsAgentIdWorkspacesRoute:
    AuthedTenantAgentsAgentIdWorkspacesRoute,
  AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRoute:
    AuthedTenantAgentsAgentIdScheduledJobsScheduledJobIdRoute,
  AuthedTenantAgentsAgentIdScheduledJobsIndexRoute:
    AuthedTenantAgentsAgentIdScheduledJobsIndexRoute,
}

const AuthedTenantRouteWithChildren = AuthedTenantRoute._addFileChildren(
  AuthedTenantRouteChildren,
)

interface AuthedRouteChildren {
  AuthedTenantRoute: typeof AuthedTenantRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedTenantRoute: AuthedTenantRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
