/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OnboardingWelcomeRouteImport } from "./routes/onboarding/welcome";
import { Route as InviteTokenRouteImport } from "./routes/invite.$token";
import { Route as AuthCallbackRouteImport } from "./routes/auth/callback";
import { Route as AuthedTenantRouteImport } from "./routes/_authed/_tenant";
import { Route as AuthedTenantSettingsRouteImport } from "./routes/_authed/_tenant/settings";
import { Route as AuthedTenantOrgRouteImport } from "./routes/_authed/_tenant/org";
import { Route as AuthedTenantOntologyRouteImport } from "./routes/_authed/_tenant/ontology";
import { Route as AuthedTenantKnowledgeRouteImport } from "./routes/_authed/_tenant/knowledge";
import { Route as AuthedTenantDashboardRouteImport } from "./routes/_authed/_tenant/dashboard";
import { Route as AuthedTenantCapabilitiesRouteImport } from "./routes/_authed/_tenant/capabilities";
import { Route as AuthedTenantBillingRouteImport } from "./routes/_authed/_tenant/billing";
import { Route as AuthedTenantAnalyticsRouteImport } from "./routes/_authed/_tenant/analytics";
import { Route as AuthedTenantAgentRouteImport } from "./routes/_authed/_tenant/agent";
import { Route as AuthedTenantComplianceRouteRouteImport } from "./routes/_authed/_tenant/compliance/route";
import { Route as AuthedTenantWorkspaceReviewsIndexRouteImport } from "./routes/_authed/_tenant/workspace-reviews/index";
import { Route as AuthedTenantWikiIndexRouteImport } from "./routes/_authed/_tenant/wiki/index";
import { Route as AuthedTenantWebhooksIndexRouteImport } from "./routes/_authed/_tenant/webhooks/index";
import { Route as AuthedTenantUsersIndexRouteImport } from "./routes/_authed/_tenant/users/index";
import { Route as AuthedTenantThreadsIndexRouteImport } from "./routes/_authed/_tenant/threads/index";
import { Route as AuthedTenantSpacesIndexRouteImport } from "./routes/_authed/_tenant/spaces/index";
import { Route as AuthedTenantSlackIndexRouteImport } from "./routes/_authed/_tenant/slack/index";
import { Route as AuthedTenantSecurityIndexRouteImport } from "./routes/_authed/_tenant/security/index";
import { Route as AuthedTenantScheduledJobsIndexRouteImport } from "./routes/_authed/_tenant/scheduled-jobs/index";
import { Route as AuthedTenantRoutinesIndexRouteImport } from "./routes/_authed/_tenant/routines/index";
import { Route as AuthedTenantMemoryIndexRouteImport } from "./routes/_authed/_tenant/memory/index";
import { Route as AuthedTenantKnowledgeIndexRouteImport } from "./routes/_authed/_tenant/knowledge/index";
import { Route as AuthedTenantKnowledgeBasesIndexRouteImport } from "./routes/_authed/_tenant/knowledge-bases/index";
import { Route as AuthedTenantInboxIndexRouteImport } from "./routes/_authed/_tenant/inbox/index";
import { Route as AuthedTenantEvaluationsIndexRouteImport } from "./routes/_authed/_tenant/evaluations/index";
import { Route as AuthedTenantComputersIndexRouteImport } from "./routes/_authed/_tenant/computers/index";
import { Route as AuthedTenantComplianceIndexRouteImport } from "./routes/_authed/_tenant/compliance/index";
import { Route as AuthedTenantCapabilitiesIndexRouteImport } from "./routes/_authed/_tenant/capabilities/index";
import { Route as AuthedTenantAutomationsIndexRouteImport } from "./routes/_authed/_tenant/automations/index";
import { Route as AuthedTenantArtifactsIndexRouteImport } from "./routes/_authed/_tenant/artifacts/index";
import { Route as AuthedTenantAppletsIndexRouteImport } from "./routes/_authed/_tenant/applets/index";
import { Route as AuthedTenantAnalyticsIndexRouteImport } from "./routes/_authed/_tenant/analytics/index";
import { Route as AuthedTenantAgentIndexRouteImport } from "./routes/_authed/_tenant/agent/index";
import { Route as AuthedTenantWebhooksWebhookIdRouteImport } from "./routes/_authed/_tenant/webhooks/$webhookId";
import { Route as AuthedTenantUsersUserIdRouteImport } from "./routes/_authed/_tenant/users/$userId";
import { Route as AuthedTenantThreadsThreadIdRouteImport } from "./routes/_authed/_tenant/threads/$threadId";
import { Route as AuthedTenantSpacesSpaceIdRouteImport } from "./routes/_authed/_tenant/spaces/$spaceId";
import { Route as AuthedTenantScheduledJobsScheduledJobIdRouteImport } from "./routes/_authed/_tenant/scheduled-jobs/$scheduledJobId";
import { Route as AuthedTenantRoutinesRoutineIdRouteImport } from "./routes/_authed/_tenant/routines/$routineId";
import { Route as AuthedTenantKnowledgeWikiRouteImport } from "./routes/_authed/_tenant/knowledge/wiki";
import { Route as AuthedTenantKnowledgeUserRouteImport } from "./routes/_authed/_tenant/knowledge/user";
import { Route as AuthedTenantKnowledgeMemoryRouteImport } from "./routes/_authed/_tenant/knowledge/memory";
import { Route as AuthedTenantKnowledgeKnowledgeBasesRouteImport } from "./routes/_authed/_tenant/knowledge/knowledge-bases";
import { Route as AuthedTenantKnowledgeContextEngineRouteImport } from "./routes/_authed/_tenant/knowledge/context-engine";
import { Route as AuthedTenantKnowledgeBasesKbIdRouteImport } from "./routes/_authed/_tenant/knowledge-bases/$kbId";
import { Route as AuthedTenantInboxInboxItemIdRouteImport } from "./routes/_authed/_tenant/inbox/$inboxItemId";
import { Route as AuthedTenantExtensionsExtensionIdRouteImport } from "./routes/_authed/_tenant/extensions/$extensionId";
import { Route as AuthedTenantEvaluationsRunIdRouteImport } from "./routes/_authed/_tenant/evaluations/$runId";
import { Route as AuthedTenantComputersComputerIdRouteImport } from "./routes/_authed/_tenant/computers/$computerId";
import { Route as AuthedTenantCapabilitiesMcpServersRouteImport } from "./routes/_authed/_tenant/capabilities/mcp-servers";
import { Route as AuthedTenantCapabilitiesBuiltinToolsRouteImport } from "./routes/_authed/_tenant/capabilities/builtin-tools";
import { Route as AuthedTenantAppletsAppIdRouteImport } from "./routes/_authed/_tenant/applets/$appId";
import { Route as AuthedTenantAnalyticsPerformanceRouteImport } from "./routes/_authed/_tenant/analytics/performance";
import { Route as AuthedTenantAnalyticsCostRouteImport } from "./routes/_authed/_tenant/analytics/cost";
import { Route as AuthedTenantAnalyticsActivityRouteImport } from "./routes/_authed/_tenant/analytics/activity";
import { Route as AuthedTenantAgentFilesRouteImport } from "./routes/_authed/_tenant/agent/files";
import { Route as AuthedTenantAgentConfigRouteImport } from "./routes/_authed/_tenant/agent/config";
import { Route as AuthedTenantEvaluationsStudioIndexRouteImport } from "./routes/_authed/_tenant/evaluations/studio/index";
import { Route as AuthedTenantComplianceExportsIndexRouteImport } from "./routes/_authed/_tenant/compliance/exports/index";
import { Route as AuthedTenantCapabilitiesSkillsIndexRouteImport } from "./routes/_authed/_tenant/capabilities/skills/index";
import { Route as AuthedTenantCapabilitiesPluginsIndexRouteImport } from "./routes/_authed/_tenant/capabilities/plugins/index";
import { Route as AuthedTenantAutomationsWebhooksIndexRouteImport } from "./routes/_authed/_tenant/automations/webhooks/index";
import { Route as AuthedTenantAutomationsSchedulesIndexRouteImport } from "./routes/_authed/_tenant/automations/schedules/index";
import { Route as AuthedTenantAutomationsRoutinesIndexRouteImport } from "./routes/_authed/_tenant/automations/routines/index";
import { Route as AuthedTenantAutomationsCredentialsIndexRouteImport } from "./routes/_authed/_tenant/automations/credentials/index";
import { Route as AuthedTenantSpacesSpaceIdWorkspaceRouteImport } from "./routes/_authed/_tenant/spaces/$spaceId_.workspace";
import { Route as AuthedTenantSpacesSpaceIdMemoryRouteImport } from "./routes/_authed/_tenant/spaces/$spaceId_.memory";
import { Route as AuthedTenantSpacesSpaceIdConfigurationRouteImport } from "./routes/_authed/_tenant/spaces/$spaceId_.configuration";
import { Route as AuthedTenantSpacesSpaceIdAutomationsRouteImport } from "./routes/_authed/_tenant/spaces/$spaceId_.automations";
import { Route as AuthedTenantKnowledgeKnowledgeBasesKbIdRouteImport } from "./routes/_authed/_tenant/knowledge/knowledge-bases/$kbId";
import { Route as AuthedTenantEvaluationsStudioNewRouteImport } from "./routes/_authed/_tenant/evaluations/studio/new";
import { Route as AuthedTenantEvaluationsStudioTestCaseIdRouteImport } from "./routes/_authed/_tenant/evaluations/studio/$testCaseId";
import { Route as AuthedTenantComplianceEventsEventIdRouteImport } from "./routes/_authed/_tenant/compliance/events.$eventId";
import { Route as AuthedTenantCapabilitiesSkillsBuilderRouteImport } from "./routes/_authed/_tenant/capabilities/skills/builder";
import { Route as AuthedTenantCapabilitiesSkillsSlugRouteImport } from "./routes/_authed/_tenant/capabilities/skills/$slug";
import { Route as AuthedTenantCapabilitiesPluginsUploadIdRouteImport } from "./routes/_authed/_tenant/capabilities/plugins/$uploadId";
import { Route as AuthedTenantAutomationsWebhooksWebhookIdRouteImport } from "./routes/_authed/_tenant/automations/webhooks/$webhookId";
import { Route as AuthedTenantAutomationsSchedulesScheduledJobIdRouteImport } from "./routes/_authed/_tenant/automations/schedules/$scheduledJobId";
import { Route as AuthedTenantAutomationsRoutinesNewRouteImport } from "./routes/_authed/_tenant/automations/routines/new";
import { Route as AuthedTenantAutomationsRoutinesRoutineIdRouteImport } from "./routes/_authed/_tenant/automations/routines/$routineId";
import { Route as AuthedTenantAutomationsCredentialsCredentialIdRouteImport } from "./routes/_authed/_tenant/automations/credentials/$credentialId";
import { Route as AuthedTenantEvaluationsStudioEditTestCaseIdRouteImport } from "./routes/_authed/_tenant/evaluations/studio/edit.$testCaseId";
import { Route as AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRouteImport } from "./routes/_authed/_tenant/automations/routines/$routineId_.executions.$executionId";

const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: "/onboarding/welcome",
  path: "/onboarding/welcome",
  getParentRoute: () => rootRouteImport,
} as any);
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: "/invite/$token",
  path: "/invite/$token",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedTenantRoute = AuthedTenantRouteImport.update({
  id: "/_tenant",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedTenantSettingsRoute = AuthedTenantSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantOrgRoute = AuthedTenantOrgRouteImport.update({
  id: "/org",
  path: "/org",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantOntologyRoute = AuthedTenantOntologyRouteImport.update({
  id: "/ontology",
  path: "/ontology",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantKnowledgeRoute = AuthedTenantKnowledgeRouteImport.update({
  id: "/knowledge",
  path: "/knowledge",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantDashboardRoute = AuthedTenantDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantCapabilitiesRoute =
  AuthedTenantCapabilitiesRouteImport.update({
    id: "/capabilities",
    path: "/capabilities",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantBillingRoute = AuthedTenantBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantAnalyticsRoute = AuthedTenantAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantAgentRoute = AuthedTenantAgentRouteImport.update({
  id: "/agent",
  path: "/agent",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantComplianceRouteRoute =
  AuthedTenantComplianceRouteRouteImport.update({
    id: "/compliance",
    path: "/compliance",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantWorkspaceReviewsIndexRoute =
  AuthedTenantWorkspaceReviewsIndexRouteImport.update({
    id: "/workspace-reviews/",
    path: "/workspace-reviews/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantWikiIndexRoute = AuthedTenantWikiIndexRouteImport.update({
  id: "/wiki/",
  path: "/wiki/",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantWebhooksIndexRoute =
  AuthedTenantWebhooksIndexRouteImport.update({
    id: "/webhooks/",
    path: "/webhooks/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantUsersIndexRoute = AuthedTenantUsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantThreadsIndexRoute =
  AuthedTenantThreadsIndexRouteImport.update({
    id: "/threads/",
    path: "/threads/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantSpacesIndexRoute = AuthedTenantSpacesIndexRouteImport.update({
  id: "/spaces/",
  path: "/spaces/",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantSlackIndexRoute = AuthedTenantSlackIndexRouteImport.update({
  id: "/slack/",
  path: "/slack/",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantSecurityIndexRoute =
  AuthedTenantSecurityIndexRouteImport.update({
    id: "/security/",
    path: "/security/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantScheduledJobsIndexRoute =
  AuthedTenantScheduledJobsIndexRouteImport.update({
    id: "/scheduled-jobs/",
    path: "/scheduled-jobs/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantRoutinesIndexRoute =
  AuthedTenantRoutinesIndexRouteImport.update({
    id: "/routines/",
    path: "/routines/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantMemoryIndexRoute = AuthedTenantMemoryIndexRouteImport.update({
  id: "/memory/",
  path: "/memory/",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantKnowledgeIndexRoute =
  AuthedTenantKnowledgeIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedTenantKnowledgeRoute,
  } as any);
const AuthedTenantKnowledgeBasesIndexRoute =
  AuthedTenantKnowledgeBasesIndexRouteImport.update({
    id: "/knowledge-bases/",
    path: "/knowledge-bases/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantInboxIndexRoute = AuthedTenantInboxIndexRouteImport.update({
  id: "/inbox/",
  path: "/inbox/",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantEvaluationsIndexRoute =
  AuthedTenantEvaluationsIndexRouteImport.update({
    id: "/evaluations/",
    path: "/evaluations/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantComputersIndexRoute =
  AuthedTenantComputersIndexRouteImport.update({
    id: "/computers/",
    path: "/computers/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantComplianceIndexRoute =
  AuthedTenantComplianceIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedTenantComplianceRouteRoute,
  } as any);
const AuthedTenantCapabilitiesIndexRoute =
  AuthedTenantCapabilitiesIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedTenantCapabilitiesRoute,
  } as any);
const AuthedTenantAutomationsIndexRoute =
  AuthedTenantAutomationsIndexRouteImport.update({
    id: "/automations/",
    path: "/automations/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantArtifactsIndexRoute =
  AuthedTenantArtifactsIndexRouteImport.update({
    id: "/artifacts/",
    path: "/artifacts/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAppletsIndexRoute =
  AuthedTenantAppletsIndexRouteImport.update({
    id: "/applets/",
    path: "/applets/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAnalyticsIndexRoute =
  AuthedTenantAnalyticsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedTenantAnalyticsRoute,
  } as any);
const AuthedTenantAgentIndexRoute = AuthedTenantAgentIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedTenantAgentRoute,
} as any);
const AuthedTenantWebhooksWebhookIdRoute =
  AuthedTenantWebhooksWebhookIdRouteImport.update({
    id: "/webhooks/$webhookId",
    path: "/webhooks/$webhookId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantUsersUserIdRoute = AuthedTenantUsersUserIdRouteImport.update({
  id: "/users/$userId",
  path: "/users/$userId",
  getParentRoute: () => AuthedTenantRoute,
} as any);
const AuthedTenantThreadsThreadIdRoute =
  AuthedTenantThreadsThreadIdRouteImport.update({
    id: "/threads/$threadId",
    path: "/threads/$threadId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantSpacesSpaceIdRoute =
  AuthedTenantSpacesSpaceIdRouteImport.update({
    id: "/spaces/$spaceId",
    path: "/spaces/$spaceId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantScheduledJobsScheduledJobIdRoute =
  AuthedTenantScheduledJobsScheduledJobIdRouteImport.update({
    id: "/scheduled-jobs/$scheduledJobId",
    path: "/scheduled-jobs/$scheduledJobId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantRoutinesRoutineIdRoute =
  AuthedTenantRoutinesRoutineIdRouteImport.update({
    id: "/routines/$routineId",
    path: "/routines/$routineId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantKnowledgeWikiRoute =
  AuthedTenantKnowledgeWikiRouteImport.update({
    id: "/wiki",
    path: "/wiki",
    getParentRoute: () => AuthedTenantKnowledgeRoute,
  } as any);
const AuthedTenantKnowledgeUserRoute =
  AuthedTenantKnowledgeUserRouteImport.update({
    id: "/user",
    path: "/user",
    getParentRoute: () => AuthedTenantKnowledgeRoute,
  } as any);
const AuthedTenantKnowledgeMemoryRoute =
  AuthedTenantKnowledgeMemoryRouteImport.update({
    id: "/memory",
    path: "/memory",
    getParentRoute: () => AuthedTenantKnowledgeRoute,
  } as any);
const AuthedTenantKnowledgeKnowledgeBasesRoute =
  AuthedTenantKnowledgeKnowledgeBasesRouteImport.update({
    id: "/knowledge-bases",
    path: "/knowledge-bases",
    getParentRoute: () => AuthedTenantKnowledgeRoute,
  } as any);
const AuthedTenantKnowledgeContextEngineRoute =
  AuthedTenantKnowledgeContextEngineRouteImport.update({
    id: "/context-engine",
    path: "/context-engine",
    getParentRoute: () => AuthedTenantKnowledgeRoute,
  } as any);
const AuthedTenantKnowledgeBasesKbIdRoute =
  AuthedTenantKnowledgeBasesKbIdRouteImport.update({
    id: "/knowledge-bases/$kbId",
    path: "/knowledge-bases/$kbId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantInboxInboxItemIdRoute =
  AuthedTenantInboxInboxItemIdRouteImport.update({
    id: "/inbox/$inboxItemId",
    path: "/inbox/$inboxItemId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantExtensionsExtensionIdRoute =
  AuthedTenantExtensionsExtensionIdRouteImport.update({
    id: "/extensions/$extensionId",
    path: "/extensions/$extensionId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantEvaluationsRunIdRoute =
  AuthedTenantEvaluationsRunIdRouteImport.update({
    id: "/evaluations/$runId",
    path: "/evaluations/$runId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantComputersComputerIdRoute =
  AuthedTenantComputersComputerIdRouteImport.update({
    id: "/computers/$computerId",
    path: "/computers/$computerId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantCapabilitiesMcpServersRoute =
  AuthedTenantCapabilitiesMcpServersRouteImport.update({
    id: "/mcp-servers",
    path: "/mcp-servers",
    getParentRoute: () => AuthedTenantCapabilitiesRoute,
  } as any);
const AuthedTenantCapabilitiesBuiltinToolsRoute =
  AuthedTenantCapabilitiesBuiltinToolsRouteImport.update({
    id: "/builtin-tools",
    path: "/builtin-tools",
    getParentRoute: () => AuthedTenantCapabilitiesRoute,
  } as any);
const AuthedTenantAppletsAppIdRoute =
  AuthedTenantAppletsAppIdRouteImport.update({
    id: "/applets/$appId",
    path: "/applets/$appId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAnalyticsPerformanceRoute =
  AuthedTenantAnalyticsPerformanceRouteImport.update({
    id: "/performance",
    path: "/performance",
    getParentRoute: () => AuthedTenantAnalyticsRoute,
  } as any);
const AuthedTenantAnalyticsCostRoute =
  AuthedTenantAnalyticsCostRouteImport.update({
    id: "/cost",
    path: "/cost",
    getParentRoute: () => AuthedTenantAnalyticsRoute,
  } as any);
const AuthedTenantAnalyticsActivityRoute =
  AuthedTenantAnalyticsActivityRouteImport.update({
    id: "/activity",
    path: "/activity",
    getParentRoute: () => AuthedTenantAnalyticsRoute,
  } as any);
const AuthedTenantAgentFilesRoute = AuthedTenantAgentFilesRouteImport.update({
  id: "/files",
  path: "/files",
  getParentRoute: () => AuthedTenantAgentRoute,
} as any);
const AuthedTenantAgentConfigRoute = AuthedTenantAgentConfigRouteImport.update({
  id: "/config",
  path: "/config",
  getParentRoute: () => AuthedTenantAgentRoute,
} as any);
const AuthedTenantEvaluationsStudioIndexRoute =
  AuthedTenantEvaluationsStudioIndexRouteImport.update({
    id: "/evaluations/studio/",
    path: "/evaluations/studio/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantComplianceExportsIndexRoute =
  AuthedTenantComplianceExportsIndexRouteImport.update({
    id: "/exports/",
    path: "/exports/",
    getParentRoute: () => AuthedTenantComplianceRouteRoute,
  } as any);
const AuthedTenantCapabilitiesSkillsIndexRoute =
  AuthedTenantCapabilitiesSkillsIndexRouteImport.update({
    id: "/skills/",
    path: "/skills/",
    getParentRoute: () => AuthedTenantCapabilitiesRoute,
  } as any);
const AuthedTenantCapabilitiesPluginsIndexRoute =
  AuthedTenantCapabilitiesPluginsIndexRouteImport.update({
    id: "/plugins/",
    path: "/plugins/",
    getParentRoute: () => AuthedTenantCapabilitiesRoute,
  } as any);
const AuthedTenantAutomationsWebhooksIndexRoute =
  AuthedTenantAutomationsWebhooksIndexRouteImport.update({
    id: "/automations/webhooks/",
    path: "/automations/webhooks/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAutomationsSchedulesIndexRoute =
  AuthedTenantAutomationsSchedulesIndexRouteImport.update({
    id: "/automations/schedules/",
    path: "/automations/schedules/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAutomationsRoutinesIndexRoute =
  AuthedTenantAutomationsRoutinesIndexRouteImport.update({
    id: "/automations/routines/",
    path: "/automations/routines/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAutomationsCredentialsIndexRoute =
  AuthedTenantAutomationsCredentialsIndexRouteImport.update({
    id: "/automations/credentials/",
    path: "/automations/credentials/",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantSpacesSpaceIdWorkspaceRoute =
  AuthedTenantSpacesSpaceIdWorkspaceRouteImport.update({
    id: "/spaces/$spaceId_/workspace",
    path: "/spaces/$spaceId/workspace",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantSpacesSpaceIdMemoryRoute =
  AuthedTenantSpacesSpaceIdMemoryRouteImport.update({
    id: "/spaces/$spaceId_/memory",
    path: "/spaces/$spaceId/memory",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantSpacesSpaceIdConfigurationRoute =
  AuthedTenantSpacesSpaceIdConfigurationRouteImport.update({
    id: "/spaces/$spaceId_/configuration",
    path: "/spaces/$spaceId/configuration",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantSpacesSpaceIdAutomationsRoute =
  AuthedTenantSpacesSpaceIdAutomationsRouteImport.update({
    id: "/spaces/$spaceId_/automations",
    path: "/spaces/$spaceId/automations",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantKnowledgeKnowledgeBasesKbIdRoute =
  AuthedTenantKnowledgeKnowledgeBasesKbIdRouteImport.update({
    id: "/$kbId",
    path: "/$kbId",
    getParentRoute: () => AuthedTenantKnowledgeKnowledgeBasesRoute,
  } as any);
const AuthedTenantEvaluationsStudioNewRoute =
  AuthedTenantEvaluationsStudioNewRouteImport.update({
    id: "/evaluations/studio/new",
    path: "/evaluations/studio/new",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantEvaluationsStudioTestCaseIdRoute =
  AuthedTenantEvaluationsStudioTestCaseIdRouteImport.update({
    id: "/evaluations/studio/$testCaseId",
    path: "/evaluations/studio/$testCaseId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantComplianceEventsEventIdRoute =
  AuthedTenantComplianceEventsEventIdRouteImport.update({
    id: "/events/$eventId",
    path: "/events/$eventId",
    getParentRoute: () => AuthedTenantComplianceRouteRoute,
  } as any);
const AuthedTenantCapabilitiesSkillsBuilderRoute =
  AuthedTenantCapabilitiesSkillsBuilderRouteImport.update({
    id: "/skills/builder",
    path: "/skills/builder",
    getParentRoute: () => AuthedTenantCapabilitiesRoute,
  } as any);
const AuthedTenantCapabilitiesSkillsSlugRoute =
  AuthedTenantCapabilitiesSkillsSlugRouteImport.update({
    id: "/skills/$slug",
    path: "/skills/$slug",
    getParentRoute: () => AuthedTenantCapabilitiesRoute,
  } as any);
const AuthedTenantCapabilitiesPluginsUploadIdRoute =
  AuthedTenantCapabilitiesPluginsUploadIdRouteImport.update({
    id: "/plugins/$uploadId",
    path: "/plugins/$uploadId",
    getParentRoute: () => AuthedTenantCapabilitiesRoute,
  } as any);
const AuthedTenantAutomationsWebhooksWebhookIdRoute =
  AuthedTenantAutomationsWebhooksWebhookIdRouteImport.update({
    id: "/automations/webhooks/$webhookId",
    path: "/automations/webhooks/$webhookId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAutomationsSchedulesScheduledJobIdRoute =
  AuthedTenantAutomationsSchedulesScheduledJobIdRouteImport.update({
    id: "/automations/schedules/$scheduledJobId",
    path: "/automations/schedules/$scheduledJobId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAutomationsRoutinesNewRoute =
  AuthedTenantAutomationsRoutinesNewRouteImport.update({
    id: "/automations/routines/new",
    path: "/automations/routines/new",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAutomationsRoutinesRoutineIdRoute =
  AuthedTenantAutomationsRoutinesRoutineIdRouteImport.update({
    id: "/automations/routines/$routineId",
    path: "/automations/routines/$routineId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAutomationsCredentialsCredentialIdRoute =
  AuthedTenantAutomationsCredentialsCredentialIdRouteImport.update({
    id: "/automations/credentials/$credentialId",
    path: "/automations/credentials/$credentialId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantEvaluationsStudioEditTestCaseIdRoute =
  AuthedTenantEvaluationsStudioEditTestCaseIdRouteImport.update({
    id: "/evaluations/studio/edit/$testCaseId",
    path: "/evaluations/studio/edit/$testCaseId",
    getParentRoute: () => AuthedTenantRoute,
  } as any);
const AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRoute =
  AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRouteImport.update(
    {
      id: "/automations/routines/$routineId_/executions/$executionId",
      path: "/automations/routines/$routineId/executions/$executionId",
      getParentRoute: () => AuthedTenantRoute,
    } as any,
  );

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/sign-in": typeof SignInRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/invite/$token": typeof InviteTokenRoute;
  "/onboarding/welcome": typeof OnboardingWelcomeRoute;
  "/compliance": typeof AuthedTenantComplianceRouteRouteWithChildren;
  "/agent": typeof AuthedTenantAgentRouteWithChildren;
  "/analytics": typeof AuthedTenantAnalyticsRouteWithChildren;
  "/billing": typeof AuthedTenantBillingRoute;
  "/capabilities": typeof AuthedTenantCapabilitiesRouteWithChildren;
  "/dashboard": typeof AuthedTenantDashboardRoute;
  "/knowledge": typeof AuthedTenantKnowledgeRouteWithChildren;
  "/ontology": typeof AuthedTenantOntologyRoute;
  "/org": typeof AuthedTenantOrgRoute;
  "/settings": typeof AuthedTenantSettingsRoute;
  "/agent/config": typeof AuthedTenantAgentConfigRoute;
  "/agent/files": typeof AuthedTenantAgentFilesRoute;
  "/analytics/activity": typeof AuthedTenantAnalyticsActivityRoute;
  "/analytics/cost": typeof AuthedTenantAnalyticsCostRoute;
  "/analytics/performance": typeof AuthedTenantAnalyticsPerformanceRoute;
  "/applets/$appId": typeof AuthedTenantAppletsAppIdRoute;
  "/capabilities/builtin-tools": typeof AuthedTenantCapabilitiesBuiltinToolsRoute;
  "/capabilities/mcp-servers": typeof AuthedTenantCapabilitiesMcpServersRoute;
  "/computers/$computerId": typeof AuthedTenantComputersComputerIdRoute;
  "/evaluations/$runId": typeof AuthedTenantEvaluationsRunIdRoute;
  "/extensions/$extensionId": typeof AuthedTenantExtensionsExtensionIdRoute;
  "/inbox/$inboxItemId": typeof AuthedTenantInboxInboxItemIdRoute;
  "/knowledge-bases/$kbId": typeof AuthedTenantKnowledgeBasesKbIdRoute;
  "/knowledge/context-engine": typeof AuthedTenantKnowledgeContextEngineRoute;
  "/knowledge/knowledge-bases": typeof AuthedTenantKnowledgeKnowledgeBasesRouteWithChildren;
  "/knowledge/memory": typeof AuthedTenantKnowledgeMemoryRoute;
  "/knowledge/user": typeof AuthedTenantKnowledgeUserRoute;
  "/knowledge/wiki": typeof AuthedTenantKnowledgeWikiRoute;
  "/routines/$routineId": typeof AuthedTenantRoutinesRoutineIdRoute;
  "/scheduled-jobs/$scheduledJobId": typeof AuthedTenantScheduledJobsScheduledJobIdRoute;
  "/spaces/$spaceId": typeof AuthedTenantSpacesSpaceIdRoute;
  "/threads/$threadId": typeof AuthedTenantThreadsThreadIdRoute;
  "/users/$userId": typeof AuthedTenantUsersUserIdRoute;
  "/webhooks/$webhookId": typeof AuthedTenantWebhooksWebhookIdRoute;
  "/agent/": typeof AuthedTenantAgentIndexRoute;
  "/analytics/": typeof AuthedTenantAnalyticsIndexRoute;
  "/applets/": typeof AuthedTenantAppletsIndexRoute;
  "/artifacts/": typeof AuthedTenantArtifactsIndexRoute;
  "/automations/": typeof AuthedTenantAutomationsIndexRoute;
  "/capabilities/": typeof AuthedTenantCapabilitiesIndexRoute;
  "/compliance/": typeof AuthedTenantComplianceIndexRoute;
  "/computers/": typeof AuthedTenantComputersIndexRoute;
  "/evaluations/": typeof AuthedTenantEvaluationsIndexRoute;
  "/inbox/": typeof AuthedTenantInboxIndexRoute;
  "/knowledge-bases/": typeof AuthedTenantKnowledgeBasesIndexRoute;
  "/knowledge/": typeof AuthedTenantKnowledgeIndexRoute;
  "/memory/": typeof AuthedTenantMemoryIndexRoute;
  "/routines/": typeof AuthedTenantRoutinesIndexRoute;
  "/scheduled-jobs/": typeof AuthedTenantScheduledJobsIndexRoute;
  "/security/": typeof AuthedTenantSecurityIndexRoute;
  "/slack/": typeof AuthedTenantSlackIndexRoute;
  "/spaces/": typeof AuthedTenantSpacesIndexRoute;
  "/threads/": typeof AuthedTenantThreadsIndexRoute;
  "/users/": typeof AuthedTenantUsersIndexRoute;
  "/webhooks/": typeof AuthedTenantWebhooksIndexRoute;
  "/wiki/": typeof AuthedTenantWikiIndexRoute;
  "/workspace-reviews/": typeof AuthedTenantWorkspaceReviewsIndexRoute;
  "/automations/credentials/$credentialId": typeof AuthedTenantAutomationsCredentialsCredentialIdRoute;
  "/automations/routines/$routineId": typeof AuthedTenantAutomationsRoutinesRoutineIdRoute;
  "/automations/routines/new": typeof AuthedTenantAutomationsRoutinesNewRoute;
  "/automations/schedules/$scheduledJobId": typeof AuthedTenantAutomationsSchedulesScheduledJobIdRoute;
  "/automations/webhooks/$webhookId": typeof AuthedTenantAutomationsWebhooksWebhookIdRoute;
  "/capabilities/plugins/$uploadId": typeof AuthedTenantCapabilitiesPluginsUploadIdRoute;
  "/capabilities/skills/$slug": typeof AuthedTenantCapabilitiesSkillsSlugRoute;
  "/capabilities/skills/builder": typeof AuthedTenantCapabilitiesSkillsBuilderRoute;
  "/compliance/events/$eventId": typeof AuthedTenantComplianceEventsEventIdRoute;
  "/evaluations/studio/$testCaseId": typeof AuthedTenantEvaluationsStudioTestCaseIdRoute;
  "/evaluations/studio/new": typeof AuthedTenantEvaluationsStudioNewRoute;
  "/knowledge/knowledge-bases/$kbId": typeof AuthedTenantKnowledgeKnowledgeBasesKbIdRoute;
  "/spaces/$spaceId/automations": typeof AuthedTenantSpacesSpaceIdAutomationsRoute;
  "/spaces/$spaceId/configuration": typeof AuthedTenantSpacesSpaceIdConfigurationRoute;
  "/spaces/$spaceId/memory": typeof AuthedTenantSpacesSpaceIdMemoryRoute;
  "/spaces/$spaceId/workspace": typeof AuthedTenantSpacesSpaceIdWorkspaceRoute;
  "/automations/credentials/": typeof AuthedTenantAutomationsCredentialsIndexRoute;
  "/automations/routines/": typeof AuthedTenantAutomationsRoutinesIndexRoute;
  "/automations/schedules/": typeof AuthedTenantAutomationsSchedulesIndexRoute;
  "/automations/webhooks/": typeof AuthedTenantAutomationsWebhooksIndexRoute;
  "/capabilities/plugins/": typeof AuthedTenantCapabilitiesPluginsIndexRoute;
  "/capabilities/skills/": typeof AuthedTenantCapabilitiesSkillsIndexRoute;
  "/compliance/exports/": typeof AuthedTenantComplianceExportsIndexRoute;
  "/evaluations/studio/": typeof AuthedTenantEvaluationsStudioIndexRoute;
  "/evaluations/studio/edit/$testCaseId": typeof AuthedTenantEvaluationsStudioEditTestCaseIdRoute;
  "/automations/routines/$routineId/executions/$executionId": typeof AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/sign-in": typeof SignInRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/invite/$token": typeof InviteTokenRoute;
  "/onboarding/welcome": typeof OnboardingWelcomeRoute;
  "/billing": typeof AuthedTenantBillingRoute;
  "/dashboard": typeof AuthedTenantDashboardRoute;
  "/ontology": typeof AuthedTenantOntologyRoute;
  "/org": typeof AuthedTenantOrgRoute;
  "/settings": typeof AuthedTenantSettingsRoute;
  "/agent/config": typeof AuthedTenantAgentConfigRoute;
  "/agent/files": typeof AuthedTenantAgentFilesRoute;
  "/analytics/activity": typeof AuthedTenantAnalyticsActivityRoute;
  "/analytics/cost": typeof AuthedTenantAnalyticsCostRoute;
  "/analytics/performance": typeof AuthedTenantAnalyticsPerformanceRoute;
  "/applets/$appId": typeof AuthedTenantAppletsAppIdRoute;
  "/capabilities/builtin-tools": typeof AuthedTenantCapabilitiesBuiltinToolsRoute;
  "/capabilities/mcp-servers": typeof AuthedTenantCapabilitiesMcpServersRoute;
  "/computers/$computerId": typeof AuthedTenantComputersComputerIdRoute;
  "/evaluations/$runId": typeof AuthedTenantEvaluationsRunIdRoute;
  "/extensions/$extensionId": typeof AuthedTenantExtensionsExtensionIdRoute;
  "/inbox/$inboxItemId": typeof AuthedTenantInboxInboxItemIdRoute;
  "/knowledge-bases/$kbId": typeof AuthedTenantKnowledgeBasesKbIdRoute;
  "/knowledge/context-engine": typeof AuthedTenantKnowledgeContextEngineRoute;
  "/knowledge/knowledge-bases": typeof AuthedTenantKnowledgeKnowledgeBasesRouteWithChildren;
  "/knowledge/memory": typeof AuthedTenantKnowledgeMemoryRoute;
  "/knowledge/user": typeof AuthedTenantKnowledgeUserRoute;
  "/knowledge/wiki": typeof AuthedTenantKnowledgeWikiRoute;
  "/routines/$routineId": typeof AuthedTenantRoutinesRoutineIdRoute;
  "/scheduled-jobs/$scheduledJobId": typeof AuthedTenantScheduledJobsScheduledJobIdRoute;
  "/spaces/$spaceId": typeof AuthedTenantSpacesSpaceIdRoute;
  "/threads/$threadId": typeof AuthedTenantThreadsThreadIdRoute;
  "/users/$userId": typeof AuthedTenantUsersUserIdRoute;
  "/webhooks/$webhookId": typeof AuthedTenantWebhooksWebhookIdRoute;
  "/agent": typeof AuthedTenantAgentIndexRoute;
  "/analytics": typeof AuthedTenantAnalyticsIndexRoute;
  "/applets": typeof AuthedTenantAppletsIndexRoute;
  "/artifacts": typeof AuthedTenantArtifactsIndexRoute;
  "/automations": typeof AuthedTenantAutomationsIndexRoute;
  "/capabilities": typeof AuthedTenantCapabilitiesIndexRoute;
  "/compliance": typeof AuthedTenantComplianceIndexRoute;
  "/computers": typeof AuthedTenantComputersIndexRoute;
  "/evaluations": typeof AuthedTenantEvaluationsIndexRoute;
  "/inbox": typeof AuthedTenantInboxIndexRoute;
  "/knowledge-bases": typeof AuthedTenantKnowledgeBasesIndexRoute;
  "/knowledge": typeof AuthedTenantKnowledgeIndexRoute;
  "/memory": typeof AuthedTenantMemoryIndexRoute;
  "/routines": typeof AuthedTenantRoutinesIndexRoute;
  "/scheduled-jobs": typeof AuthedTenantScheduledJobsIndexRoute;
  "/security": typeof AuthedTenantSecurityIndexRoute;
  "/slack": typeof AuthedTenantSlackIndexRoute;
  "/spaces": typeof AuthedTenantSpacesIndexRoute;
  "/threads": typeof AuthedTenantThreadsIndexRoute;
  "/users": typeof AuthedTenantUsersIndexRoute;
  "/webhooks": typeof AuthedTenantWebhooksIndexRoute;
  "/wiki": typeof AuthedTenantWikiIndexRoute;
  "/workspace-reviews": typeof AuthedTenantWorkspaceReviewsIndexRoute;
  "/automations/credentials/$credentialId": typeof AuthedTenantAutomationsCredentialsCredentialIdRoute;
  "/automations/routines/$routineId": typeof AuthedTenantAutomationsRoutinesRoutineIdRoute;
  "/automations/routines/new": typeof AuthedTenantAutomationsRoutinesNewRoute;
  "/automations/schedules/$scheduledJobId": typeof AuthedTenantAutomationsSchedulesScheduledJobIdRoute;
  "/automations/webhooks/$webhookId": typeof AuthedTenantAutomationsWebhooksWebhookIdRoute;
  "/capabilities/plugins/$uploadId": typeof AuthedTenantCapabilitiesPluginsUploadIdRoute;
  "/capabilities/skills/$slug": typeof AuthedTenantCapabilitiesSkillsSlugRoute;
  "/capabilities/skills/builder": typeof AuthedTenantCapabilitiesSkillsBuilderRoute;
  "/compliance/events/$eventId": typeof AuthedTenantComplianceEventsEventIdRoute;
  "/evaluations/studio/$testCaseId": typeof AuthedTenantEvaluationsStudioTestCaseIdRoute;
  "/evaluations/studio/new": typeof AuthedTenantEvaluationsStudioNewRoute;
  "/knowledge/knowledge-bases/$kbId": typeof AuthedTenantKnowledgeKnowledgeBasesKbIdRoute;
  "/spaces/$spaceId/automations": typeof AuthedTenantSpacesSpaceIdAutomationsRoute;
  "/spaces/$spaceId/configuration": typeof AuthedTenantSpacesSpaceIdConfigurationRoute;
  "/spaces/$spaceId/memory": typeof AuthedTenantSpacesSpaceIdMemoryRoute;
  "/spaces/$spaceId/workspace": typeof AuthedTenantSpacesSpaceIdWorkspaceRoute;
  "/automations/credentials": typeof AuthedTenantAutomationsCredentialsIndexRoute;
  "/automations/routines": typeof AuthedTenantAutomationsRoutinesIndexRoute;
  "/automations/schedules": typeof AuthedTenantAutomationsSchedulesIndexRoute;
  "/automations/webhooks": typeof AuthedTenantAutomationsWebhooksIndexRoute;
  "/capabilities/plugins": typeof AuthedTenantCapabilitiesPluginsIndexRoute;
  "/capabilities/skills": typeof AuthedTenantCapabilitiesSkillsIndexRoute;
  "/compliance/exports": typeof AuthedTenantComplianceExportsIndexRoute;
  "/evaluations/studio": typeof AuthedTenantEvaluationsStudioIndexRoute;
  "/evaluations/studio/edit/$testCaseId": typeof AuthedTenantEvaluationsStudioEditTestCaseIdRoute;
  "/automations/routines/$routineId/executions/$executionId": typeof AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/sign-in": typeof SignInRoute;
  "/_authed/_tenant": typeof AuthedTenantRouteWithChildren;
  "/auth/callback": typeof AuthCallbackRoute;
  "/invite/$token": typeof InviteTokenRoute;
  "/onboarding/welcome": typeof OnboardingWelcomeRoute;
  "/_authed/_tenant/compliance": typeof AuthedTenantComplianceRouteRouteWithChildren;
  "/_authed/_tenant/agent": typeof AuthedTenantAgentRouteWithChildren;
  "/_authed/_tenant/analytics": typeof AuthedTenantAnalyticsRouteWithChildren;
  "/_authed/_tenant/billing": typeof AuthedTenantBillingRoute;
  "/_authed/_tenant/capabilities": typeof AuthedTenantCapabilitiesRouteWithChildren;
  "/_authed/_tenant/dashboard": typeof AuthedTenantDashboardRoute;
  "/_authed/_tenant/knowledge": typeof AuthedTenantKnowledgeRouteWithChildren;
  "/_authed/_tenant/ontology": typeof AuthedTenantOntologyRoute;
  "/_authed/_tenant/org": typeof AuthedTenantOrgRoute;
  "/_authed/_tenant/settings": typeof AuthedTenantSettingsRoute;
  "/_authed/_tenant/agent/config": typeof AuthedTenantAgentConfigRoute;
  "/_authed/_tenant/agent/files": typeof AuthedTenantAgentFilesRoute;
  "/_authed/_tenant/analytics/activity": typeof AuthedTenantAnalyticsActivityRoute;
  "/_authed/_tenant/analytics/cost": typeof AuthedTenantAnalyticsCostRoute;
  "/_authed/_tenant/analytics/performance": typeof AuthedTenantAnalyticsPerformanceRoute;
  "/_authed/_tenant/applets/$appId": typeof AuthedTenantAppletsAppIdRoute;
  "/_authed/_tenant/capabilities/builtin-tools": typeof AuthedTenantCapabilitiesBuiltinToolsRoute;
  "/_authed/_tenant/capabilities/mcp-servers": typeof AuthedTenantCapabilitiesMcpServersRoute;
  "/_authed/_tenant/computers/$computerId": typeof AuthedTenantComputersComputerIdRoute;
  "/_authed/_tenant/evaluations/$runId": typeof AuthedTenantEvaluationsRunIdRoute;
  "/_authed/_tenant/extensions/$extensionId": typeof AuthedTenantExtensionsExtensionIdRoute;
  "/_authed/_tenant/inbox/$inboxItemId": typeof AuthedTenantInboxInboxItemIdRoute;
  "/_authed/_tenant/knowledge-bases/$kbId": typeof AuthedTenantKnowledgeBasesKbIdRoute;
  "/_authed/_tenant/knowledge/context-engine": typeof AuthedTenantKnowledgeContextEngineRoute;
  "/_authed/_tenant/knowledge/knowledge-bases": typeof AuthedTenantKnowledgeKnowledgeBasesRouteWithChildren;
  "/_authed/_tenant/knowledge/memory": typeof AuthedTenantKnowledgeMemoryRoute;
  "/_authed/_tenant/knowledge/user": typeof AuthedTenantKnowledgeUserRoute;
  "/_authed/_tenant/knowledge/wiki": typeof AuthedTenantKnowledgeWikiRoute;
  "/_authed/_tenant/routines/$routineId": typeof AuthedTenantRoutinesRoutineIdRoute;
  "/_authed/_tenant/scheduled-jobs/$scheduledJobId": typeof AuthedTenantScheduledJobsScheduledJobIdRoute;
  "/_authed/_tenant/spaces/$spaceId": typeof AuthedTenantSpacesSpaceIdRoute;
  "/_authed/_tenant/threads/$threadId": typeof AuthedTenantThreadsThreadIdRoute;
  "/_authed/_tenant/users/$userId": typeof AuthedTenantUsersUserIdRoute;
  "/_authed/_tenant/webhooks/$webhookId": typeof AuthedTenantWebhooksWebhookIdRoute;
  "/_authed/_tenant/agent/": typeof AuthedTenantAgentIndexRoute;
  "/_authed/_tenant/analytics/": typeof AuthedTenantAnalyticsIndexRoute;
  "/_authed/_tenant/applets/": typeof AuthedTenantAppletsIndexRoute;
  "/_authed/_tenant/artifacts/": typeof AuthedTenantArtifactsIndexRoute;
  "/_authed/_tenant/automations/": typeof AuthedTenantAutomationsIndexRoute;
  "/_authed/_tenant/capabilities/": typeof AuthedTenantCapabilitiesIndexRoute;
  "/_authed/_tenant/compliance/": typeof AuthedTenantComplianceIndexRoute;
  "/_authed/_tenant/computers/": typeof AuthedTenantComputersIndexRoute;
  "/_authed/_tenant/evaluations/": typeof AuthedTenantEvaluationsIndexRoute;
  "/_authed/_tenant/inbox/": typeof AuthedTenantInboxIndexRoute;
  "/_authed/_tenant/knowledge-bases/": typeof AuthedTenantKnowledgeBasesIndexRoute;
  "/_authed/_tenant/knowledge/": typeof AuthedTenantKnowledgeIndexRoute;
  "/_authed/_tenant/memory/": typeof AuthedTenantMemoryIndexRoute;
  "/_authed/_tenant/routines/": typeof AuthedTenantRoutinesIndexRoute;
  "/_authed/_tenant/scheduled-jobs/": typeof AuthedTenantScheduledJobsIndexRoute;
  "/_authed/_tenant/security/": typeof AuthedTenantSecurityIndexRoute;
  "/_authed/_tenant/slack/": typeof AuthedTenantSlackIndexRoute;
  "/_authed/_tenant/spaces/": typeof AuthedTenantSpacesIndexRoute;
  "/_authed/_tenant/threads/": typeof AuthedTenantThreadsIndexRoute;
  "/_authed/_tenant/users/": typeof AuthedTenantUsersIndexRoute;
  "/_authed/_tenant/webhooks/": typeof AuthedTenantWebhooksIndexRoute;
  "/_authed/_tenant/wiki/": typeof AuthedTenantWikiIndexRoute;
  "/_authed/_tenant/workspace-reviews/": typeof AuthedTenantWorkspaceReviewsIndexRoute;
  "/_authed/_tenant/automations/credentials/$credentialId": typeof AuthedTenantAutomationsCredentialsCredentialIdRoute;
  "/_authed/_tenant/automations/routines/$routineId": typeof AuthedTenantAutomationsRoutinesRoutineIdRoute;
  "/_authed/_tenant/automations/routines/new": typeof AuthedTenantAutomationsRoutinesNewRoute;
  "/_authed/_tenant/automations/schedules/$scheduledJobId": typeof AuthedTenantAutomationsSchedulesScheduledJobIdRoute;
  "/_authed/_tenant/automations/webhooks/$webhookId": typeof AuthedTenantAutomationsWebhooksWebhookIdRoute;
  "/_authed/_tenant/capabilities/plugins/$uploadId": typeof AuthedTenantCapabilitiesPluginsUploadIdRoute;
  "/_authed/_tenant/capabilities/skills/$slug": typeof AuthedTenantCapabilitiesSkillsSlugRoute;
  "/_authed/_tenant/capabilities/skills/builder": typeof AuthedTenantCapabilitiesSkillsBuilderRoute;
  "/_authed/_tenant/compliance/events/$eventId": typeof AuthedTenantComplianceEventsEventIdRoute;
  "/_authed/_tenant/evaluations/studio/$testCaseId": typeof AuthedTenantEvaluationsStudioTestCaseIdRoute;
  "/_authed/_tenant/evaluations/studio/new": typeof AuthedTenantEvaluationsStudioNewRoute;
  "/_authed/_tenant/knowledge/knowledge-bases/$kbId": typeof AuthedTenantKnowledgeKnowledgeBasesKbIdRoute;
  "/_authed/_tenant/spaces/$spaceId_/automations": typeof AuthedTenantSpacesSpaceIdAutomationsRoute;
  "/_authed/_tenant/spaces/$spaceId_/configuration": typeof AuthedTenantSpacesSpaceIdConfigurationRoute;
  "/_authed/_tenant/spaces/$spaceId_/memory": typeof AuthedTenantSpacesSpaceIdMemoryRoute;
  "/_authed/_tenant/spaces/$spaceId_/workspace": typeof AuthedTenantSpacesSpaceIdWorkspaceRoute;
  "/_authed/_tenant/automations/credentials/": typeof AuthedTenantAutomationsCredentialsIndexRoute;
  "/_authed/_tenant/automations/routines/": typeof AuthedTenantAutomationsRoutinesIndexRoute;
  "/_authed/_tenant/automations/schedules/": typeof AuthedTenantAutomationsSchedulesIndexRoute;
  "/_authed/_tenant/automations/webhooks/": typeof AuthedTenantAutomationsWebhooksIndexRoute;
  "/_authed/_tenant/capabilities/plugins/": typeof AuthedTenantCapabilitiesPluginsIndexRoute;
  "/_authed/_tenant/capabilities/skills/": typeof AuthedTenantCapabilitiesSkillsIndexRoute;
  "/_authed/_tenant/compliance/exports/": typeof AuthedTenantComplianceExportsIndexRoute;
  "/_authed/_tenant/evaluations/studio/": typeof AuthedTenantEvaluationsStudioIndexRoute;
  "/_authed/_tenant/evaluations/studio/edit/$testCaseId": typeof AuthedTenantEvaluationsStudioEditTestCaseIdRoute;
  "/_authed/_tenant/automations/routines/$routineId_/executions/$executionId": typeof AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/forgot-password"
    | "/sign-in"
    | "/auth/callback"
    | "/invite/$token"
    | "/onboarding/welcome"
    | "/compliance"
    | "/agent"
    | "/analytics"
    | "/billing"
    | "/capabilities"
    | "/dashboard"
    | "/knowledge"
    | "/ontology"
    | "/org"
    | "/settings"
    | "/agent/config"
    | "/agent/files"
    | "/analytics/activity"
    | "/analytics/cost"
    | "/analytics/performance"
    | "/applets/$appId"
    | "/capabilities/builtin-tools"
    | "/capabilities/mcp-servers"
    | "/computers/$computerId"
    | "/evaluations/$runId"
    | "/extensions/$extensionId"
    | "/inbox/$inboxItemId"
    | "/knowledge-bases/$kbId"
    | "/knowledge/context-engine"
    | "/knowledge/knowledge-bases"
    | "/knowledge/memory"
    | "/knowledge/user"
    | "/knowledge/wiki"
    | "/routines/$routineId"
    | "/scheduled-jobs/$scheduledJobId"
    | "/spaces/$spaceId"
    | "/threads/$threadId"
    | "/users/$userId"
    | "/webhooks/$webhookId"
    | "/agent/"
    | "/analytics/"
    | "/applets/"
    | "/artifacts/"
    | "/automations/"
    | "/capabilities/"
    | "/compliance/"
    | "/computers/"
    | "/evaluations/"
    | "/inbox/"
    | "/knowledge-bases/"
    | "/knowledge/"
    | "/memory/"
    | "/routines/"
    | "/scheduled-jobs/"
    | "/security/"
    | "/slack/"
    | "/spaces/"
    | "/threads/"
    | "/users/"
    | "/webhooks/"
    | "/wiki/"
    | "/workspace-reviews/"
    | "/automations/credentials/$credentialId"
    | "/automations/routines/$routineId"
    | "/automations/routines/new"
    | "/automations/schedules/$scheduledJobId"
    | "/automations/webhooks/$webhookId"
    | "/capabilities/plugins/$uploadId"
    | "/capabilities/skills/$slug"
    | "/capabilities/skills/builder"
    | "/compliance/events/$eventId"
    | "/evaluations/studio/$testCaseId"
    | "/evaluations/studio/new"
    | "/knowledge/knowledge-bases/$kbId"
    | "/spaces/$spaceId/automations"
    | "/spaces/$spaceId/configuration"
    | "/spaces/$spaceId/memory"
    | "/spaces/$spaceId/workspace"
    | "/automations/credentials/"
    | "/automations/routines/"
    | "/automations/schedules/"
    | "/automations/webhooks/"
    | "/capabilities/plugins/"
    | "/capabilities/skills/"
    | "/compliance/exports/"
    | "/evaluations/studio/"
    | "/evaluations/studio/edit/$testCaseId"
    | "/automations/routines/$routineId/executions/$executionId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/forgot-password"
    | "/sign-in"
    | "/auth/callback"
    | "/invite/$token"
    | "/onboarding/welcome"
    | "/billing"
    | "/dashboard"
    | "/ontology"
    | "/org"
    | "/settings"
    | "/agent/config"
    | "/agent/files"
    | "/analytics/activity"
    | "/analytics/cost"
    | "/analytics/performance"
    | "/applets/$appId"
    | "/capabilities/builtin-tools"
    | "/capabilities/mcp-servers"
    | "/computers/$computerId"
    | "/evaluations/$runId"
    | "/extensions/$extensionId"
    | "/inbox/$inboxItemId"
    | "/knowledge-bases/$kbId"
    | "/knowledge/context-engine"
    | "/knowledge/knowledge-bases"
    | "/knowledge/memory"
    | "/knowledge/user"
    | "/knowledge/wiki"
    | "/routines/$routineId"
    | "/scheduled-jobs/$scheduledJobId"
    | "/spaces/$spaceId"
    | "/threads/$threadId"
    | "/users/$userId"
    | "/webhooks/$webhookId"
    | "/agent"
    | "/analytics"
    | "/applets"
    | "/artifacts"
    | "/automations"
    | "/capabilities"
    | "/compliance"
    | "/computers"
    | "/evaluations"
    | "/inbox"
    | "/knowledge-bases"
    | "/knowledge"
    | "/memory"
    | "/routines"
    | "/scheduled-jobs"
    | "/security"
    | "/slack"
    | "/spaces"
    | "/threads"
    | "/users"
    | "/webhooks"
    | "/wiki"
    | "/workspace-reviews"
    | "/automations/credentials/$credentialId"
    | "/automations/routines/$routineId"
    | "/automations/routines/new"
    | "/automations/schedules/$scheduledJobId"
    | "/automations/webhooks/$webhookId"
    | "/capabilities/plugins/$uploadId"
    | "/capabilities/skills/$slug"
    | "/capabilities/skills/builder"
    | "/compliance/events/$eventId"
    | "/evaluations/studio/$testCaseId"
    | "/evaluations/studio/new"
    | "/knowledge/knowledge-bases/$kbId"
    | "/spaces/$spaceId/automations"
    | "/spaces/$spaceId/configuration"
    | "/spaces/$spaceId/memory"
    | "/spaces/$spaceId/workspace"
    | "/automations/credentials"
    | "/automations/routines"
    | "/automations/schedules"
    | "/automations/webhooks"
    | "/capabilities/plugins"
    | "/capabilities/skills"
    | "/compliance/exports"
    | "/evaluations/studio"
    | "/evaluations/studio/edit/$testCaseId"
    | "/automations/routines/$routineId/executions/$executionId";
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/forgot-password"
    | "/sign-in"
    | "/_authed/_tenant"
    | "/auth/callback"
    | "/invite/$token"
    | "/onboarding/welcome"
    | "/_authed/_tenant/compliance"
    | "/_authed/_tenant/agent"
    | "/_authed/_tenant/analytics"
    | "/_authed/_tenant/billing"
    | "/_authed/_tenant/capabilities"
    | "/_authed/_tenant/dashboard"
    | "/_authed/_tenant/knowledge"
    | "/_authed/_tenant/ontology"
    | "/_authed/_tenant/org"
    | "/_authed/_tenant/settings"
    | "/_authed/_tenant/agent/config"
    | "/_authed/_tenant/agent/files"
    | "/_authed/_tenant/analytics/activity"
    | "/_authed/_tenant/analytics/cost"
    | "/_authed/_tenant/analytics/performance"
    | "/_authed/_tenant/applets/$appId"
    | "/_authed/_tenant/capabilities/builtin-tools"
    | "/_authed/_tenant/capabilities/mcp-servers"
    | "/_authed/_tenant/computers/$computerId"
    | "/_authed/_tenant/evaluations/$runId"
    | "/_authed/_tenant/extensions/$extensionId"
    | "/_authed/_tenant/inbox/$inboxItemId"
    | "/_authed/_tenant/knowledge-bases/$kbId"
    | "/_authed/_tenant/knowledge/context-engine"
    | "/_authed/_tenant/knowledge/knowledge-bases"
    | "/_authed/_tenant/knowledge/memory"
    | "/_authed/_tenant/knowledge/user"
    | "/_authed/_tenant/knowledge/wiki"
    | "/_authed/_tenant/routines/$routineId"
    | "/_authed/_tenant/scheduled-jobs/$scheduledJobId"
    | "/_authed/_tenant/spaces/$spaceId"
    | "/_authed/_tenant/threads/$threadId"
    | "/_authed/_tenant/users/$userId"
    | "/_authed/_tenant/webhooks/$webhookId"
    | "/_authed/_tenant/agent/"
    | "/_authed/_tenant/analytics/"
    | "/_authed/_tenant/applets/"
    | "/_authed/_tenant/artifacts/"
    | "/_authed/_tenant/automations/"
    | "/_authed/_tenant/capabilities/"
    | "/_authed/_tenant/compliance/"
    | "/_authed/_tenant/computers/"
    | "/_authed/_tenant/evaluations/"
    | "/_authed/_tenant/inbox/"
    | "/_authed/_tenant/knowledge-bases/"
    | "/_authed/_tenant/knowledge/"
    | "/_authed/_tenant/memory/"
    | "/_authed/_tenant/routines/"
    | "/_authed/_tenant/scheduled-jobs/"
    | "/_authed/_tenant/security/"
    | "/_authed/_tenant/slack/"
    | "/_authed/_tenant/spaces/"
    | "/_authed/_tenant/threads/"
    | "/_authed/_tenant/users/"
    | "/_authed/_tenant/webhooks/"
    | "/_authed/_tenant/wiki/"
    | "/_authed/_tenant/workspace-reviews/"
    | "/_authed/_tenant/automations/credentials/$credentialId"
    | "/_authed/_tenant/automations/routines/$routineId"
    | "/_authed/_tenant/automations/routines/new"
    | "/_authed/_tenant/automations/schedules/$scheduledJobId"
    | "/_authed/_tenant/automations/webhooks/$webhookId"
    | "/_authed/_tenant/capabilities/plugins/$uploadId"
    | "/_authed/_tenant/capabilities/skills/$slug"
    | "/_authed/_tenant/capabilities/skills/builder"
    | "/_authed/_tenant/compliance/events/$eventId"
    | "/_authed/_tenant/evaluations/studio/$testCaseId"
    | "/_authed/_tenant/evaluations/studio/new"
    | "/_authed/_tenant/knowledge/knowledge-bases/$kbId"
    | "/_authed/_tenant/spaces/$spaceId_/automations"
    | "/_authed/_tenant/spaces/$spaceId_/configuration"
    | "/_authed/_tenant/spaces/$spaceId_/memory"
    | "/_authed/_tenant/spaces/$spaceId_/workspace"
    | "/_authed/_tenant/automations/credentials/"
    | "/_authed/_tenant/automations/routines/"
    | "/_authed/_tenant/automations/schedules/"
    | "/_authed/_tenant/automations/webhooks/"
    | "/_authed/_tenant/capabilities/plugins/"
    | "/_authed/_tenant/capabilities/skills/"
    | "/_authed/_tenant/compliance/exports/"
    | "/_authed/_tenant/evaluations/studio/"
    | "/_authed/_tenant/evaluations/studio/edit/$testCaseId"
    | "/_authed/_tenant/automations/routines/$routineId_/executions/$executionId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  SignInRoute: typeof SignInRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
  InviteTokenRoute: typeof InviteTokenRoute;
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forgot-password": {
      id: "/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding/welcome": {
      id: "/onboarding/welcome";
      path: "/onboarding/welcome";
      fullPath: "/onboarding/welcome";
      preLoaderRoute: typeof OnboardingWelcomeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/invite/$token": {
      id: "/invite/$token";
      path: "/invite/$token";
      fullPath: "/invite/$token";
      preLoaderRoute: typeof InviteTokenRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/_tenant": {
      id: "/_authed/_tenant";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedTenantRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/_tenant/settings": {
      id: "/_authed/_tenant/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthedTenantSettingsRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/org": {
      id: "/_authed/_tenant/org";
      path: "/org";
      fullPath: "/org";
      preLoaderRoute: typeof AuthedTenantOrgRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/ontology": {
      id: "/_authed/_tenant/ontology";
      path: "/ontology";
      fullPath: "/ontology";
      preLoaderRoute: typeof AuthedTenantOntologyRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/knowledge": {
      id: "/_authed/_tenant/knowledge";
      path: "/knowledge";
      fullPath: "/knowledge";
      preLoaderRoute: typeof AuthedTenantKnowledgeRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/dashboard": {
      id: "/_authed/_tenant/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthedTenantDashboardRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/capabilities": {
      id: "/_authed/_tenant/capabilities";
      path: "/capabilities";
      fullPath: "/capabilities";
      preLoaderRoute: typeof AuthedTenantCapabilitiesRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/billing": {
      id: "/_authed/_tenant/billing";
      path: "/billing";
      fullPath: "/billing";
      preLoaderRoute: typeof AuthedTenantBillingRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/analytics": {
      id: "/_authed/_tenant/analytics";
      path: "/analytics";
      fullPath: "/analytics";
      preLoaderRoute: typeof AuthedTenantAnalyticsRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/agent": {
      id: "/_authed/_tenant/agent";
      path: "/agent";
      fullPath: "/agent";
      preLoaderRoute: typeof AuthedTenantAgentRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/compliance": {
      id: "/_authed/_tenant/compliance";
      path: "/compliance";
      fullPath: "/compliance";
      preLoaderRoute: typeof AuthedTenantComplianceRouteRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/workspace-reviews/": {
      id: "/_authed/_tenant/workspace-reviews/";
      path: "/workspace-reviews";
      fullPath: "/workspace-reviews/";
      preLoaderRoute: typeof AuthedTenantWorkspaceReviewsIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/wiki/": {
      id: "/_authed/_tenant/wiki/";
      path: "/wiki";
      fullPath: "/wiki/";
      preLoaderRoute: typeof AuthedTenantWikiIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/webhooks/": {
      id: "/_authed/_tenant/webhooks/";
      path: "/webhooks";
      fullPath: "/webhooks/";
      preLoaderRoute: typeof AuthedTenantWebhooksIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/users/": {
      id: "/_authed/_tenant/users/";
      path: "/users";
      fullPath: "/users/";
      preLoaderRoute: typeof AuthedTenantUsersIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/threads/": {
      id: "/_authed/_tenant/threads/";
      path: "/threads";
      fullPath: "/threads/";
      preLoaderRoute: typeof AuthedTenantThreadsIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/spaces/": {
      id: "/_authed/_tenant/spaces/";
      path: "/spaces";
      fullPath: "/spaces/";
      preLoaderRoute: typeof AuthedTenantSpacesIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/slack/": {
      id: "/_authed/_tenant/slack/";
      path: "/slack";
      fullPath: "/slack/";
      preLoaderRoute: typeof AuthedTenantSlackIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/security/": {
      id: "/_authed/_tenant/security/";
      path: "/security";
      fullPath: "/security/";
      preLoaderRoute: typeof AuthedTenantSecurityIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/scheduled-jobs/": {
      id: "/_authed/_tenant/scheduled-jobs/";
      path: "/scheduled-jobs";
      fullPath: "/scheduled-jobs/";
      preLoaderRoute: typeof AuthedTenantScheduledJobsIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/routines/": {
      id: "/_authed/_tenant/routines/";
      path: "/routines";
      fullPath: "/routines/";
      preLoaderRoute: typeof AuthedTenantRoutinesIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/memory/": {
      id: "/_authed/_tenant/memory/";
      path: "/memory";
      fullPath: "/memory/";
      preLoaderRoute: typeof AuthedTenantMemoryIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/knowledge/": {
      id: "/_authed/_tenant/knowledge/";
      path: "/";
      fullPath: "/knowledge/";
      preLoaderRoute: typeof AuthedTenantKnowledgeIndexRouteImport;
      parentRoute: typeof AuthedTenantKnowledgeRoute;
    };
    "/_authed/_tenant/knowledge-bases/": {
      id: "/_authed/_tenant/knowledge-bases/";
      path: "/knowledge-bases";
      fullPath: "/knowledge-bases/";
      preLoaderRoute: typeof AuthedTenantKnowledgeBasesIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/inbox/": {
      id: "/_authed/_tenant/inbox/";
      path: "/inbox";
      fullPath: "/inbox/";
      preLoaderRoute: typeof AuthedTenantInboxIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/evaluations/": {
      id: "/_authed/_tenant/evaluations/";
      path: "/evaluations";
      fullPath: "/evaluations/";
      preLoaderRoute: typeof AuthedTenantEvaluationsIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/computers/": {
      id: "/_authed/_tenant/computers/";
      path: "/computers";
      fullPath: "/computers/";
      preLoaderRoute: typeof AuthedTenantComputersIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/compliance/": {
      id: "/_authed/_tenant/compliance/";
      path: "/";
      fullPath: "/compliance/";
      preLoaderRoute: typeof AuthedTenantComplianceIndexRouteImport;
      parentRoute: typeof AuthedTenantComplianceRouteRoute;
    };
    "/_authed/_tenant/capabilities/": {
      id: "/_authed/_tenant/capabilities/";
      path: "/";
      fullPath: "/capabilities/";
      preLoaderRoute: typeof AuthedTenantCapabilitiesIndexRouteImport;
      parentRoute: typeof AuthedTenantCapabilitiesRoute;
    };
    "/_authed/_tenant/automations/": {
      id: "/_authed/_tenant/automations/";
      path: "/automations";
      fullPath: "/automations/";
      preLoaderRoute: typeof AuthedTenantAutomationsIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/artifacts/": {
      id: "/_authed/_tenant/artifacts/";
      path: "/artifacts";
      fullPath: "/artifacts/";
      preLoaderRoute: typeof AuthedTenantArtifactsIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/applets/": {
      id: "/_authed/_tenant/applets/";
      path: "/applets";
      fullPath: "/applets/";
      preLoaderRoute: typeof AuthedTenantAppletsIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/analytics/": {
      id: "/_authed/_tenant/analytics/";
      path: "/";
      fullPath: "/analytics/";
      preLoaderRoute: typeof AuthedTenantAnalyticsIndexRouteImport;
      parentRoute: typeof AuthedTenantAnalyticsRoute;
    };
    "/_authed/_tenant/agent/": {
      id: "/_authed/_tenant/agent/";
      path: "/";
      fullPath: "/agent/";
      preLoaderRoute: typeof AuthedTenantAgentIndexRouteImport;
      parentRoute: typeof AuthedTenantAgentRoute;
    };
    "/_authed/_tenant/webhooks/$webhookId": {
      id: "/_authed/_tenant/webhooks/$webhookId";
      path: "/webhooks/$webhookId";
      fullPath: "/webhooks/$webhookId";
      preLoaderRoute: typeof AuthedTenantWebhooksWebhookIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/users/$userId": {
      id: "/_authed/_tenant/users/$userId";
      path: "/users/$userId";
      fullPath: "/users/$userId";
      preLoaderRoute: typeof AuthedTenantUsersUserIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/threads/$threadId": {
      id: "/_authed/_tenant/threads/$threadId";
      path: "/threads/$threadId";
      fullPath: "/threads/$threadId";
      preLoaderRoute: typeof AuthedTenantThreadsThreadIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/spaces/$spaceId": {
      id: "/_authed/_tenant/spaces/$spaceId";
      path: "/spaces/$spaceId";
      fullPath: "/spaces/$spaceId";
      preLoaderRoute: typeof AuthedTenantSpacesSpaceIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/scheduled-jobs/$scheduledJobId": {
      id: "/_authed/_tenant/scheduled-jobs/$scheduledJobId";
      path: "/scheduled-jobs/$scheduledJobId";
      fullPath: "/scheduled-jobs/$scheduledJobId";
      preLoaderRoute: typeof AuthedTenantScheduledJobsScheduledJobIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/routines/$routineId": {
      id: "/_authed/_tenant/routines/$routineId";
      path: "/routines/$routineId";
      fullPath: "/routines/$routineId";
      preLoaderRoute: typeof AuthedTenantRoutinesRoutineIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/knowledge/wiki": {
      id: "/_authed/_tenant/knowledge/wiki";
      path: "/wiki";
      fullPath: "/knowledge/wiki";
      preLoaderRoute: typeof AuthedTenantKnowledgeWikiRouteImport;
      parentRoute: typeof AuthedTenantKnowledgeRoute;
    };
    "/_authed/_tenant/knowledge/user": {
      id: "/_authed/_tenant/knowledge/user";
      path: "/user";
      fullPath: "/knowledge/user";
      preLoaderRoute: typeof AuthedTenantKnowledgeUserRouteImport;
      parentRoute: typeof AuthedTenantKnowledgeRoute;
    };
    "/_authed/_tenant/knowledge/memory": {
      id: "/_authed/_tenant/knowledge/memory";
      path: "/memory";
      fullPath: "/knowledge/memory";
      preLoaderRoute: typeof AuthedTenantKnowledgeMemoryRouteImport;
      parentRoute: typeof AuthedTenantKnowledgeRoute;
    };
    "/_authed/_tenant/knowledge/knowledge-bases": {
      id: "/_authed/_tenant/knowledge/knowledge-bases";
      path: "/knowledge-bases";
      fullPath: "/knowledge/knowledge-bases";
      preLoaderRoute: typeof AuthedTenantKnowledgeKnowledgeBasesRouteImport;
      parentRoute: typeof AuthedTenantKnowledgeRoute;
    };
    "/_authed/_tenant/knowledge/context-engine": {
      id: "/_authed/_tenant/knowledge/context-engine";
      path: "/context-engine";
      fullPath: "/knowledge/context-engine";
      preLoaderRoute: typeof AuthedTenantKnowledgeContextEngineRouteImport;
      parentRoute: typeof AuthedTenantKnowledgeRoute;
    };
    "/_authed/_tenant/knowledge-bases/$kbId": {
      id: "/_authed/_tenant/knowledge-bases/$kbId";
      path: "/knowledge-bases/$kbId";
      fullPath: "/knowledge-bases/$kbId";
      preLoaderRoute: typeof AuthedTenantKnowledgeBasesKbIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/inbox/$inboxItemId": {
      id: "/_authed/_tenant/inbox/$inboxItemId";
      path: "/inbox/$inboxItemId";
      fullPath: "/inbox/$inboxItemId";
      preLoaderRoute: typeof AuthedTenantInboxInboxItemIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/extensions/$extensionId": {
      id: "/_authed/_tenant/extensions/$extensionId";
      path: "/extensions/$extensionId";
      fullPath: "/extensions/$extensionId";
      preLoaderRoute: typeof AuthedTenantExtensionsExtensionIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/evaluations/$runId": {
      id: "/_authed/_tenant/evaluations/$runId";
      path: "/evaluations/$runId";
      fullPath: "/evaluations/$runId";
      preLoaderRoute: typeof AuthedTenantEvaluationsRunIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/computers/$computerId": {
      id: "/_authed/_tenant/computers/$computerId";
      path: "/computers/$computerId";
      fullPath: "/computers/$computerId";
      preLoaderRoute: typeof AuthedTenantComputersComputerIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/capabilities/mcp-servers": {
      id: "/_authed/_tenant/capabilities/mcp-servers";
      path: "/mcp-servers";
      fullPath: "/capabilities/mcp-servers";
      preLoaderRoute: typeof AuthedTenantCapabilitiesMcpServersRouteImport;
      parentRoute: typeof AuthedTenantCapabilitiesRoute;
    };
    "/_authed/_tenant/capabilities/builtin-tools": {
      id: "/_authed/_tenant/capabilities/builtin-tools";
      path: "/builtin-tools";
      fullPath: "/capabilities/builtin-tools";
      preLoaderRoute: typeof AuthedTenantCapabilitiesBuiltinToolsRouteImport;
      parentRoute: typeof AuthedTenantCapabilitiesRoute;
    };
    "/_authed/_tenant/applets/$appId": {
      id: "/_authed/_tenant/applets/$appId";
      path: "/applets/$appId";
      fullPath: "/applets/$appId";
      preLoaderRoute: typeof AuthedTenantAppletsAppIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/analytics/performance": {
      id: "/_authed/_tenant/analytics/performance";
      path: "/performance";
      fullPath: "/analytics/performance";
      preLoaderRoute: typeof AuthedTenantAnalyticsPerformanceRouteImport;
      parentRoute: typeof AuthedTenantAnalyticsRoute;
    };
    "/_authed/_tenant/analytics/cost": {
      id: "/_authed/_tenant/analytics/cost";
      path: "/cost";
      fullPath: "/analytics/cost";
      preLoaderRoute: typeof AuthedTenantAnalyticsCostRouteImport;
      parentRoute: typeof AuthedTenantAnalyticsRoute;
    };
    "/_authed/_tenant/analytics/activity": {
      id: "/_authed/_tenant/analytics/activity";
      path: "/activity";
      fullPath: "/analytics/activity";
      preLoaderRoute: typeof AuthedTenantAnalyticsActivityRouteImport;
      parentRoute: typeof AuthedTenantAnalyticsRoute;
    };
    "/_authed/_tenant/agent/files": {
      id: "/_authed/_tenant/agent/files";
      path: "/files";
      fullPath: "/agent/files";
      preLoaderRoute: typeof AuthedTenantAgentFilesRouteImport;
      parentRoute: typeof AuthedTenantAgentRoute;
    };
    "/_authed/_tenant/agent/config": {
      id: "/_authed/_tenant/agent/config";
      path: "/config";
      fullPath: "/agent/config";
      preLoaderRoute: typeof AuthedTenantAgentConfigRouteImport;
      parentRoute: typeof AuthedTenantAgentRoute;
    };
    "/_authed/_tenant/evaluations/studio/": {
      id: "/_authed/_tenant/evaluations/studio/";
      path: "/evaluations/studio";
      fullPath: "/evaluations/studio/";
      preLoaderRoute: typeof AuthedTenantEvaluationsStudioIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/compliance/exports/": {
      id: "/_authed/_tenant/compliance/exports/";
      path: "/exports";
      fullPath: "/compliance/exports/";
      preLoaderRoute: typeof AuthedTenantComplianceExportsIndexRouteImport;
      parentRoute: typeof AuthedTenantComplianceRouteRoute;
    };
    "/_authed/_tenant/capabilities/skills/": {
      id: "/_authed/_tenant/capabilities/skills/";
      path: "/skills";
      fullPath: "/capabilities/skills/";
      preLoaderRoute: typeof AuthedTenantCapabilitiesSkillsIndexRouteImport;
      parentRoute: typeof AuthedTenantCapabilitiesRoute;
    };
    "/_authed/_tenant/capabilities/plugins/": {
      id: "/_authed/_tenant/capabilities/plugins/";
      path: "/plugins";
      fullPath: "/capabilities/plugins/";
      preLoaderRoute: typeof AuthedTenantCapabilitiesPluginsIndexRouteImport;
      parentRoute: typeof AuthedTenantCapabilitiesRoute;
    };
    "/_authed/_tenant/automations/webhooks/": {
      id: "/_authed/_tenant/automations/webhooks/";
      path: "/automations/webhooks";
      fullPath: "/automations/webhooks/";
      preLoaderRoute: typeof AuthedTenantAutomationsWebhooksIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/automations/schedules/": {
      id: "/_authed/_tenant/automations/schedules/";
      path: "/automations/schedules";
      fullPath: "/automations/schedules/";
      preLoaderRoute: typeof AuthedTenantAutomationsSchedulesIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/automations/routines/": {
      id: "/_authed/_tenant/automations/routines/";
      path: "/automations/routines";
      fullPath: "/automations/routines/";
      preLoaderRoute: typeof AuthedTenantAutomationsRoutinesIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/automations/credentials/": {
      id: "/_authed/_tenant/automations/credentials/";
      path: "/automations/credentials";
      fullPath: "/automations/credentials/";
      preLoaderRoute: typeof AuthedTenantAutomationsCredentialsIndexRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/spaces/$spaceId_/workspace": {
      id: "/_authed/_tenant/spaces/$spaceId_/workspace";
      path: "/spaces/$spaceId/workspace";
      fullPath: "/spaces/$spaceId/workspace";
      preLoaderRoute: typeof AuthedTenantSpacesSpaceIdWorkspaceRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/spaces/$spaceId_/memory": {
      id: "/_authed/_tenant/spaces/$spaceId_/memory";
      path: "/spaces/$spaceId/memory";
      fullPath: "/spaces/$spaceId/memory";
      preLoaderRoute: typeof AuthedTenantSpacesSpaceIdMemoryRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/spaces/$spaceId_/configuration": {
      id: "/_authed/_tenant/spaces/$spaceId_/configuration";
      path: "/spaces/$spaceId/configuration";
      fullPath: "/spaces/$spaceId/configuration";
      preLoaderRoute: typeof AuthedTenantSpacesSpaceIdConfigurationRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/spaces/$spaceId_/automations": {
      id: "/_authed/_tenant/spaces/$spaceId_/automations";
      path: "/spaces/$spaceId/automations";
      fullPath: "/spaces/$spaceId/automations";
      preLoaderRoute: typeof AuthedTenantSpacesSpaceIdAutomationsRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/knowledge/knowledge-bases/$kbId": {
      id: "/_authed/_tenant/knowledge/knowledge-bases/$kbId";
      path: "/$kbId";
      fullPath: "/knowledge/knowledge-bases/$kbId";
      preLoaderRoute: typeof AuthedTenantKnowledgeKnowledgeBasesKbIdRouteImport;
      parentRoute: typeof AuthedTenantKnowledgeKnowledgeBasesRoute;
    };
    "/_authed/_tenant/evaluations/studio/new": {
      id: "/_authed/_tenant/evaluations/studio/new";
      path: "/evaluations/studio/new";
      fullPath: "/evaluations/studio/new";
      preLoaderRoute: typeof AuthedTenantEvaluationsStudioNewRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/evaluations/studio/$testCaseId": {
      id: "/_authed/_tenant/evaluations/studio/$testCaseId";
      path: "/evaluations/studio/$testCaseId";
      fullPath: "/evaluations/studio/$testCaseId";
      preLoaderRoute: typeof AuthedTenantEvaluationsStudioTestCaseIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/compliance/events/$eventId": {
      id: "/_authed/_tenant/compliance/events/$eventId";
      path: "/events/$eventId";
      fullPath: "/compliance/events/$eventId";
      preLoaderRoute: typeof AuthedTenantComplianceEventsEventIdRouteImport;
      parentRoute: typeof AuthedTenantComplianceRouteRoute;
    };
    "/_authed/_tenant/capabilities/skills/builder": {
      id: "/_authed/_tenant/capabilities/skills/builder";
      path: "/skills/builder";
      fullPath: "/capabilities/skills/builder";
      preLoaderRoute: typeof AuthedTenantCapabilitiesSkillsBuilderRouteImport;
      parentRoute: typeof AuthedTenantCapabilitiesRoute;
    };
    "/_authed/_tenant/capabilities/skills/$slug": {
      id: "/_authed/_tenant/capabilities/skills/$slug";
      path: "/skills/$slug";
      fullPath: "/capabilities/skills/$slug";
      preLoaderRoute: typeof AuthedTenantCapabilitiesSkillsSlugRouteImport;
      parentRoute: typeof AuthedTenantCapabilitiesRoute;
    };
    "/_authed/_tenant/capabilities/plugins/$uploadId": {
      id: "/_authed/_tenant/capabilities/plugins/$uploadId";
      path: "/plugins/$uploadId";
      fullPath: "/capabilities/plugins/$uploadId";
      preLoaderRoute: typeof AuthedTenantCapabilitiesPluginsUploadIdRouteImport;
      parentRoute: typeof AuthedTenantCapabilitiesRoute;
    };
    "/_authed/_tenant/automations/webhooks/$webhookId": {
      id: "/_authed/_tenant/automations/webhooks/$webhookId";
      path: "/automations/webhooks/$webhookId";
      fullPath: "/automations/webhooks/$webhookId";
      preLoaderRoute: typeof AuthedTenantAutomationsWebhooksWebhookIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/automations/schedules/$scheduledJobId": {
      id: "/_authed/_tenant/automations/schedules/$scheduledJobId";
      path: "/automations/schedules/$scheduledJobId";
      fullPath: "/automations/schedules/$scheduledJobId";
      preLoaderRoute: typeof AuthedTenantAutomationsSchedulesScheduledJobIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/automations/routines/new": {
      id: "/_authed/_tenant/automations/routines/new";
      path: "/automations/routines/new";
      fullPath: "/automations/routines/new";
      preLoaderRoute: typeof AuthedTenantAutomationsRoutinesNewRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/automations/routines/$routineId": {
      id: "/_authed/_tenant/automations/routines/$routineId";
      path: "/automations/routines/$routineId";
      fullPath: "/automations/routines/$routineId";
      preLoaderRoute: typeof AuthedTenantAutomationsRoutinesRoutineIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/automations/credentials/$credentialId": {
      id: "/_authed/_tenant/automations/credentials/$credentialId";
      path: "/automations/credentials/$credentialId";
      fullPath: "/automations/credentials/$credentialId";
      preLoaderRoute: typeof AuthedTenantAutomationsCredentialsCredentialIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/evaluations/studio/edit/$testCaseId": {
      id: "/_authed/_tenant/evaluations/studio/edit/$testCaseId";
      path: "/evaluations/studio/edit/$testCaseId";
      fullPath: "/evaluations/studio/edit/$testCaseId";
      preLoaderRoute: typeof AuthedTenantEvaluationsStudioEditTestCaseIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
    "/_authed/_tenant/automations/routines/$routineId_/executions/$executionId": {
      id: "/_authed/_tenant/automations/routines/$routineId_/executions/$executionId";
      path: "/automations/routines/$routineId/executions/$executionId";
      fullPath: "/automations/routines/$routineId/executions/$executionId";
      preLoaderRoute: typeof AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRouteImport;
      parentRoute: typeof AuthedTenantRoute;
    };
  }
}

interface AuthedTenantComplianceRouteRouteChildren {
  AuthedTenantComplianceIndexRoute: typeof AuthedTenantComplianceIndexRoute;
  AuthedTenantComplianceEventsEventIdRoute: typeof AuthedTenantComplianceEventsEventIdRoute;
  AuthedTenantComplianceExportsIndexRoute: typeof AuthedTenantComplianceExportsIndexRoute;
}

const AuthedTenantComplianceRouteRouteChildren: AuthedTenantComplianceRouteRouteChildren =
  {
    AuthedTenantComplianceIndexRoute: AuthedTenantComplianceIndexRoute,
    AuthedTenantComplianceEventsEventIdRoute:
      AuthedTenantComplianceEventsEventIdRoute,
    AuthedTenantComplianceExportsIndexRoute:
      AuthedTenantComplianceExportsIndexRoute,
  };

const AuthedTenantComplianceRouteRouteWithChildren =
  AuthedTenantComplianceRouteRoute._addFileChildren(
    AuthedTenantComplianceRouteRouteChildren,
  );

interface AuthedTenantAgentRouteChildren {
  AuthedTenantAgentConfigRoute: typeof AuthedTenantAgentConfigRoute;
  AuthedTenantAgentFilesRoute: typeof AuthedTenantAgentFilesRoute;
  AuthedTenantAgentIndexRoute: typeof AuthedTenantAgentIndexRoute;
}

const AuthedTenantAgentRouteChildren: AuthedTenantAgentRouteChildren = {
  AuthedTenantAgentConfigRoute: AuthedTenantAgentConfigRoute,
  AuthedTenantAgentFilesRoute: AuthedTenantAgentFilesRoute,
  AuthedTenantAgentIndexRoute: AuthedTenantAgentIndexRoute,
};

const AuthedTenantAgentRouteWithChildren =
  AuthedTenantAgentRoute._addFileChildren(AuthedTenantAgentRouteChildren);

interface AuthedTenantAnalyticsRouteChildren {
  AuthedTenantAnalyticsActivityRoute: typeof AuthedTenantAnalyticsActivityRoute;
  AuthedTenantAnalyticsCostRoute: typeof AuthedTenantAnalyticsCostRoute;
  AuthedTenantAnalyticsPerformanceRoute: typeof AuthedTenantAnalyticsPerformanceRoute;
  AuthedTenantAnalyticsIndexRoute: typeof AuthedTenantAnalyticsIndexRoute;
}

const AuthedTenantAnalyticsRouteChildren: AuthedTenantAnalyticsRouteChildren = {
  AuthedTenantAnalyticsActivityRoute: AuthedTenantAnalyticsActivityRoute,
  AuthedTenantAnalyticsCostRoute: AuthedTenantAnalyticsCostRoute,
  AuthedTenantAnalyticsPerformanceRoute: AuthedTenantAnalyticsPerformanceRoute,
  AuthedTenantAnalyticsIndexRoute: AuthedTenantAnalyticsIndexRoute,
};

const AuthedTenantAnalyticsRouteWithChildren =
  AuthedTenantAnalyticsRoute._addFileChildren(
    AuthedTenantAnalyticsRouteChildren,
  );

interface AuthedTenantCapabilitiesRouteChildren {
  AuthedTenantCapabilitiesBuiltinToolsRoute: typeof AuthedTenantCapabilitiesBuiltinToolsRoute;
  AuthedTenantCapabilitiesMcpServersRoute: typeof AuthedTenantCapabilitiesMcpServersRoute;
  AuthedTenantCapabilitiesIndexRoute: typeof AuthedTenantCapabilitiesIndexRoute;
  AuthedTenantCapabilitiesPluginsUploadIdRoute: typeof AuthedTenantCapabilitiesPluginsUploadIdRoute;
  AuthedTenantCapabilitiesSkillsSlugRoute: typeof AuthedTenantCapabilitiesSkillsSlugRoute;
  AuthedTenantCapabilitiesSkillsBuilderRoute: typeof AuthedTenantCapabilitiesSkillsBuilderRoute;
  AuthedTenantCapabilitiesPluginsIndexRoute: typeof AuthedTenantCapabilitiesPluginsIndexRoute;
  AuthedTenantCapabilitiesSkillsIndexRoute: typeof AuthedTenantCapabilitiesSkillsIndexRoute;
}

const AuthedTenantCapabilitiesRouteChildren: AuthedTenantCapabilitiesRouteChildren =
  {
    AuthedTenantCapabilitiesBuiltinToolsRoute:
      AuthedTenantCapabilitiesBuiltinToolsRoute,
    AuthedTenantCapabilitiesMcpServersRoute:
      AuthedTenantCapabilitiesMcpServersRoute,
    AuthedTenantCapabilitiesIndexRoute: AuthedTenantCapabilitiesIndexRoute,
    AuthedTenantCapabilitiesPluginsUploadIdRoute:
      AuthedTenantCapabilitiesPluginsUploadIdRoute,
    AuthedTenantCapabilitiesSkillsSlugRoute:
      AuthedTenantCapabilitiesSkillsSlugRoute,
    AuthedTenantCapabilitiesSkillsBuilderRoute:
      AuthedTenantCapabilitiesSkillsBuilderRoute,
    AuthedTenantCapabilitiesPluginsIndexRoute:
      AuthedTenantCapabilitiesPluginsIndexRoute,
    AuthedTenantCapabilitiesSkillsIndexRoute:
      AuthedTenantCapabilitiesSkillsIndexRoute,
  };

const AuthedTenantCapabilitiesRouteWithChildren =
  AuthedTenantCapabilitiesRoute._addFileChildren(
    AuthedTenantCapabilitiesRouteChildren,
  );

interface AuthedTenantKnowledgeKnowledgeBasesRouteChildren {
  AuthedTenantKnowledgeKnowledgeBasesKbIdRoute: typeof AuthedTenantKnowledgeKnowledgeBasesKbIdRoute;
}

const AuthedTenantKnowledgeKnowledgeBasesRouteChildren: AuthedTenantKnowledgeKnowledgeBasesRouteChildren =
  {
    AuthedTenantKnowledgeKnowledgeBasesKbIdRoute:
      AuthedTenantKnowledgeKnowledgeBasesKbIdRoute,
  };

const AuthedTenantKnowledgeKnowledgeBasesRouteWithChildren =
  AuthedTenantKnowledgeKnowledgeBasesRoute._addFileChildren(
    AuthedTenantKnowledgeKnowledgeBasesRouteChildren,
  );

interface AuthedTenantKnowledgeRouteChildren {
  AuthedTenantKnowledgeContextEngineRoute: typeof AuthedTenantKnowledgeContextEngineRoute;
  AuthedTenantKnowledgeKnowledgeBasesRoute: typeof AuthedTenantKnowledgeKnowledgeBasesRouteWithChildren;
  AuthedTenantKnowledgeMemoryRoute: typeof AuthedTenantKnowledgeMemoryRoute;
  AuthedTenantKnowledgeUserRoute: typeof AuthedTenantKnowledgeUserRoute;
  AuthedTenantKnowledgeWikiRoute: typeof AuthedTenantKnowledgeWikiRoute;
  AuthedTenantKnowledgeIndexRoute: typeof AuthedTenantKnowledgeIndexRoute;
}

const AuthedTenantKnowledgeRouteChildren: AuthedTenantKnowledgeRouteChildren = {
  AuthedTenantKnowledgeContextEngineRoute:
    AuthedTenantKnowledgeContextEngineRoute,
  AuthedTenantKnowledgeKnowledgeBasesRoute:
    AuthedTenantKnowledgeKnowledgeBasesRouteWithChildren,
  AuthedTenantKnowledgeMemoryRoute: AuthedTenantKnowledgeMemoryRoute,
  AuthedTenantKnowledgeUserRoute: AuthedTenantKnowledgeUserRoute,
  AuthedTenantKnowledgeWikiRoute: AuthedTenantKnowledgeWikiRoute,
  AuthedTenantKnowledgeIndexRoute: AuthedTenantKnowledgeIndexRoute,
};

const AuthedTenantKnowledgeRouteWithChildren =
  AuthedTenantKnowledgeRoute._addFileChildren(
    AuthedTenantKnowledgeRouteChildren,
  );

interface AuthedTenantRouteChildren {
  AuthedTenantComplianceRouteRoute: typeof AuthedTenantComplianceRouteRouteWithChildren;
  AuthedTenantAgentRoute: typeof AuthedTenantAgentRouteWithChildren;
  AuthedTenantAnalyticsRoute: typeof AuthedTenantAnalyticsRouteWithChildren;
  AuthedTenantBillingRoute: typeof AuthedTenantBillingRoute;
  AuthedTenantCapabilitiesRoute: typeof AuthedTenantCapabilitiesRouteWithChildren;
  AuthedTenantDashboardRoute: typeof AuthedTenantDashboardRoute;
  AuthedTenantKnowledgeRoute: typeof AuthedTenantKnowledgeRouteWithChildren;
  AuthedTenantOntologyRoute: typeof AuthedTenantOntologyRoute;
  AuthedTenantOrgRoute: typeof AuthedTenantOrgRoute;
  AuthedTenantSettingsRoute: typeof AuthedTenantSettingsRoute;
  AuthedTenantAppletsAppIdRoute: typeof AuthedTenantAppletsAppIdRoute;
  AuthedTenantComputersComputerIdRoute: typeof AuthedTenantComputersComputerIdRoute;
  AuthedTenantEvaluationsRunIdRoute: typeof AuthedTenantEvaluationsRunIdRoute;
  AuthedTenantExtensionsExtensionIdRoute: typeof AuthedTenantExtensionsExtensionIdRoute;
  AuthedTenantInboxInboxItemIdRoute: typeof AuthedTenantInboxInboxItemIdRoute;
  AuthedTenantKnowledgeBasesKbIdRoute: typeof AuthedTenantKnowledgeBasesKbIdRoute;
  AuthedTenantRoutinesRoutineIdRoute: typeof AuthedTenantRoutinesRoutineIdRoute;
  AuthedTenantScheduledJobsScheduledJobIdRoute: typeof AuthedTenantScheduledJobsScheduledJobIdRoute;
  AuthedTenantSpacesSpaceIdRoute: typeof AuthedTenantSpacesSpaceIdRoute;
  AuthedTenantThreadsThreadIdRoute: typeof AuthedTenantThreadsThreadIdRoute;
  AuthedTenantUsersUserIdRoute: typeof AuthedTenantUsersUserIdRoute;
  AuthedTenantWebhooksWebhookIdRoute: typeof AuthedTenantWebhooksWebhookIdRoute;
  AuthedTenantAppletsIndexRoute: typeof AuthedTenantAppletsIndexRoute;
  AuthedTenantArtifactsIndexRoute: typeof AuthedTenantArtifactsIndexRoute;
  AuthedTenantAutomationsIndexRoute: typeof AuthedTenantAutomationsIndexRoute;
  AuthedTenantComputersIndexRoute: typeof AuthedTenantComputersIndexRoute;
  AuthedTenantEvaluationsIndexRoute: typeof AuthedTenantEvaluationsIndexRoute;
  AuthedTenantInboxIndexRoute: typeof AuthedTenantInboxIndexRoute;
  AuthedTenantKnowledgeBasesIndexRoute: typeof AuthedTenantKnowledgeBasesIndexRoute;
  AuthedTenantMemoryIndexRoute: typeof AuthedTenantMemoryIndexRoute;
  AuthedTenantRoutinesIndexRoute: typeof AuthedTenantRoutinesIndexRoute;
  AuthedTenantScheduledJobsIndexRoute: typeof AuthedTenantScheduledJobsIndexRoute;
  AuthedTenantSecurityIndexRoute: typeof AuthedTenantSecurityIndexRoute;
  AuthedTenantSlackIndexRoute: typeof AuthedTenantSlackIndexRoute;
  AuthedTenantSpacesIndexRoute: typeof AuthedTenantSpacesIndexRoute;
  AuthedTenantThreadsIndexRoute: typeof AuthedTenantThreadsIndexRoute;
  AuthedTenantUsersIndexRoute: typeof AuthedTenantUsersIndexRoute;
  AuthedTenantWebhooksIndexRoute: typeof AuthedTenantWebhooksIndexRoute;
  AuthedTenantWikiIndexRoute: typeof AuthedTenantWikiIndexRoute;
  AuthedTenantWorkspaceReviewsIndexRoute: typeof AuthedTenantWorkspaceReviewsIndexRoute;
  AuthedTenantAutomationsCredentialsCredentialIdRoute: typeof AuthedTenantAutomationsCredentialsCredentialIdRoute;
  AuthedTenantAutomationsRoutinesRoutineIdRoute: typeof AuthedTenantAutomationsRoutinesRoutineIdRoute;
  AuthedTenantAutomationsRoutinesNewRoute: typeof AuthedTenantAutomationsRoutinesNewRoute;
  AuthedTenantAutomationsSchedulesScheduledJobIdRoute: typeof AuthedTenantAutomationsSchedulesScheduledJobIdRoute;
  AuthedTenantAutomationsWebhooksWebhookIdRoute: typeof AuthedTenantAutomationsWebhooksWebhookIdRoute;
  AuthedTenantEvaluationsStudioTestCaseIdRoute: typeof AuthedTenantEvaluationsStudioTestCaseIdRoute;
  AuthedTenantEvaluationsStudioNewRoute: typeof AuthedTenantEvaluationsStudioNewRoute;
  AuthedTenantSpacesSpaceIdAutomationsRoute: typeof AuthedTenantSpacesSpaceIdAutomationsRoute;
  AuthedTenantSpacesSpaceIdConfigurationRoute: typeof AuthedTenantSpacesSpaceIdConfigurationRoute;
  AuthedTenantSpacesSpaceIdMemoryRoute: typeof AuthedTenantSpacesSpaceIdMemoryRoute;
  AuthedTenantSpacesSpaceIdWorkspaceRoute: typeof AuthedTenantSpacesSpaceIdWorkspaceRoute;
  AuthedTenantAutomationsCredentialsIndexRoute: typeof AuthedTenantAutomationsCredentialsIndexRoute;
  AuthedTenantAutomationsRoutinesIndexRoute: typeof AuthedTenantAutomationsRoutinesIndexRoute;
  AuthedTenantAutomationsSchedulesIndexRoute: typeof AuthedTenantAutomationsSchedulesIndexRoute;
  AuthedTenantAutomationsWebhooksIndexRoute: typeof AuthedTenantAutomationsWebhooksIndexRoute;
  AuthedTenantEvaluationsStudioIndexRoute: typeof AuthedTenantEvaluationsStudioIndexRoute;
  AuthedTenantEvaluationsStudioEditTestCaseIdRoute: typeof AuthedTenantEvaluationsStudioEditTestCaseIdRoute;
  AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRoute: typeof AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRoute;
}

const AuthedTenantRouteChildren: AuthedTenantRouteChildren = {
  AuthedTenantComplianceRouteRoute:
    AuthedTenantComplianceRouteRouteWithChildren,
  AuthedTenantAgentRoute: AuthedTenantAgentRouteWithChildren,
  AuthedTenantAnalyticsRoute: AuthedTenantAnalyticsRouteWithChildren,
  AuthedTenantBillingRoute: AuthedTenantBillingRoute,
  AuthedTenantCapabilitiesRoute: AuthedTenantCapabilitiesRouteWithChildren,
  AuthedTenantDashboardRoute: AuthedTenantDashboardRoute,
  AuthedTenantKnowledgeRoute: AuthedTenantKnowledgeRouteWithChildren,
  AuthedTenantOntologyRoute: AuthedTenantOntologyRoute,
  AuthedTenantOrgRoute: AuthedTenantOrgRoute,
  AuthedTenantSettingsRoute: AuthedTenantSettingsRoute,
  AuthedTenantAppletsAppIdRoute: AuthedTenantAppletsAppIdRoute,
  AuthedTenantComputersComputerIdRoute: AuthedTenantComputersComputerIdRoute,
  AuthedTenantEvaluationsRunIdRoute: AuthedTenantEvaluationsRunIdRoute,
  AuthedTenantExtensionsExtensionIdRoute:
    AuthedTenantExtensionsExtensionIdRoute,
  AuthedTenantInboxInboxItemIdRoute: AuthedTenantInboxInboxItemIdRoute,
  AuthedTenantKnowledgeBasesKbIdRoute: AuthedTenantKnowledgeBasesKbIdRoute,
  AuthedTenantRoutinesRoutineIdRoute: AuthedTenantRoutinesRoutineIdRoute,
  AuthedTenantScheduledJobsScheduledJobIdRoute:
    AuthedTenantScheduledJobsScheduledJobIdRoute,
  AuthedTenantSpacesSpaceIdRoute: AuthedTenantSpacesSpaceIdRoute,
  AuthedTenantThreadsThreadIdRoute: AuthedTenantThreadsThreadIdRoute,
  AuthedTenantUsersUserIdRoute: AuthedTenantUsersUserIdRoute,
  AuthedTenantWebhooksWebhookIdRoute: AuthedTenantWebhooksWebhookIdRoute,
  AuthedTenantAppletsIndexRoute: AuthedTenantAppletsIndexRoute,
  AuthedTenantArtifactsIndexRoute: AuthedTenantArtifactsIndexRoute,
  AuthedTenantAutomationsIndexRoute: AuthedTenantAutomationsIndexRoute,
  AuthedTenantComputersIndexRoute: AuthedTenantComputersIndexRoute,
  AuthedTenantEvaluationsIndexRoute: AuthedTenantEvaluationsIndexRoute,
  AuthedTenantInboxIndexRoute: AuthedTenantInboxIndexRoute,
  AuthedTenantKnowledgeBasesIndexRoute: AuthedTenantKnowledgeBasesIndexRoute,
  AuthedTenantMemoryIndexRoute: AuthedTenantMemoryIndexRoute,
  AuthedTenantRoutinesIndexRoute: AuthedTenantRoutinesIndexRoute,
  AuthedTenantScheduledJobsIndexRoute: AuthedTenantScheduledJobsIndexRoute,
  AuthedTenantSecurityIndexRoute: AuthedTenantSecurityIndexRoute,
  AuthedTenantSlackIndexRoute: AuthedTenantSlackIndexRoute,
  AuthedTenantSpacesIndexRoute: AuthedTenantSpacesIndexRoute,
  AuthedTenantThreadsIndexRoute: AuthedTenantThreadsIndexRoute,
  AuthedTenantUsersIndexRoute: AuthedTenantUsersIndexRoute,
  AuthedTenantWebhooksIndexRoute: AuthedTenantWebhooksIndexRoute,
  AuthedTenantWikiIndexRoute: AuthedTenantWikiIndexRoute,
  AuthedTenantWorkspaceReviewsIndexRoute:
    AuthedTenantWorkspaceReviewsIndexRoute,
  AuthedTenantAutomationsCredentialsCredentialIdRoute:
    AuthedTenantAutomationsCredentialsCredentialIdRoute,
  AuthedTenantAutomationsRoutinesRoutineIdRoute:
    AuthedTenantAutomationsRoutinesRoutineIdRoute,
  AuthedTenantAutomationsRoutinesNewRoute:
    AuthedTenantAutomationsRoutinesNewRoute,
  AuthedTenantAutomationsSchedulesScheduledJobIdRoute:
    AuthedTenantAutomationsSchedulesScheduledJobIdRoute,
  AuthedTenantAutomationsWebhooksWebhookIdRoute:
    AuthedTenantAutomationsWebhooksWebhookIdRoute,
  AuthedTenantEvaluationsStudioTestCaseIdRoute:
    AuthedTenantEvaluationsStudioTestCaseIdRoute,
  AuthedTenantEvaluationsStudioNewRoute: AuthedTenantEvaluationsStudioNewRoute,
  AuthedTenantSpacesSpaceIdAutomationsRoute:
    AuthedTenantSpacesSpaceIdAutomationsRoute,
  AuthedTenantSpacesSpaceIdConfigurationRoute:
    AuthedTenantSpacesSpaceIdConfigurationRoute,
  AuthedTenantSpacesSpaceIdMemoryRoute: AuthedTenantSpacesSpaceIdMemoryRoute,
  AuthedTenantSpacesSpaceIdWorkspaceRoute:
    AuthedTenantSpacesSpaceIdWorkspaceRoute,
  AuthedTenantAutomationsCredentialsIndexRoute:
    AuthedTenantAutomationsCredentialsIndexRoute,
  AuthedTenantAutomationsRoutinesIndexRoute:
    AuthedTenantAutomationsRoutinesIndexRoute,
  AuthedTenantAutomationsSchedulesIndexRoute:
    AuthedTenantAutomationsSchedulesIndexRoute,
  AuthedTenantAutomationsWebhooksIndexRoute:
    AuthedTenantAutomationsWebhooksIndexRoute,
  AuthedTenantEvaluationsStudioIndexRoute:
    AuthedTenantEvaluationsStudioIndexRoute,
  AuthedTenantEvaluationsStudioEditTestCaseIdRoute:
    AuthedTenantEvaluationsStudioEditTestCaseIdRoute,
  AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRoute:
    AuthedTenantAutomationsRoutinesRoutineIdExecutionsExecutionIdRoute,
};

const AuthedTenantRouteWithChildren = AuthedTenantRoute._addFileChildren(
  AuthedTenantRouteChildren,
);

interface AuthedRouteChildren {
  AuthedTenantRoute: typeof AuthedTenantRouteWithChildren;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedTenantRoute: AuthedTenantRouteWithChildren,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SignInRoute: SignInRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
