#!/usr/bin/env tsx
/**
 * U8 — per-slug migration status for the bundled skill catalog.
 *
 * Complements U1's pre-migration census with a narrower question: "for
 * each catalog slug, what's the state of its U8 migration, and what's
 * the next step?"
 *
 * Migration states:
 *   - done              — execution is already `script` or `context`; no
 *                         composition_runner involvement.
 *   - composition       — still uses `execution: composition`. Candidate
 *                         for conversion to `context` (model drives via
 *                         Skill() meta-tool) or `script` (deterministic
 *                         entrypoint).
 *   - declarative       — uses the older `execution: declarative` shape.
 *                         Treat like composition for migration purposes.
 *   - smoke-probe       — composition slugs whose explicit purpose is to
 *                         exercise composition_runner end-to-end (e.g.,
 *                         `smoke-package-only`). MUST be migrated LAST,
 *                         alongside U6's composition_runner deletion.
 *   - unknown           — skill.yaml missing or malformed.
 *
 * Usage:
 *   tsx packages/skill-catalog/scripts/u8-status.ts
 *
 * Write to a file:
 *   tsx packages/skill-catalog/scripts/u8-status.ts > docs/plans/u8-status.md
 */

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { parse as parseYaml } from "yaml";

// Kept up to date as the skill-catalog grows — skills whose explicit
// purpose is to exercise composition_runner end-to-end. Retiring
// composition_runner (U6) retires these too.
const SMOKE_PROBES = new Set<string>(["smoke-package-only"]);

type MigrationState =
  | "done"
  | "composition"
  | "declarative"
  | "smoke-probe"
  | "unknown";

interface SlugStatus {
  slug: string;
  state: MigrationState;
  execution: string;
  mode: string;
  hasScriptsDir: boolean;
  hasSkillMd: boolean;
  stepCount: number;
  note?: string;
}

function catalogRoot(): string {
  const hereUrl = new URL(import.meta.url).pathname;
  // scripts/u8-status.ts → up two to packages/skill-catalog
  return resolve(hereUrl, "..", "..");
}

function listSlugDirs(catalog: string): string[] {
  return readdirSync(catalog, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((name) => !name.startsWith("_") && !name.startsWith("."))
    .filter((name) => name !== "node_modules" && name !== "dist")
    .filter((name) => name !== "scripts" && name !== "tests")
    .filter((name) => name !== "__tests__" && name !== "characterization")
    .sort();
}

function inspect(slug: string, catalog: string): SlugStatus {
  const dir = join(catalog, slug);
  const yamlPath = join(dir, "skill.yaml");
  const skillMdPath = join(dir, "SKILL.md");
  const scriptsDir = join(dir, "scripts");
  const hasScriptsDir =
    existsSync(scriptsDir) && statSync(scriptsDir).isDirectory();
  const hasSkillMd = existsSync(skillMdPath);

  if (!existsSync(yamlPath)) {
    return {
      slug,
      state: "unknown",
      execution: "",
      mode: "",
      hasScriptsDir,
      hasSkillMd,
      stepCount: 0,
      note: "no skill.yaml",
    };
  }

  let parsed: unknown;
  try {
    parsed = parseYaml(readFileSync(yamlPath, "utf8"));
  } catch (err) {
    return {
      slug,
      state: "unknown",
      execution: "",
      mode: "",
      hasScriptsDir,
      hasSkillMd,
      stepCount: 0,
      note: `parse failed: ${(err as Error).message}`,
    };
  }

  const y = (parsed ?? {}) as Record<string, unknown>;
  const execution = typeof y.execution === "string" ? y.execution : "";
  const mode = typeof y.mode === "string" ? y.mode : "";
  const steps = Array.isArray(y.steps) ? (y.steps as unknown[]) : [];

  let state: MigrationState;
  if (SMOKE_PROBES.has(slug) && execution === "composition") {
    state = "smoke-probe";
  } else if (execution === "composition") {
    state = "composition";
  } else if (execution === "declarative") {
    state = "declarative";
  } else if (execution === "script" || execution === "context") {
    state = "done";
  } else {
    state = "unknown";
  }

  return {
    slug,
    state,
    execution,
    mode,
    hasScriptsDir,
    hasSkillMd,
    stepCount: steps.length,
  };
}

function render(statuses: SlugStatus[]): string {
  const byState: Record<MigrationState, SlugStatus[]> = {
    done: [],
    composition: [],
    declarative: [],
    "smoke-probe": [],
    unknown: [],
  };
  for (const s of statuses) byState[s.state].push(s);

  const lines: string[] = [];
  lines.push("# U8 — Skill catalog migration status\n");
  lines.push(
    "Generated by `tsx packages/skill-catalog/scripts/u8-status.ts`.\n",
  );
  lines.push("## Summary\n");
  lines.push("| State | Count |");
  lines.push("| --- | ---: |");
  lines.push(`| done | ${byState.done.length} |`);
  lines.push(`| composition | ${byState.composition.length} |`);
  lines.push(`| declarative | ${byState.declarative.length} |`);
  lines.push(`| smoke-probe | ${byState["smoke-probe"].length} |`);
  lines.push(`| unknown | ${byState.unknown.length} |`);
  lines.push("");
  lines.push("## Per-slug detail\n");
  lines.push(
    "| Slug | State | execution | mode | scripts/ | SKILL.md | steps |",
  );
  lines.push("| --- | --- | --- | --- | ---: | ---: | ---: |");
  for (const s of statuses) {
    lines.push(
      `| ${s.slug} | ${s.state} | ${s.execution || "—"} | ${s.mode || "—"} | ${s.hasScriptsDir ? "yes" : "no"} | ${s.hasSkillMd ? "yes" : "no"} | ${s.stepCount} |`,
    );
  }
  lines.push("");
  lines.push("## Migration guidance\n");
  lines.push(
    "- **composition** slugs → convert to `execution: context` when the " +
      "SKILL.md body already documents the composition step-by-step " +
      "(model drives via the Skill meta-tool from U5). Drop `steps:`, " +
      "`delivery:`, and `budget_cap:` from skill.yaml; keep `inputs:` and " +
      "`triggers:`.",
  );
  lines.push(
    "- **declarative** slugs → same pattern as composition; the declarative " +
      "block is a legacy composition shape.",
  );
  lines.push(
    "- **smoke-probe** → migrate LAST, alongside U6's composition_runner " +
      "deletion. These exist specifically to exercise composition_runner.",
  );
  lines.push(
    "- **done** / **script-only** → no change needed for U8; rely on U7's " +
      "characterization harness for regression signal.",
  );
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const catalog = catalogRoot();
  const slugs = listSlugDirs(catalog);
  const statuses = slugs.map((slug) => inspect(slug, catalog));
  process.stdout.write(render(statuses));
}

main();
