import { describe, expect, it, vi } from "vitest";
import {
  computeSignedPayloadHash,
  fixSkillTrustEvidence,
  type SkillTrustSigner,
} from "./evidence-fixes.js";
import type { SkillTrustInputFile } from "./catalog-report.js";

const skillMd = `---
name: account-health-review
display_name: "Account Health Review"
description: Reviews account health signals and produces a health report.
license: Proprietary
metadata:
  author: thinkwork
allowed-tools:
  - crm_account_summary
---

# Account Health Review

Use CRM signals to produce a concise health report.
`;

const baseFiles = (): SkillTrustInputFile[] => [
  { path: "SKILL.md", content: Buffer.from(skillMd) },
  { path: "README.md", content: Buffer.from("# Account Health Review\n") },
];

describe("fixSkillTrustEvidence", () => {
  it("generates a skill card with a human summary and refreshed report", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: baseFiles(),
      step: "skillCard",
      scanner: { status: "completed", riskScore: 1 },
      now: new Date("2026-06-22T00:00:00Z"),
    });

    expect(result.status).toBe("generated");
    expect(result.artifactPath).toBe("skill-card.md");
    expect(result.artifact?.contentType).toBe("text/markdown; charset=utf-8");
    const card = result.artifact?.content.toString("utf8") ?? "";
    expect(card).toContain("# Account Health Review Skill Card");
    expect(card).toContain("## Summary");
    expect(card).toContain("Generated by ThinkWork");
    expect(card).toContain("Reviews account health signals");
    expect(card).toContain("crm_account_summary");
    expect(result.trustReport.evidence.skillCard).toBe("starter_generated");
    expect(result.trustReport.generatedAt).toBe("2026-06-22T00:00:00.000Z");
  });

  it("falls back to a deterministic skill card summary when model generation fails", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: baseFiles(),
      step: "skillCard",
      summaryGenerator: {
        generate: vi.fn(async () => {
          throw new Error("model unavailable");
        }),
      },
    });

    const card = result.artifact?.content.toString("utf8") ?? "";
    expect(result.status).toBe("generated");
    expect(card).toContain(
      "Account Health Review helps agents Reviews account health signals",
    );
  });

  it("uses an available summary generator for the skill-card summary", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: baseFiles(),
      step: "skillCard",
      summaryGenerator: {
        generate: vi.fn(async () => "Operator-facing model summary."),
      },
    });

    expect(result.artifact?.content.toString("utf8")).toContain(
      "Operator-facing model summary.",
    );
  });

  it("generates a seeder-valid smoke eval and marks it starter evidence", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: baseFiles(),
      step: "evalDataset",
      scanner: { status: "completed" },
    });

    expect(result.status).toBe("generated");
    expect(result.artifactPath).toBe("evals/smoke.json");
    const smoke = JSON.parse(result.artifact!.content.toString("utf8"));
    expect(smoke).toMatchObject({
      case_id: "smoke",
      query: expect.stringContaining("account-health-review"),
      rubric: expect.stringContaining("Pass if"),
    });
    expect(result.trustReport.evidence.evalDataset).toBe("starter_generated");
  });

  it("generates a benchmark readiness artifact without fabricated measurements", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: baseFiles(),
      step: "benchmark",
      scanner: { status: "completed" },
    });

    expect(result.status).toBe("generated");
    expect(result.artifactPath).toBe("BENCHMARK.md");
    const benchmark = result.artifact?.content.toString("utf8") ?? "";
    expect(benchmark).toContain("Generated by ThinkWork");
    expect(benchmark).toContain("Measured benchmark run: not recorded.");
    expect(benchmark).toContain("Pass rate: not measured.");
    expect(benchmark).not.toContain("100%");
    expect(result.trustReport.evidence.benchmark).toBe("starter_generated");
  });

  it("refuses to overwrite existing release evidence", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: [
        ...baseFiles(),
        { path: "skill-card.md", content: Buffer.from("# Existing\n") },
      ],
      step: "skillCard",
    });

    expect(result.status).toBe("existing_artifact");
    expect(result.artifact).toBeUndefined();
    expect(result.artifactPath).toBe("skill-card.md");
    expect(result.trustReport.evidence.skillCard).toBe("present");
  });

  it("does not generate evidence when SKILL.md is missing or invalid", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: [{ path: "README.md", content: Buffer.from("# Missing\n") }],
      step: "benchmark",
    });

    expect(result.status).toBe("invalid_skill");
    expect(result.artifact).toBeUndefined();
    expect(result.prerequisite).toBe("valid_skill_md");
    expect(result.trustReport.spec.status).toBe("failed");
  });

  it("reports missing signing configuration without creating a signature", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: baseFiles(),
      step: "signature",
      scanner: { status: "completed" },
    });

    expect(result.status).toBe("prerequisite_missing");
    expect(result.artifact).toBeUndefined();
    expect(result.prerequisite).toBe("signing_config");
    expect(result.trustReport.evidence.signature).toBe(
      "missing_signing_config",
    );
  });

  it("generates a signature only when the configured signer verifies it", async () => {
    const signer: SkillTrustSigner = {
      sign: vi.fn(async ({ signedPayloadHash }) =>
        Buffer.from(`sig:${signedPayloadHash}`),
      ),
      verify: vi.fn(
        async ({ signedPayloadHash, signature }) =>
          signature.toString("utf8") === `sig:${signedPayloadHash}`,
      ),
    };
    const files = baseFiles();
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files,
      step: "signature",
      scanner: { status: "completed" },
      signer,
    });

    expect(result.status).toBe("generated");
    expect(result.artifactPath).toBe("skill.oms.sig");
    expect(result.signedPayloadHash).toBe(computeSignedPayloadHash(files));
    expect(result.trustReport.evidence.signature).toBe("verified");
    expect(result.trustReport.signedPayloadHash).toBe(
      computeSignedPayloadHash(files),
    );
  });

  it("re-signs an existing signature for the current signed payload", async () => {
    const signer: SkillTrustSigner = {
      sign: vi.fn(async ({ signedPayloadHash }) =>
        Buffer.from(`sig:${signedPayloadHash}`),
      ),
      verify: vi.fn(
        async ({ signedPayloadHash, signature }) =>
          signature.toString("utf8") === `sig:${signedPayloadHash}`,
      ),
    };
    const files = [
      ...baseFiles(),
      { path: "skill.oms.sig", content: Buffer.from("old-signature") },
    ];

    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files,
      step: "signature",
      scanner: { status: "completed" },
      signer,
    });

    expect(result.status).toBe("generated");
    expect(result.artifactPath).toBe("skill.oms.sig");
    expect(result.artifact?.content.toString("utf8")).toBe(
      `sig:${computeSignedPayloadHash(files)}`,
    );
    expect(result.artifact?.content.toString("utf8")).not.toBe("old-signature");
    expect(result.trustReport.evidence.signature).toBe("verified");
    expect(result.trustReport.signedPayloadHash).toBe(
      computeSignedPayloadHash(files),
    );
  });

  it("rejects malformed signatures from a configured signer", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: baseFiles(),
      step: "signature",
      scanner: { status: "completed" },
      signer: {
        sign: vi.fn(async () => Buffer.from("bad-signature")),
        verify: vi.fn(async () => false),
      },
    });

    expect(result.status).toBe("prerequisite_missing");
    expect(result.artifact).toBeUndefined();
    expect(result.prerequisite).toBe("valid_signature");
    expect(result.trustReport.evidence.signature).toBe("invalid");
  });

  it("marks an existing signature stale after a content-changing evidence fix", async () => {
    const result = await fixSkillTrustEvidence({
      slug: "account-health-review",
      files: [
        ...baseFiles(),
        { path: "skill.oms.sig", content: Buffer.from("old-signature") },
      ],
      step: "benchmark",
      scanner: { status: "completed" },
    });

    expect(result.status).toBe("generated");
    expect(result.trustReport.evidence.signature).toBe("stale");
    expect(result.trustReport.signedPayloadHash).toMatch(/^[a-f0-9]{64}$/);
  });
});

describe("computeSignedPayloadHash", () => {
  it("excludes skill.oms.sig from the canonical payload", () => {
    const files = [
      ...baseFiles(),
      { path: "skill.oms.sig", content: Buffer.from("first") },
    ];
    const changedSignature = [
      ...baseFiles(),
      { path: "skill.oms.sig", content: Buffer.from("second") },
    ];

    expect(computeSignedPayloadHash(files)).toBe(
      computeSignedPayloadHash(changedSignature),
    );
  });
});
