import { Command } from "commander";
import { existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { execSync } from "node:child_process";
import { validateStage } from "../config.js";
import { getAwsIdentity } from "../aws.js";
import { printHeader, printSuccess, printError, printWarning } from "../ui.js";
import { createInterface } from "node:readline";

function ask(prompt: string, defaultVal = ""): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const suffix = defaultVal ? ` [${defaultVal}]` : "";
  return new Promise((resolve) => {
    rl.question(`${prompt}${suffix}: `, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultVal);
    });
  });
}

function generatePassword(): string {
  const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%";
  let pw = "";
  const bytes = new Uint8Array(32);
  globalThis.crypto.getRandomValues(bytes);
  for (const b of bytes) pw += chars[b % chars.length];
  return pw;
}

const TFVARS_TEMPLATE = `# Thinkwork — {STAGE} stage
# Generated by: thinkwork init -s {STAGE}

stage      = "{STAGE}"
region     = "{REGION}"
account_id = "{ACCOUNT_ID}"

# Database
database_engine = "aurora-serverless"
db_password = "{DB_PASSWORD}"

# Memory engine: "managed" (built-in) or "hindsight" (ECS Fargate service)
memory_engine = "{MEMORY_ENGINE}"

# API authentication secret (shared between services)
api_auth_secret = "{API_SECRET}"
`;

export function registerInitCommand(program: Command): void {
  program
    .command("init")
    .description("Initialize a new Thinkwork environment")
    .requiredOption("-s, --stage <name>", "Stage name (e.g. dev, staging, prod)")
    .option("-d, --dir <path>", "Directory to initialize in", ".")
    .action(async (opts: { stage: string; dir: string }) => {
      const stageCheck = validateStage(opts.stage);
      if (!stageCheck.valid) {
        printError(stageCheck.error!);
        process.exit(1);
      }

      const identity = getAwsIdentity();
      printHeader("init", opts.stage, identity);

      if (!identity) {
        printError("AWS credentials not configured. Run `thinkwork login` first.");
        process.exit(1);
      }

      const rootDir = resolve(opts.dir);
      const tfDir = join(rootDir, "terraform", "examples", "greenfield");

      // Check for existing terraform.tfvars
      const tfvarsPath = join(tfDir, "terraform.tfvars");
      if (existsSync(tfvarsPath)) {
        printWarning(`terraform.tfvars already exists at ${tfvarsPath}`);
        const overwrite = await ask("  Overwrite? [y/N]");
        if (overwrite.toLowerCase() !== "y") {
          console.log("  Aborted.");
          return;
        }
      }

      // Interactive configuration
      console.log("  Configure your Thinkwork environment:\n");

      const region = await ask("  AWS Region", identity.region !== "unknown" ? identity.region : "us-east-1");
      const memoryEngine = await ask("  Memory engine (managed/hindsight)", "managed");
      const dbPassword = generatePassword();
      const apiSecret = `tw-${opts.stage}-${generatePassword().slice(0, 12)}`;

      // Write terraform.tfvars
      if (!existsSync(tfDir)) {
        mkdirSync(tfDir, { recursive: true });
      }

      const tfvars = TFVARS_TEMPLATE
        .replace(/{STAGE}/g, opts.stage)
        .replace(/{REGION}/g, region)
        .replace(/{ACCOUNT_ID}/g, identity.account)
        .replace(/{DB_PASSWORD}/g, dbPassword)
        .replace(/{MEMORY_ENGINE}/g, memoryEngine)
        .replace(/{API_SECRET}/g, apiSecret);

      writeFileSync(tfvarsPath, tfvars);
      console.log(`\n  Wrote ${tfvarsPath}`);

      // Run terraform init
      console.log("\n  Initializing Terraform...\n");
      try {
        execSync("terraform init", { cwd: tfDir, stdio: "inherit" });
      } catch {
        printWarning("Terraform init failed — you may need to install Terraform first.");
        printWarning("Run: thinkwork doctor -s " + opts.stage);
        return;
      }

      printSuccess(`Environment "${opts.stage}" initialized`);
      console.log("");
      console.log("  Next steps:");
      console.log(`    1. thinkwork plan -s ${opts.stage}        # Review the plan`);
      console.log(`    2. thinkwork deploy -s ${opts.stage}       # Deploy infrastructure`);
      console.log(`    3. thinkwork bootstrap -s ${opts.stage}    # Seed workspace + skills`);
      console.log("");
    });
}
