import { Command } from "commander";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve, join } from "node:path";
import { execSync } from "node:child_process";
import { validateStage } from "../config.js";
import { getAwsIdentity } from "../aws.js";
import { printHeader, printSuccess, printError, printWarning } from "../ui.js";
import { createInterface } from "node:readline";
import chalk from "chalk";

function ask(prompt: string, defaultVal = ""): Promise<string> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  const suffix = defaultVal ? chalk.dim(` [${defaultVal}]`) : "";
  return new Promise((resolve) => {
    rl.question(`  ${prompt}${suffix}: `, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultVal);
    });
  });
}

function choose(prompt: string, options: string[], defaultVal: string): Promise<string> {
  const optStr = options.map(o => o === defaultVal ? chalk.bold(o) : chalk.dim(o)).join(" / ");
  return ask(`${prompt} (${optStr})`, defaultVal);
}

function generateSecret(length = 32): string {
  const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  let result = "";
  const bytes = new Uint8Array(length);
  globalThis.crypto.getRandomValues(bytes);
  for (const b of bytes) result += chars[b % chars.length];
  return result;
}

function buildTfvars(config: Record<string, string>): string {
  const lines: string[] = [
    `# Thinkwork — ${config.stage} stage`,
    `# Generated by: thinkwork init -s ${config.stage}`,
    `# ${new Date().toISOString().split("T")[0]}`,
    ``,
    `# ── Core ──────────────────────────────────────────────────────────`,
    `stage      = "${config.stage}"`,
    `region     = "${config.region}"`,
    `account_id = "${config.account_id}"`,
    ``,
    `# ── Database ──────────────────────────────────────────────────────`,
    `database_engine = "${config.database_engine}"`,
    `db_password     = "${config.db_password}"`,
    ``,
    `# ── Memory ────────────────────────────────────────────────────────`,
    `memory_engine = "${config.memory_engine}"`,
    ``,
    `# ── Auth ──────────────────────────────────────────────────────────`,
    `api_auth_secret = "${config.api_auth_secret}"`,
  ];

  if (config.google_oauth_client_id) {
    lines.push(``);
    lines.push(`# ── Google OAuth ──────────────────────────────────────────────────`);
    lines.push(`google_oauth_client_id     = "${config.google_oauth_client_id}"`);
    lines.push(`google_oauth_client_secret = "${config.google_oauth_client_secret}"`);
  } else {
    lines.push(``);
    lines.push(`# ── Google OAuth (uncomment to enable Google social login) ────────`);
    lines.push(`# google_oauth_client_id     = ""`);
    lines.push(`# google_oauth_client_secret = ""`);
  }

  if (config.admin_url && config.admin_url !== "http://localhost:5174") {
    lines.push(``);
    lines.push(`# ── Callback URLs ─────────────────────────────────────────────────`);
    lines.push(`admin_callback_urls  = ["${config.admin_url}", "${config.admin_url}/auth/callback"]`);
    lines.push(`admin_logout_urls    = ["${config.admin_url}"]`);
  }

  if (config.mobile_scheme && config.mobile_scheme !== "thinkwork") {
    lines.push(`mobile_callback_urls = ["${config.mobile_scheme}://", "${config.mobile_scheme}://auth/callback"]`);
    lines.push(`mobile_logout_urls   = ["${config.mobile_scheme}://"]`);
  }

  lines.push(``);
  return lines.join("\n");
}

export function registerInitCommand(program: Command): void {
  program
    .command("init")
    .description("Initialize a new Thinkwork environment")
    .requiredOption("-s, --stage <name>", "Stage name (e.g. dev, staging, prod)")
    .option("-d, --dir <path>", "Directory to initialize in", ".")
    .option("--defaults", "Skip interactive prompts, use all defaults")
    .action(async (opts: { stage: string; dir: string; defaults?: boolean }) => {
      const stageCheck = validateStage(opts.stage);
      if (!stageCheck.valid) {
        printError(stageCheck.error!);
        process.exit(1);
      }

      const identity = getAwsIdentity();
      printHeader("init", opts.stage, identity);

      if (!identity) {
        printError("AWS credentials not configured. Run `thinkwork login` first.");
        process.exit(1);
      }

      const rootDir = resolve(opts.dir);
      const tfDir = join(rootDir, "terraform", "examples", "greenfield");
      const tfvarsPath = join(tfDir, "terraform.tfvars");

      if (existsSync(tfvarsPath)) {
        printWarning(`terraform.tfvars already exists at ${tfvarsPath}`);
        const overwrite = await ask("Overwrite?", "N");
        if (overwrite.toLowerCase() !== "y") {
          console.log("  Aborted.");
          return;
        }
        console.log("");
      }

      // ── Collect configuration ──────────────────────────────────────

      const config: Record<string, string> = {
        stage: opts.stage,
        account_id: identity.account,
        db_password: generateSecret(24),
        api_auth_secret: `tw-${opts.stage}-${generateSecret(16)}`,
      };

      if (opts.defaults) {
        config.region = identity.region !== "unknown" ? identity.region : "us-east-1";
        config.database_engine = "aurora-serverless";
        config.memory_engine = "managed";
        config.google_oauth_client_id = "";
        config.google_oauth_client_secret = "";
        config.admin_url = "http://localhost:5174";
        config.mobile_scheme = "thinkwork";
      } else {
        console.log(chalk.bold("  Configure your Thinkwork environment\n"));

        // Region
        const defaultRegion = identity.region !== "unknown" ? identity.region : "us-east-1";
        config.region = await ask("AWS Region", defaultRegion);

        console.log("");
        console.log(chalk.dim("  ── Database ──"));

        // Database engine
        config.database_engine = await choose("Database engine", ["aurora-serverless", "rds-postgres"], "aurora-serverless");

        console.log("");
        console.log(chalk.dim("  ── Memory ──"));

        // Memory engine
        console.log(chalk.dim("  managed    = Built-in AgentCore memory (remember/recall/forget)"));
        console.log(chalk.dim("  hindsight  = ECS Fargate service with semantic + graph retrieval"));
        config.memory_engine = await choose("Memory engine", ["managed", "hindsight"], "managed");

        console.log("");
        console.log(chalk.dim("  ── Auth ──"));

        // Google OAuth
        const useGoogle = await ask("Enable Google OAuth login? (y/N)", "N");
        if (useGoogle.toLowerCase() === "y") {
          config.google_oauth_client_id = await ask("Google OAuth Client ID");
          config.google_oauth_client_secret = await ask("Google OAuth Client Secret");
        } else {
          config.google_oauth_client_id = "";
          config.google_oauth_client_secret = "";
        }

        console.log("");
        console.log(chalk.dim("  ── Frontend URLs ──"));

        // Admin UI URL
        config.admin_url = await ask("Admin UI URL", "http://localhost:5174");

        // Mobile scheme
        config.mobile_scheme = await ask("Mobile app URL scheme", "thinkwork");

        console.log("");
        console.log(chalk.dim("  ── Secrets (auto-generated) ──"));
        console.log(chalk.dim(`  DB password:     ${config.db_password.slice(0, 8)}...`));
        console.log(chalk.dim(`  API auth secret: ${config.api_auth_secret.slice(0, 16)}...`));
      }

      // ── Write terraform.tfvars ─────────────────────────────────────

      if (!existsSync(tfDir)) {
        mkdirSync(tfDir, { recursive: true });
      }

      const tfvars = buildTfvars(config);
      writeFileSync(tfvarsPath, tfvars);

      console.log("");
      console.log(`  Wrote ${chalk.cyan(tfvarsPath)}`);

      // ── Summary ────────────────────────────────────────────────────

      console.log("");
      console.log(chalk.dim("  ─────────────────────────────────────"));
      console.log(`  ${chalk.bold("Stage:")}           ${config.stage}`);
      console.log(`  ${chalk.bold("Region:")}          ${config.region}`);
      console.log(`  ${chalk.bold("Account:")}         ${config.account_id}`);
      console.log(`  ${chalk.bold("Database:")}        ${config.database_engine}`);
      console.log(`  ${chalk.bold("Memory:")}          ${config.memory_engine}`);
      console.log(`  ${chalk.bold("Google OAuth:")}    ${config.google_oauth_client_id ? "enabled" : "disabled"}`);
      console.log(chalk.dim("  ─────────────────────────────────────"));

      // ── Terraform init ─────────────────────────────────────────────

      console.log("\n  Initializing Terraform...\n");
      try {
        execSync("terraform init", { cwd: tfDir, stdio: "inherit" });
      } catch {
        printWarning("Terraform init failed. Run `thinkwork doctor -s " + opts.stage + "` to check prerequisites.");
        return;
      }

      printSuccess(`Environment "${opts.stage}" initialized`);
      console.log("");
      console.log("  Next steps:");
      console.log(`    ${chalk.cyan("1.")} thinkwork plan -s ${opts.stage}        ${chalk.dim("# Review infrastructure plan")}`);
      console.log(`    ${chalk.cyan("2.")} thinkwork deploy -s ${opts.stage}       ${chalk.dim("# Deploy to AWS")}`);
      console.log(`    ${chalk.cyan("3.")} thinkwork bootstrap -s ${opts.stage}    ${chalk.dim("# Seed workspace files + skills")}`);
      console.log(`    ${chalk.cyan("4.")} thinkwork outputs -s ${opts.stage}      ${chalk.dim("# Show API URL, Cognito IDs, etc.")}`);
      console.log("");
    });
}
