/**
 * Auto-provision helper: creates a Computer for a tenant member using the
 * platform-default Computer template. Wrapped in best-effort try/catch by
 * every call site (addTenantMember, inviteMember, bootstrapUser, REST
 * handlers) so a provisioning failure never blocks the primary membership
 * insert. Failure modes are surfaced via the `activity_log` audit trail so
 * admins can find and backfill stranded users.
 *
 * Bypasses `requireTenantAdmin` deliberately: at the bootstrapUser call
 * sites the new user is mid-creation and not yet tenant-admin-resolvable.
 * `createComputerCore` handles the actual write path and the validation
 * helpers (`requireTenantUser`, `requireComputerTemplate`,
 * `assertNoActiveComputer`).
 *
 * Idempotency rests on TWO error shapes: the pre-flight
 * `assertNoActiveComputer` throws a `GraphQLError` with
 * `extensions.code === "CONFLICT"`; a race between two concurrent
 * provisioners hits the DB partial unique index `uq_computers_active_owner`
 * and surfaces as Postgres SQLSTATE `23505`. Both map to
 * `skipped:already_active`.
 */

import { GraphQLError } from "graphql";
import {
	activityLog,
	agentTemplates,
	and,
	db,
	eq,
	isNull,
} from "../../graphql/utils.js";
import { createComputerCore } from "../../graphql/resolvers/computers/shared.js";

/** Slug for the platform-default Computer template seeded by 0085_seed_thinkwork_computer_default_template.sql. */
export const PLATFORM_DEFAULT_COMPUTER_TEMPLATE_SLUG =
	"thinkwork-computer-default";

/**
 * Sentinel actor_id for activity_log rows produced by server-internal
 * provisioning paths where no human caller maps to the action — currently
 * the `bootstrapUser` call sites, which fire under the new user's own JWT
 * but should not audit as "this user did something" to themselves.
 */
export const SYSTEM_ACTOR_ID = "00000000-0000-0000-0000-000000000000";

export type ProvisionCallSite =
	| "addTenantMember"
	| "inviteMember"
	| "bootstrapUser"
	| "restAddMember"
	| "restInvite";

export type ProvisionInput = {
	tenantId: string;
	/** The `principal_id` from the just-inserted tenant_members row. */
	userId: string;
	/** Lowercased before comparison; helper skips when not "user". */
	principalType: string;
	/** Identifies the resolver/handler that called the helper; controls actor attribution. */
	callSite: ProvisionCallSite;
	/**
	 * Optional template id to use instead of the platform default. Useful for
	 * future tenant-level default overrides; not used by v1 callers.
	 */
	templateId?: string | null;
	/**
	 * Optional admin user id that initiated the membership add. Used as
	 * activity_log `actor_id` for non-bootstrap call sites. For bootstrapUser,
	 * the actor is SYSTEM_ACTOR_ID regardless.
	 */
	adminUserId?: string | null;
};

export type ProvisionResult =
	| { status: "created"; computerId: string }
	| { status: "skipped"; reason: "already_active" | "not_user_principal" }
	| {
			status: "failed";
			reason:
				| "no_default_template"
				| "user_not_in_tenant"
				| "template_not_found"
				| "unknown";
			message?: string;
	  };

/**
 * Provision a Computer for a tenant member. Never throws — every error path
 * is captured into the discriminated `ProvisionResult` so the caller can
 * decide whether to write a log entry without coupling to thrown errors.
 */
export async function provisionComputerForMember(
	input: ProvisionInput,
): Promise<ProvisionResult> {
	// 1) Skip non-USER principals (teams, services). Case-insensitive because the
	//    codebase mixes 'USER' (inviteMember) and 'user' (bootstrapUser) casings.
	if (input.principalType.toLowerCase() !== "user") {
		return { status: "skipped", reason: "not_user_principal" };
	}

	// 2) Resolve the platform default template. The lookup pins template_kind
	//    AND tenant_id IS NULL in SQL — relying on a downstream
	//    requireComputerTemplate call alone would NOT prevent picking up a
	//    same-slug global template of a different kind.
	let resolvedTemplateId: string | null = input.templateId ?? null;
	if (!resolvedTemplateId) {
		const [defaultTemplate] = await db
			.select({ id: agentTemplates.id })
			.from(agentTemplates)
			.where(
				and(
					eq(agentTemplates.slug, PLATFORM_DEFAULT_COMPUTER_TEMPLATE_SLUG),
					isNull(agentTemplates.tenant_id),
					eq(agentTemplates.template_kind, "computer"),
				),
			);
		if (!defaultTemplate) {
			await safeWriteActivityLog({
				tenantId: input.tenantId,
				userId: input.userId,
				reason: "no_default_template",
				callSite: input.callSite,
				adminUserId: input.adminUserId,
			});
			return { status: "failed", reason: "no_default_template" };
		}
		resolvedTemplateId = defaultTemplate.id;
	}

	// 3) Attempt the insert. Map known conflict shapes to skipped.
	try {
		const row = await createComputerCore({
			tenantId: input.tenantId,
			ownerUserId: input.userId,
			templateId: resolvedTemplateId,
			name: deriveComputerName(input.userId),
			// Slug auto-generated by createComputerCore via generateSlug().
			createdBy: input.callSite === "bootstrapUser" ? null : input.adminUserId ?? null,
		});
		return { status: "created", computerId: row.id };
	} catch (err) {
		if (isAlreadyActiveConflict(err)) {
			return { status: "skipped", reason: "already_active" };
		}
		const reason = classifyValidationError(err);
		await safeWriteActivityLog({
			tenantId: input.tenantId,
			userId: input.userId,
			reason,
			callSite: input.callSite,
			adminUserId: input.adminUserId,
			message: errorMessage(err),
		});
		return { status: "failed", reason, message: errorMessage(err) };
	}
}

/**
 * Detect both error shapes the partial-unique-index invariant can surface:
 *   (a) `assertNoActiveComputer` throws `GraphQLError({ extensions: { code: "CONFLICT" } })`
 *   (b) the partial-unique-index race surfaces as Postgres SQLSTATE 23505
 *       (`err.code === "23505"` or `err.cause?.code === "23505"` when drizzle
 *       wraps it).
 */
function isAlreadyActiveConflict(err: unknown): boolean {
	if (err instanceof GraphQLError) {
		const code = (err.extensions as Record<string, unknown> | undefined)?.code;
		if (code === "CONFLICT") return true;
	}
	if (typeof err !== "object" || err === null) return false;
	const candidate = err as { code?: unknown; cause?: { code?: unknown } };
	if (candidate.code === "23505") return true;
	if (candidate.cause?.code === "23505") return true;
	return false;
}

function classifyValidationError(
	err: unknown,
): "user_not_in_tenant" | "template_not_found" | "unknown" {
	if (err instanceof GraphQLError) {
		const message = err.message.toLowerCase();
		if (message.includes("owner user not found")) return "user_not_in_tenant";
		if (message.includes("template not found")) return "template_not_found";
	}
	return "unknown";
}

function errorMessage(err: unknown): string {
	if (err instanceof Error) return err.message;
	return String(err);
}

function deriveComputerName(userId: string): string {
	// Short fallback name; admins can rename via the (future) Config tab.
	// Using the userId fragment avoids requiring a users.name lookup at
	// provisioning time and keeps the helper synchronous-ish.
	return `Computer ${userId.slice(0, 8)}`;
}

type FailureReason = Extract<ProvisionResult, { status: "failed" }>["reason"];

type ActivityArgs = {
	tenantId: string;
	userId: string;
	reason: FailureReason;
	callSite: ProvisionCallSite;
	adminUserId?: string | null;
	message?: string;
};

async function safeWriteActivityLog(args: ActivityArgs): Promise<void> {
	try {
		const actorId =
			args.callSite === "bootstrapUser"
				? SYSTEM_ACTOR_ID
				: args.adminUserId ?? SYSTEM_ACTOR_ID;
		const actorType = args.callSite === "bootstrapUser" ? "system" : "user";
		await db.insert(activityLog).values({
			tenant_id: args.tenantId,
			actor_type: actorType,
			actor_id: actorId,
			action: "computer_auto_provision_failed",
			entity_type: "user",
			entity_id: args.userId,
			metadata: {
				reason: args.reason,
				callSite: args.callSite,
				message: args.message ?? null,
			},
		});
	} catch (err) {
		console.error(
			"[provisionComputerForMember] activity_log write failed:",
			err,
		);
	}
}
