import { Search } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { useQuery } from "urql";
import { Button, Input } from "@thinkwork/ui";
import {
  type AppArtifactPreview,
  type AppletPreviewNode,
  toAppletPreview,
} from "@/lib/app-artifacts";
import { AppPreviewCard } from "@/components/apps/AppPreviewCard";
import { AppletsQuery } from "@/lib/graphql-queries";

interface AppsGalleryProps {
  applets?: AppArtifactPreview[];
}

interface AppletsResult {
  applets?: {
    nodes?: AppletPreviewNode[] | null;
    nextCursor?: string | null;
  } | null;
}

export function AppsGallery({ applets }: AppsGalleryProps) {
  if (applets) return <AppsGalleryContent artifacts={applets} />;
  return <LiveAppsGallery />;
}

function LiveAppsGallery() {
  const [{ data, fetching, error }] = useQuery<AppletsResult>({
    query: AppletsQuery,
    requestPolicy: "cache-and-network",
  });
  const artifacts = (data?.applets?.nodes ?? []).map(toAppletPreview);

  return (
    <AppsGalleryContent
      artifacts={artifacts}
      fetching={fetching}
      errorMessage={error?.message}
    />
  );
}

export function AppsGalleryContent({
  artifacts,
  fetching = false,
  errorMessage,
}: {
  artifacts: AppArtifactPreview[];
  fetching?: boolean;
  errorMessage?: string;
}) {
  return (
    <main className="flex w-full flex-1 flex-col">
      <div className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-4 py-6 sm:px-6">
        <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm text-muted-foreground">
            Outputs generated by your Computer, including apps, charts, and
            documents.
          </p>
          <Button asChild>
            <Link to="/new">Create artifact</Link>
          </Button>
        </header>

        {artifacts.length > 1 ? (
          <label className="relative max-w-md">
            <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
            <Input className="pl-9" placeholder="Search artifacts" />
          </label>
        ) : null}

        {fetching && artifacts.length === 0 ? (
          <div className="rounded-lg border border-border/70 p-8 text-center">
            <p className="text-muted-foreground">Loading artifacts...</p>
          </div>
        ) : errorMessage ? (
          <div className="rounded-lg border border-border/70 p-8 text-center">
            <p className="text-muted-foreground">
              {errorMessage || "Generated artifacts could not be loaded."}
            </p>
          </div>
        ) : artifacts.length === 0 ? (
          <div className="rounded-lg border border-border/70 p-8 text-center">
            <p className="text-muted-foreground">
              Ask Computer to create an artifact and it will appear here.
            </p>
          </div>
        ) : (
          <section
            aria-label="Generated artifacts"
            className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"
          >
            {artifacts.map((artifact) => (
              <AppPreviewCard key={artifact.id} artifact={artifact} />
            ))}
          </section>
        )}
      </div>
    </main>
  );
}
