import { Search } from "lucide-react";
import { Button, Input } from "@thinkwork/ui";
import {
  FIXTURE_APP_ARTIFACTS,
  type AppArtifactPreview,
} from "@/lib/app-artifacts";
import { AppPreviewCard } from "@/components/apps/AppPreviewCard";

interface AppsGalleryProps {
  artifacts?: AppArtifactPreview[];
}

export function AppsGallery({
  artifacts = FIXTURE_APP_ARTIFACTS,
}: AppsGalleryProps) {
  return (
    <main className="flex w-full flex-1 flex-col">
      <div className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-4 py-6 sm:px-6">
        <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight">Apps</h1>
            <p className="mt-1 text-sm text-muted-foreground">
              Interactive outputs generated by your Computer.
            </p>
          </div>
          <Button asChild>
            <a href="/computer">Build an app</a>
          </Button>
        </header>

        {artifacts.length > 1 ? (
          <label className="relative max-w-md">
            <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
            <Input className="pl-9" placeholder="Search apps" />
          </label>
        ) : null}

        {artifacts.length === 0 ? (
          <div className="rounded-lg border border-border/70 p-8 text-center">
            <p className="text-muted-foreground">
              Ask Computer to build a dashboard and it will appear here.
            </p>
          </div>
        ) : (
          <section
            aria-label="Generated apps"
            className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"
          >
            {artifacts.map((artifact) => (
              <AppPreviewCard key={artifact.id} artifact={artifact} />
            ))}
          </section>
        )}
      </div>
    </main>
  );
}
