import { cleanup, render, screen } from "@testing-library/react";
import { afterEach, describe, expect, it } from "vitest";
import { AppsGalleryContent } from "./AppsGallery";
import type { AppArtifactPreview } from "@/lib/app-artifacts";

afterEach(cleanup);

describe("AppsGallery", () => {
  it("renders applet cards", () => {
    render(<AppsGalleryContent artifacts={[fixtureAppletPreview]} />);

    // Page title now lives in AppTopBar via PageHeaderContext.
    expect(screen.getByText("LastMile CRM pipeline risk")).toBeTruthy();
  });

  it("renders an empty state", () => {
    render(<AppsGalleryContent artifacts={[]} />);

    expect(
      screen.getByText(/Ask Computer to create an artifact/i),
    ).toBeTruthy();
  });
});

const fixtureAppletPreview = {
  id: "33333333-3333-4333-8333-333333333333",
  title: "LastMile CRM pipeline risk",
  kind: "applet",
  summary: "Pipeline-risk applet generated by Computer.",
  href: "/artifacts/33333333-3333-4333-8333-333333333333",
  generatedAt: "2026-05-08T16:00:00.000Z",
  version: 1,
  modelId: "fixture",
  stdlibVersionAtGeneration: "0.1.0",
} satisfies AppArtifactPreview;
