/**
 * Temporary catalog fixtures so the Customize page renders with content
 * before the GraphQL resolvers (plan U8) and the page-side queries
 * (plan U4–U6) ship. Replace each per-tab fixture import with a real
 * urql query when those land; the file can be deleted at that point.
 */

import type { CustomizeItem } from "./customize-filtering";

export const CONNECTORS_FIXTURE: CustomizeItem[] = [
  {
    id: "slack",
    name: "Slack",
    description: "Read channels, send messages, react to threads.",
    category: "Messaging",
    iconFallback: "S",
    typeBadge: "MCP",
    connected: true,
    featured: true,
  },
  {
    id: "github",
    name: "GitHub",
    description: "Pull requests, issues, repo content, code review comments.",
    category: "Engineering",
    iconFallback: "G",
    typeBadge: "MCP",
    connected: true,
    featured: true,
  },
  {
    id: "linear",
    name: "Linear",
    description: "Issues, cycles, projects, and triage queues.",
    category: "Engineering",
    iconFallback: "L",
    typeBadge: "MCP",
    connected: false,
    featured: true,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Search, read, and summarize Drive documents.",
    category: "Files",
    iconFallback: "D",
    connected: true,
  },
  {
    id: "gmail",
    name: "Gmail",
    description: "Read and triage incoming mail; draft replies.",
    category: "Email",
    iconFallback: "M",
    connected: true,
    featured: true,
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Read schedule, propose meeting times, draft invites.",
    category: "Calendar",
    iconFallback: "C",
    connected: false,
  },
  {
    id: "notion",
    name: "Notion",
    description: "Search pages, read databases, draft updates.",
    category: "Docs",
    iconFallback: "N",
    typeBadge: "MCP",
    connected: false,
    featured: true,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    description: "Opportunities, accounts, contacts, and activity history.",
    category: "CRM",
    iconFallback: "SF",
    connected: false,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Deals, companies, contacts, marketing automation context.",
    category: "CRM",
    iconFallback: "H",
    connected: false,
  },
  {
    id: "jira",
    name: "Jira",
    description: "Tickets, sprints, and project boards.",
    category: "Engineering",
    iconFallback: "J",
    typeBadge: "MCP",
    connected: false,
  },
];

export const SKILLS_FIXTURE: CustomizeItem[] = [
  {
    id: "web-search",
    name: "Web search",
    description: "Search the open web, follow links, summarize results.",
    category: "Research",
    iconFallback: "W",
    connected: true,
    featured: true,
  },
  {
    id: "agent-email-send",
    name: "Send email",
    description: "Compose and send email on the user's behalf.",
    category: "Communication",
    iconFallback: "E",
    connected: true,
  },
  {
    id: "google-calendar",
    name: "Calendar coordination",
    description: "Find meeting times across calendars, propose invites.",
    category: "Calendar",
    iconFallback: "C",
    connected: true,
    featured: true,
  },
  {
    id: "sales-prep",
    name: "Sales call prep",
    description: "Brief the user before a sales call: account, deal, history.",
    category: "Sales",
    iconFallback: "S",
    connected: false,
    featured: true,
  },
  {
    id: "account-health-review",
    name: "Account health review",
    description: "Score account health from CRM signals + usage telemetry.",
    category: "Sales",
    iconFallback: "A",
    connected: false,
  },
  {
    id: "renewal-prep",
    name: "Renewal prep",
    description: "Pull renewal context: usage trends, contract terms, risks.",
    category: "Sales",
    iconFallback: "R",
    connected: false,
  },
  {
    id: "customer-onboarding",
    name: "Customer onboarding",
    description: "Drive a new customer through the onboarding checklist.",
    category: "Customer Success",
    iconFallback: "O",
    connected: false,
  },
  {
    id: "workspace-memory",
    name: "Workspace memory",
    description: "Recall and reflect on past sessions for compounding context.",
    category: "System",
    iconFallback: "M",
    connected: true,
  },
  {
    id: "artifacts",
    name: "Artifacts",
    description: "Render dashboards, briefs, and applets for the user.",
    category: "System",
    iconFallback: "A",
    connected: true,
  },
];

export const WORKFLOWS_FIXTURE: CustomizeItem[] = [
  {
    id: "daily-standup-digest",
    name: "Daily standup digest",
    description: "Summarize yesterday's work and today's plan from Linear + GitHub.",
    category: "Engineering",
    iconFallback: "D",
    connected: true,
    featured: true,
  },
  {
    id: "customer-health-refresh",
    name: "Customer health refresh",
    description: "Recompute health scores nightly across the active book of business.",
    category: "Customer Success",
    iconFallback: "H",
    connected: true,
    featured: true,
  },
  {
    id: "renewal-pipeline-sweep",
    name: "Renewal pipeline sweep",
    description: "Surface upcoming renewals every Monday with risk callouts.",
    category: "Sales",
    iconFallback: "R",
    connected: false,
    featured: true,
  },
  {
    id: "new-lead-triage",
    name: "New lead triage",
    description: "Score and route inbound leads to the right account exec.",
    category: "Sales",
    iconFallback: "L",
    connected: false,
  },
  {
    id: "weekly-sales-brief",
    name: "Weekly sales brief",
    description: "Friday wrap-up: pipeline movement, wins, blocked deals.",
    category: "Sales",
    iconFallback: "S",
    connected: false,
  },
  {
    id: "support-incident-postmortem",
    name: "Support incident postmortem",
    description: "Draft a postmortem after every P0/P1 support escalation.",
    category: "Customer Success",
    iconFallback: "P",
    connected: false,
  },
  {
    id: "weekly-product-changelog",
    name: "Weekly product changelog",
    description: "Generate a customer-facing changelog from merged PRs.",
    category: "Product",
    iconFallback: "C",
    connected: false,
  },
];
