/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as DeploymentProfileRouteImport } from "./routes/deployment-profile";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OnboardingWelcomeRouteImport } from "./routes/onboarding/welcome";
import { Route as AuthDesktopCallbackRouteImport } from "./routes/auth/desktop-callback";
import { Route as AuthCallbackRouteImport } from "./routes/auth/callback";
import { Route as AuthedSettingsRouteImport } from "./routes/_authed/settings";
import { Route as AuthedShellRouteImport } from "./routes/_authed/_shell";
import { Route as AuthedSettingsIndexRouteImport } from "./routes/_authed/settings.index";
import { Route as AuthedSettingsWikiRouteImport } from "./routes/_authed/settings.wiki";
import { Route as AuthedSettingsToolsRouteImport } from "./routes/_authed/settings.tools";
import { Route as AuthedSettingsModelCatalogRouteImport } from "./routes/_authed/settings.model-catalog";
import { Route as AuthedSettingsMemoryRouteImport } from "./routes/_authed/settings.memory";
import { Route as AuthedSettingsManagedApplicationsRouteImport } from "./routes/_authed/settings.managed-applications";
import { Route as AuthedSettingsLocalWorkspaceRouteImport } from "./routes/_authed/settings.local-workspace";
import { Route as AuthedSettingsKnowledgeGraphRouteImport } from "./routes/_authed/settings.knowledge-graph";
import { Route as AuthedSettingsGeneralRouteImport } from "./routes/_authed/settings.general";
import { Route as AuthedSettingsCrmRouteImport } from "./routes/_authed/settings.crm";
import { Route as AuthedSettingsBillingRouteImport } from "./routes/_authed/settings.billing";
import { Route as AuthedSettingsArtifactsRouteImport } from "./routes/_authed/settings.artifacts";
import { Route as AuthedSettingsAnalyticsRouteImport } from "./routes/_authed/settings.analytics";
import { Route as AuthedSettingsActivityRouteImport } from "./routes/_authed/settings.activity";
import { Route as AuthedShellNewRouteImport } from "./routes/_authed/_shell/new";
import { Route as AuthedShellMemoryRouteImport } from "./routes/_authed/_shell/memory";
import { Route as AuthedShellCustomizeRouteImport } from "./routes/_authed/_shell/customize";
import { Route as AuthedShellAutomationsRouteImport } from "./routes/_authed/_shell/automations";
import { Route as AuthedSettingsWebhooksIndexRouteImport } from "./routes/_authed/settings.webhooks.index";
import { Route as AuthedSettingsUsersIndexRouteImport } from "./routes/_authed/settings.users.index";
import { Route as AuthedSettingsSpacesIndexRouteImport } from "./routes/_authed/settings.spaces.index";
import { Route as AuthedSettingsSkillsIndexRouteImport } from "./routes/_authed/settings.skills.index";
import { Route as AuthedSettingsRoutinesIndexRouteImport } from "./routes/_authed/settings.routines.index";
import { Route as AuthedSettingsMcpServersIndexRouteImport } from "./routes/_authed/settings.mcp-servers.index";
import { Route as AuthedSettingsKnowledgeBasesIndexRouteImport } from "./routes/_authed/settings.knowledge-bases.index";
import { Route as AuthedSettingsEvaluationsIndexRouteImport } from "./routes/_authed/settings.evaluations.index";
import { Route as AuthedSettingsAutomationsIndexRouteImport } from "./routes/_authed/settings.automations.index";
import { Route as AuthedSettingsArtifactsIndexRouteImport } from "./routes/_authed/settings.artifacts.index";
import { Route as AuthedSettingsAgentsIndexRouteImport } from "./routes/_authed/settings.agents.index";
import { Route as AuthedShellThreadsIndexRouteImport } from "./routes/_authed/_shell/threads.index";
import { Route as AuthedShellSpacesIndexRouteImport } from "./routes/_authed/_shell/spaces.index";
import { Route as AuthedShellMemoryIndexRouteImport } from "./routes/_authed/_shell/memory.index";
import { Route as AuthedShellCustomizeIndexRouteImport } from "./routes/_authed/_shell/customize.index";
import { Route as AuthedShellAutomationsIndexRouteImport } from "./routes/_authed/_shell/automations.index";
import { Route as AuthedShellArtifactsIndexRouteImport } from "./routes/_authed/_shell/artifacts.index";
import { Route as AuthedShellApprovalsIndexRouteImport } from "./routes/_authed/_shell/approvals.index";
import { Route as AuthedSettingsWebhooksWebhookIdRouteImport } from "./routes/_authed/settings.webhooks.$webhookId";
import { Route as AuthedSettingsUsersUserIdRouteImport } from "./routes/_authed/settings.users.$userId";
import { Route as AuthedSettingsSpacesSpaceIdRouteImport } from "./routes/_authed/settings.spaces.$spaceId";
import { Route as AuthedSettingsSkillsSkillSlugRouteImport } from "./routes/_authed/settings.skills.$skillSlug";
import { Route as AuthedSettingsRoutinesRoutineIdRouteImport } from "./routes/_authed/settings.routines.$routineId";
import { Route as AuthedSettingsMemoryWikiRouteImport } from "./routes/_authed/settings.memory.wiki";
import { Route as AuthedSettingsMemoryKnowledgeGraphRouteImport } from "./routes/_authed/settings.memory.knowledge-graph";
import { Route as AuthedSettingsMemoryKnowledgeBasesRouteImport } from "./routes/_authed/settings.memory.knowledge-bases";
import { Route as AuthedSettingsMcpServersServerIdRouteImport } from "./routes/_authed/settings.mcp-servers.$serverId";
import { Route as AuthedSettingsKnowledgeBasesKbIdRouteImport } from "./routes/_authed/settings.knowledge-bases.$kbId";
import { Route as AuthedSettingsEvaluationsRunIdRouteImport } from "./routes/_authed/settings.evaluations.$runId";
import { Route as AuthedSettingsAutomationsScheduledJobIdRouteImport } from "./routes/_authed/settings.automations.$scheduledJobId";
import { Route as AuthedSettingsArtifactsIdRouteImport } from "./routes/_authed/settings.artifacts.$id";
import { Route as AuthedSettingsApplicationsKestraRouteImport } from "./routes/_authed/settings.applications.kestra";
import { Route as AuthedSettingsApplicationsCogneeRouteImport } from "./routes/_authed/settings.applications.cognee";
import { Route as AuthedSettingsAgentsProfileIdRouteImport } from "./routes/_authed/settings.agents.$profileId";
import { Route as AuthedSettingsActivityThreadIdRouteImport } from "./routes/_authed/settings.activity_.$threadId";
import { Route as AuthedShellThreadsIdRouteImport } from "./routes/_authed/_shell/threads.$id";
import { Route as AuthedShellSpacesSpaceIdRouteImport } from "./routes/_authed/_shell/spaces.$spaceId";
import { Route as AuthedShellMemoryPagesRouteImport } from "./routes/_authed/_shell/memory.pages";
import { Route as AuthedShellMemoryKbsRouteImport } from "./routes/_authed/_shell/memory.kbs";
import { Route as AuthedShellMemoryBrainRouteImport } from "./routes/_authed/_shell/memory.brain";
import { Route as AuthedShellCustomizeWorkflowsRouteImport } from "./routes/_authed/_shell/customize.workflows";
import { Route as AuthedShellCustomizeSkillsRouteImport } from "./routes/_authed/_shell/customize.skills";
import { Route as AuthedShellAutomationsScheduledJobIdRouteImport } from "./routes/_authed/_shell/automations.$scheduledJobId";
import { Route as AuthedShellArtifactsIdRouteImport } from "./routes/_authed/_shell/artifacts.$id";
import { Route as AuthedShellApprovalsApprovalIdRouteImport } from "./routes/_authed/_shell/approvals.$approvalId";
import { Route as AuthedShellActivityThreadIdRouteImport } from "./routes/_authed/_shell/activity.$threadId";
import { Route as AuthedSettingsEvaluationsStudioIndexRouteImport } from "./routes/_authed/settings.evaluations.studio.index";
import { Route as AuthedSettingsEvaluationsStudioNewRouteImport } from "./routes/_authed/settings.evaluations.studio.new";
import { Route as AuthedSettingsEvaluationsStudioTestCaseIdRouteImport } from "./routes/_authed/settings.evaluations.studio.$testCaseId";
import { Route as AuthedShellMemoryKbsKbIdRouteImport } from "./routes/_authed/_shell/memory.kbs.$kbId";
import { Route as AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRouteImport } from "./routes/_authed/settings.routines.$routineId_.executions.$executionId";
import { Route as AuthedSettingsEvaluationsStudioEditTestCaseIdRouteImport } from "./routes/_authed/settings.evaluations.studio.edit.$testCaseId";
import { Route as AuthedShellSpacesSpaceIdThreadsThreadIdRouteImport } from "./routes/_authed/_shell/spaces.$spaceId.threads.$threadId";

const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const DeploymentProfileRoute = DeploymentProfileRouteImport.update({
  id: "/deployment-profile",
  path: "/deployment-profile",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: "/onboarding/welcome",
  path: "/onboarding/welcome",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthDesktopCallbackRoute = AuthDesktopCallbackRouteImport.update({
  id: "/auth/desktop-callback",
  path: "/auth/desktop-callback",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedShellRoute = AuthedShellRouteImport.update({
  id: "/_shell",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedSettingsWikiRoute = AuthedSettingsWikiRouteImport.update({
  id: "/wiki",
  path: "/wiki",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedSettingsToolsRoute = AuthedSettingsToolsRouteImport.update({
  id: "/tools",
  path: "/tools",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedSettingsModelCatalogRoute =
  AuthedSettingsModelCatalogRouteImport.update({
    id: "/model-catalog",
    path: "/model-catalog",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsMemoryRoute = AuthedSettingsMemoryRouteImport.update({
  id: "/memory",
  path: "/memory",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedSettingsManagedApplicationsRoute =
  AuthedSettingsManagedApplicationsRouteImport.update({
    id: "/managed-applications",
    path: "/managed-applications",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsLocalWorkspaceRoute =
  AuthedSettingsLocalWorkspaceRouteImport.update({
    id: "/local-workspace",
    path: "/local-workspace",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsKnowledgeGraphRoute =
  AuthedSettingsKnowledgeGraphRouteImport.update({
    id: "/knowledge-graph",
    path: "/knowledge-graph",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsGeneralRoute = AuthedSettingsGeneralRouteImport.update({
  id: "/general",
  path: "/general",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedSettingsCrmRoute = AuthedSettingsCrmRouteImport.update({
  id: "/crm",
  path: "/crm",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedSettingsBillingRoute = AuthedSettingsBillingRouteImport.update({
  id: "/billing",
  path: "/billing",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedSettingsArtifactsRoute = AuthedSettingsArtifactsRouteImport.update({
  id: "/artifacts",
  path: "/artifacts",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedSettingsAnalyticsRoute = AuthedSettingsAnalyticsRouteImport.update({
  id: "/analytics",
  path: "/analytics",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedSettingsActivityRoute = AuthedSettingsActivityRouteImport.update({
  id: "/activity",
  path: "/activity",
  getParentRoute: () => AuthedSettingsRoute,
} as any);
const AuthedShellNewRoute = AuthedShellNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellMemoryRoute = AuthedShellMemoryRouteImport.update({
  id: "/memory",
  path: "/memory",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellCustomizeRoute = AuthedShellCustomizeRouteImport.update({
  id: "/customize",
  path: "/customize",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellAutomationsRoute = AuthedShellAutomationsRouteImport.update({
  id: "/automations",
  path: "/automations",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedSettingsWebhooksIndexRoute =
  AuthedSettingsWebhooksIndexRouteImport.update({
    id: "/webhooks/",
    path: "/webhooks/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsUsersIndexRoute =
  AuthedSettingsUsersIndexRouteImport.update({
    id: "/users/",
    path: "/users/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsSpacesIndexRoute =
  AuthedSettingsSpacesIndexRouteImport.update({
    id: "/spaces/",
    path: "/spaces/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsSkillsIndexRoute =
  AuthedSettingsSkillsIndexRouteImport.update({
    id: "/skills/",
    path: "/skills/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsRoutinesIndexRoute =
  AuthedSettingsRoutinesIndexRouteImport.update({
    id: "/routines/",
    path: "/routines/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsMcpServersIndexRoute =
  AuthedSettingsMcpServersIndexRouteImport.update({
    id: "/mcp-servers/",
    path: "/mcp-servers/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsKnowledgeBasesIndexRoute =
  AuthedSettingsKnowledgeBasesIndexRouteImport.update({
    id: "/knowledge-bases/",
    path: "/knowledge-bases/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsEvaluationsIndexRoute =
  AuthedSettingsEvaluationsIndexRouteImport.update({
    id: "/evaluations/",
    path: "/evaluations/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsAutomationsIndexRoute =
  AuthedSettingsAutomationsIndexRouteImport.update({
    id: "/automations/",
    path: "/automations/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsArtifactsIndexRoute =
  AuthedSettingsArtifactsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedSettingsArtifactsRoute,
  } as any);
const AuthedSettingsAgentsIndexRoute =
  AuthedSettingsAgentsIndexRouteImport.update({
    id: "/agents/",
    path: "/agents/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedShellThreadsIndexRoute = AuthedShellThreadsIndexRouteImport.update({
  id: "/threads/",
  path: "/threads/",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellSpacesIndexRoute = AuthedShellSpacesIndexRouteImport.update({
  id: "/spaces/",
  path: "/spaces/",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellMemoryIndexRoute = AuthedShellMemoryIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedShellMemoryRoute,
} as any);
const AuthedShellCustomizeIndexRoute =
  AuthedShellCustomizeIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedShellCustomizeRoute,
  } as any);
const AuthedShellAutomationsIndexRoute =
  AuthedShellAutomationsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedShellAutomationsRoute,
  } as any);
const AuthedShellArtifactsIndexRoute =
  AuthedShellArtifactsIndexRouteImport.update({
    id: "/artifacts/",
    path: "/artifacts/",
    getParentRoute: () => AuthedShellRoute,
  } as any);
const AuthedShellApprovalsIndexRoute =
  AuthedShellApprovalsIndexRouteImport.update({
    id: "/approvals/",
    path: "/approvals/",
    getParentRoute: () => AuthedShellRoute,
  } as any);
const AuthedSettingsWebhooksWebhookIdRoute =
  AuthedSettingsWebhooksWebhookIdRouteImport.update({
    id: "/webhooks/$webhookId",
    path: "/webhooks/$webhookId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsUsersUserIdRoute =
  AuthedSettingsUsersUserIdRouteImport.update({
    id: "/users/$userId",
    path: "/users/$userId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsSpacesSpaceIdRoute =
  AuthedSettingsSpacesSpaceIdRouteImport.update({
    id: "/spaces/$spaceId",
    path: "/spaces/$spaceId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsSkillsSkillSlugRoute =
  AuthedSettingsSkillsSkillSlugRouteImport.update({
    id: "/skills/$skillSlug",
    path: "/skills/$skillSlug",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsRoutinesRoutineIdRoute =
  AuthedSettingsRoutinesRoutineIdRouteImport.update({
    id: "/routines/$routineId",
    path: "/routines/$routineId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsMemoryWikiRoute =
  AuthedSettingsMemoryWikiRouteImport.update({
    id: "/wiki",
    path: "/wiki",
    getParentRoute: () => AuthedSettingsMemoryRoute,
  } as any);
const AuthedSettingsMemoryKnowledgeGraphRoute =
  AuthedSettingsMemoryKnowledgeGraphRouteImport.update({
    id: "/knowledge-graph",
    path: "/knowledge-graph",
    getParentRoute: () => AuthedSettingsMemoryRoute,
  } as any);
const AuthedSettingsMemoryKnowledgeBasesRoute =
  AuthedSettingsMemoryKnowledgeBasesRouteImport.update({
    id: "/knowledge-bases",
    path: "/knowledge-bases",
    getParentRoute: () => AuthedSettingsMemoryRoute,
  } as any);
const AuthedSettingsMcpServersServerIdRoute =
  AuthedSettingsMcpServersServerIdRouteImport.update({
    id: "/mcp-servers/$serverId",
    path: "/mcp-servers/$serverId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsKnowledgeBasesKbIdRoute =
  AuthedSettingsKnowledgeBasesKbIdRouteImport.update({
    id: "/knowledge-bases/$kbId",
    path: "/knowledge-bases/$kbId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsEvaluationsRunIdRoute =
  AuthedSettingsEvaluationsRunIdRouteImport.update({
    id: "/evaluations/$runId",
    path: "/evaluations/$runId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsAutomationsScheduledJobIdRoute =
  AuthedSettingsAutomationsScheduledJobIdRouteImport.update({
    id: "/automations/$scheduledJobId",
    path: "/automations/$scheduledJobId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsArtifactsIdRoute =
  AuthedSettingsArtifactsIdRouteImport.update({
    id: "/$id",
    path: "/$id",
    getParentRoute: () => AuthedSettingsArtifactsRoute,
  } as any);
const AuthedSettingsApplicationsKestraRoute =
  AuthedSettingsApplicationsKestraRouteImport.update({
    id: "/applications/kestra",
    path: "/applications/kestra",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsApplicationsCogneeRoute =
  AuthedSettingsApplicationsCogneeRouteImport.update({
    id: "/applications/cognee",
    path: "/applications/cognee",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsAgentsProfileIdRoute =
  AuthedSettingsAgentsProfileIdRouteImport.update({
    id: "/agents/$profileId",
    path: "/agents/$profileId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsActivityThreadIdRoute =
  AuthedSettingsActivityThreadIdRouteImport.update({
    id: "/activity_/$threadId",
    path: "/activity/$threadId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedShellThreadsIdRoute = AuthedShellThreadsIdRouteImport.update({
  id: "/threads/$id",
  path: "/threads/$id",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellSpacesSpaceIdRoute =
  AuthedShellSpacesSpaceIdRouteImport.update({
    id: "/spaces/$spaceId",
    path: "/spaces/$spaceId",
    getParentRoute: () => AuthedShellRoute,
  } as any);
const AuthedShellMemoryPagesRoute = AuthedShellMemoryPagesRouteImport.update({
  id: "/pages",
  path: "/pages",
  getParentRoute: () => AuthedShellMemoryRoute,
} as any);
const AuthedShellMemoryKbsRoute = AuthedShellMemoryKbsRouteImport.update({
  id: "/kbs",
  path: "/kbs",
  getParentRoute: () => AuthedShellMemoryRoute,
} as any);
const AuthedShellMemoryBrainRoute = AuthedShellMemoryBrainRouteImport.update({
  id: "/brain",
  path: "/brain",
  getParentRoute: () => AuthedShellMemoryRoute,
} as any);
const AuthedShellCustomizeWorkflowsRoute =
  AuthedShellCustomizeWorkflowsRouteImport.update({
    id: "/workflows",
    path: "/workflows",
    getParentRoute: () => AuthedShellCustomizeRoute,
  } as any);
const AuthedShellCustomizeSkillsRoute =
  AuthedShellCustomizeSkillsRouteImport.update({
    id: "/skills",
    path: "/skills",
    getParentRoute: () => AuthedShellCustomizeRoute,
  } as any);
const AuthedShellAutomationsScheduledJobIdRoute =
  AuthedShellAutomationsScheduledJobIdRouteImport.update({
    id: "/$scheduledJobId",
    path: "/$scheduledJobId",
    getParentRoute: () => AuthedShellAutomationsRoute,
  } as any);
const AuthedShellArtifactsIdRoute = AuthedShellArtifactsIdRouteImport.update({
  id: "/artifacts/$id",
  path: "/artifacts/$id",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellApprovalsApprovalIdRoute =
  AuthedShellApprovalsApprovalIdRouteImport.update({
    id: "/approvals/$approvalId",
    path: "/approvals/$approvalId",
    getParentRoute: () => AuthedShellRoute,
  } as any);
const AuthedShellActivityThreadIdRoute =
  AuthedShellActivityThreadIdRouteImport.update({
    id: "/activity/$threadId",
    path: "/activity/$threadId",
    getParentRoute: () => AuthedShellRoute,
  } as any);
const AuthedSettingsEvaluationsStudioIndexRoute =
  AuthedSettingsEvaluationsStudioIndexRouteImport.update({
    id: "/evaluations/studio/",
    path: "/evaluations/studio/",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsEvaluationsStudioNewRoute =
  AuthedSettingsEvaluationsStudioNewRouteImport.update({
    id: "/evaluations/studio/new",
    path: "/evaluations/studio/new",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsEvaluationsStudioTestCaseIdRoute =
  AuthedSettingsEvaluationsStudioTestCaseIdRouteImport.update({
    id: "/evaluations/studio/$testCaseId",
    path: "/evaluations/studio/$testCaseId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedShellMemoryKbsKbIdRoute =
  AuthedShellMemoryKbsKbIdRouteImport.update({
    id: "/$kbId",
    path: "/$kbId",
    getParentRoute: () => AuthedShellMemoryKbsRoute,
  } as any);
const AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRoute =
  AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRouteImport.update({
    id: "/routines/$routineId_/executions/$executionId",
    path: "/routines/$routineId/executions/$executionId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedSettingsEvaluationsStudioEditTestCaseIdRoute =
  AuthedSettingsEvaluationsStudioEditTestCaseIdRouteImport.update({
    id: "/evaluations/studio/edit/$testCaseId",
    path: "/evaluations/studio/edit/$testCaseId",
    getParentRoute: () => AuthedSettingsRoute,
  } as any);
const AuthedShellSpacesSpaceIdThreadsThreadIdRoute =
  AuthedShellSpacesSpaceIdThreadsThreadIdRouteImport.update({
    id: "/threads/$threadId",
    path: "/threads/$threadId",
    getParentRoute: () => AuthedShellSpacesSpaceIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/deployment-profile": typeof DeploymentProfileRoute;
  "/sign-in": typeof SignInRoute;
  "/settings": typeof AuthedSettingsRouteWithChildren;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/desktop-callback": typeof AuthDesktopCallbackRoute;
  "/onboarding/welcome": typeof OnboardingWelcomeRoute;
  "/automations": typeof AuthedShellAutomationsRouteWithChildren;
  "/customize": typeof AuthedShellCustomizeRouteWithChildren;
  "/memory": typeof AuthedShellMemoryRouteWithChildren;
  "/new": typeof AuthedShellNewRoute;
  "/settings/activity": typeof AuthedSettingsActivityRoute;
  "/settings/analytics": typeof AuthedSettingsAnalyticsRoute;
  "/settings/artifacts": typeof AuthedSettingsArtifactsRouteWithChildren;
  "/settings/billing": typeof AuthedSettingsBillingRoute;
  "/settings/crm": typeof AuthedSettingsCrmRoute;
  "/settings/general": typeof AuthedSettingsGeneralRoute;
  "/settings/knowledge-graph": typeof AuthedSettingsKnowledgeGraphRoute;
  "/settings/local-workspace": typeof AuthedSettingsLocalWorkspaceRoute;
  "/settings/managed-applications": typeof AuthedSettingsManagedApplicationsRoute;
  "/settings/memory": typeof AuthedSettingsMemoryRouteWithChildren;
  "/settings/model-catalog": typeof AuthedSettingsModelCatalogRoute;
  "/settings/tools": typeof AuthedSettingsToolsRoute;
  "/settings/wiki": typeof AuthedSettingsWikiRoute;
  "/settings/": typeof AuthedSettingsIndexRoute;
  "/activity/$threadId": typeof AuthedShellActivityThreadIdRoute;
  "/approvals/$approvalId": typeof AuthedShellApprovalsApprovalIdRoute;
  "/artifacts/$id": typeof AuthedShellArtifactsIdRoute;
  "/automations/$scheduledJobId": typeof AuthedShellAutomationsScheduledJobIdRoute;
  "/customize/skills": typeof AuthedShellCustomizeSkillsRoute;
  "/customize/workflows": typeof AuthedShellCustomizeWorkflowsRoute;
  "/memory/brain": typeof AuthedShellMemoryBrainRoute;
  "/memory/kbs": typeof AuthedShellMemoryKbsRouteWithChildren;
  "/memory/pages": typeof AuthedShellMemoryPagesRoute;
  "/spaces/$spaceId": typeof AuthedShellSpacesSpaceIdRouteWithChildren;
  "/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/settings/activity/$threadId": typeof AuthedSettingsActivityThreadIdRoute;
  "/settings/agents/$profileId": typeof AuthedSettingsAgentsProfileIdRoute;
  "/settings/applications/cognee": typeof AuthedSettingsApplicationsCogneeRoute;
  "/settings/applications/kestra": typeof AuthedSettingsApplicationsKestraRoute;
  "/settings/artifacts/$id": typeof AuthedSettingsArtifactsIdRoute;
  "/settings/automations/$scheduledJobId": typeof AuthedSettingsAutomationsScheduledJobIdRoute;
  "/settings/evaluations/$runId": typeof AuthedSettingsEvaluationsRunIdRoute;
  "/settings/knowledge-bases/$kbId": typeof AuthedSettingsKnowledgeBasesKbIdRoute;
  "/settings/mcp-servers/$serverId": typeof AuthedSettingsMcpServersServerIdRoute;
  "/settings/memory/knowledge-bases": typeof AuthedSettingsMemoryKnowledgeBasesRoute;
  "/settings/memory/knowledge-graph": typeof AuthedSettingsMemoryKnowledgeGraphRoute;
  "/settings/memory/wiki": typeof AuthedSettingsMemoryWikiRoute;
  "/settings/routines/$routineId": typeof AuthedSettingsRoutinesRoutineIdRoute;
  "/settings/skills/$skillSlug": typeof AuthedSettingsSkillsSkillSlugRoute;
  "/settings/spaces/$spaceId": typeof AuthedSettingsSpacesSpaceIdRoute;
  "/settings/users/$userId": typeof AuthedSettingsUsersUserIdRoute;
  "/settings/webhooks/$webhookId": typeof AuthedSettingsWebhooksWebhookIdRoute;
  "/approvals/": typeof AuthedShellApprovalsIndexRoute;
  "/artifacts/": typeof AuthedShellArtifactsIndexRoute;
  "/automations/": typeof AuthedShellAutomationsIndexRoute;
  "/customize/": typeof AuthedShellCustomizeIndexRoute;
  "/memory/": typeof AuthedShellMemoryIndexRoute;
  "/spaces/": typeof AuthedShellSpacesIndexRoute;
  "/threads/": typeof AuthedShellThreadsIndexRoute;
  "/settings/agents/": typeof AuthedSettingsAgentsIndexRoute;
  "/settings/artifacts/": typeof AuthedSettingsArtifactsIndexRoute;
  "/settings/automations/": typeof AuthedSettingsAutomationsIndexRoute;
  "/settings/evaluations/": typeof AuthedSettingsEvaluationsIndexRoute;
  "/settings/knowledge-bases/": typeof AuthedSettingsKnowledgeBasesIndexRoute;
  "/settings/mcp-servers/": typeof AuthedSettingsMcpServersIndexRoute;
  "/settings/routines/": typeof AuthedSettingsRoutinesIndexRoute;
  "/settings/skills/": typeof AuthedSettingsSkillsIndexRoute;
  "/settings/spaces/": typeof AuthedSettingsSpacesIndexRoute;
  "/settings/users/": typeof AuthedSettingsUsersIndexRoute;
  "/settings/webhooks/": typeof AuthedSettingsWebhooksIndexRoute;
  "/memory/kbs/$kbId": typeof AuthedShellMemoryKbsKbIdRoute;
  "/settings/evaluations/studio/$testCaseId": typeof AuthedSettingsEvaluationsStudioTestCaseIdRoute;
  "/settings/evaluations/studio/new": typeof AuthedSettingsEvaluationsStudioNewRoute;
  "/settings/evaluations/studio/": typeof AuthedSettingsEvaluationsStudioIndexRoute;
  "/spaces/$spaceId/threads/$threadId": typeof AuthedShellSpacesSpaceIdThreadsThreadIdRoute;
  "/settings/evaluations/studio/edit/$testCaseId": typeof AuthedSettingsEvaluationsStudioEditTestCaseIdRoute;
  "/settings/routines/$routineId/executions/$executionId": typeof AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/deployment-profile": typeof DeploymentProfileRoute;
  "/sign-in": typeof SignInRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/desktop-callback": typeof AuthDesktopCallbackRoute;
  "/onboarding/welcome": typeof OnboardingWelcomeRoute;
  "/new": typeof AuthedShellNewRoute;
  "/settings/activity": typeof AuthedSettingsActivityRoute;
  "/settings/analytics": typeof AuthedSettingsAnalyticsRoute;
  "/settings/billing": typeof AuthedSettingsBillingRoute;
  "/settings/crm": typeof AuthedSettingsCrmRoute;
  "/settings/general": typeof AuthedSettingsGeneralRoute;
  "/settings/knowledge-graph": typeof AuthedSettingsKnowledgeGraphRoute;
  "/settings/local-workspace": typeof AuthedSettingsLocalWorkspaceRoute;
  "/settings/managed-applications": typeof AuthedSettingsManagedApplicationsRoute;
  "/settings/memory": typeof AuthedSettingsMemoryRouteWithChildren;
  "/settings/model-catalog": typeof AuthedSettingsModelCatalogRoute;
  "/settings/tools": typeof AuthedSettingsToolsRoute;
  "/settings/wiki": typeof AuthedSettingsWikiRoute;
  "/settings": typeof AuthedSettingsIndexRoute;
  "/activity/$threadId": typeof AuthedShellActivityThreadIdRoute;
  "/approvals/$approvalId": typeof AuthedShellApprovalsApprovalIdRoute;
  "/artifacts/$id": typeof AuthedShellArtifactsIdRoute;
  "/automations/$scheduledJobId": typeof AuthedShellAutomationsScheduledJobIdRoute;
  "/customize/skills": typeof AuthedShellCustomizeSkillsRoute;
  "/customize/workflows": typeof AuthedShellCustomizeWorkflowsRoute;
  "/memory/brain": typeof AuthedShellMemoryBrainRoute;
  "/memory/kbs": typeof AuthedShellMemoryKbsRouteWithChildren;
  "/memory/pages": typeof AuthedShellMemoryPagesRoute;
  "/spaces/$spaceId": typeof AuthedShellSpacesSpaceIdRouteWithChildren;
  "/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/settings/activity/$threadId": typeof AuthedSettingsActivityThreadIdRoute;
  "/settings/agents/$profileId": typeof AuthedSettingsAgentsProfileIdRoute;
  "/settings/applications/cognee": typeof AuthedSettingsApplicationsCogneeRoute;
  "/settings/applications/kestra": typeof AuthedSettingsApplicationsKestraRoute;
  "/settings/artifacts/$id": typeof AuthedSettingsArtifactsIdRoute;
  "/settings/automations/$scheduledJobId": typeof AuthedSettingsAutomationsScheduledJobIdRoute;
  "/settings/evaluations/$runId": typeof AuthedSettingsEvaluationsRunIdRoute;
  "/settings/knowledge-bases/$kbId": typeof AuthedSettingsKnowledgeBasesKbIdRoute;
  "/settings/mcp-servers/$serverId": typeof AuthedSettingsMcpServersServerIdRoute;
  "/settings/memory/knowledge-bases": typeof AuthedSettingsMemoryKnowledgeBasesRoute;
  "/settings/memory/knowledge-graph": typeof AuthedSettingsMemoryKnowledgeGraphRoute;
  "/settings/memory/wiki": typeof AuthedSettingsMemoryWikiRoute;
  "/settings/routines/$routineId": typeof AuthedSettingsRoutinesRoutineIdRoute;
  "/settings/skills/$skillSlug": typeof AuthedSettingsSkillsSkillSlugRoute;
  "/settings/spaces/$spaceId": typeof AuthedSettingsSpacesSpaceIdRoute;
  "/settings/users/$userId": typeof AuthedSettingsUsersUserIdRoute;
  "/settings/webhooks/$webhookId": typeof AuthedSettingsWebhooksWebhookIdRoute;
  "/approvals": typeof AuthedShellApprovalsIndexRoute;
  "/artifacts": typeof AuthedShellArtifactsIndexRoute;
  "/automations": typeof AuthedShellAutomationsIndexRoute;
  "/customize": typeof AuthedShellCustomizeIndexRoute;
  "/memory": typeof AuthedShellMemoryIndexRoute;
  "/spaces": typeof AuthedShellSpacesIndexRoute;
  "/threads": typeof AuthedShellThreadsIndexRoute;
  "/settings/agents": typeof AuthedSettingsAgentsIndexRoute;
  "/settings/artifacts": typeof AuthedSettingsArtifactsIndexRoute;
  "/settings/automations": typeof AuthedSettingsAutomationsIndexRoute;
  "/settings/evaluations": typeof AuthedSettingsEvaluationsIndexRoute;
  "/settings/knowledge-bases": typeof AuthedSettingsKnowledgeBasesIndexRoute;
  "/settings/mcp-servers": typeof AuthedSettingsMcpServersIndexRoute;
  "/settings/routines": typeof AuthedSettingsRoutinesIndexRoute;
  "/settings/skills": typeof AuthedSettingsSkillsIndexRoute;
  "/settings/spaces": typeof AuthedSettingsSpacesIndexRoute;
  "/settings/users": typeof AuthedSettingsUsersIndexRoute;
  "/settings/webhooks": typeof AuthedSettingsWebhooksIndexRoute;
  "/memory/kbs/$kbId": typeof AuthedShellMemoryKbsKbIdRoute;
  "/settings/evaluations/studio/$testCaseId": typeof AuthedSettingsEvaluationsStudioTestCaseIdRoute;
  "/settings/evaluations/studio/new": typeof AuthedSettingsEvaluationsStudioNewRoute;
  "/settings/evaluations/studio": typeof AuthedSettingsEvaluationsStudioIndexRoute;
  "/spaces/$spaceId/threads/$threadId": typeof AuthedShellSpacesSpaceIdThreadsThreadIdRoute;
  "/settings/evaluations/studio/edit/$testCaseId": typeof AuthedSettingsEvaluationsStudioEditTestCaseIdRoute;
  "/settings/routines/$routineId/executions/$executionId": typeof AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/deployment-profile": typeof DeploymentProfileRoute;
  "/sign-in": typeof SignInRoute;
  "/_authed/_shell": typeof AuthedShellRouteWithChildren;
  "/_authed/settings": typeof AuthedSettingsRouteWithChildren;
  "/auth/callback": typeof AuthCallbackRoute;
  "/auth/desktop-callback": typeof AuthDesktopCallbackRoute;
  "/onboarding/welcome": typeof OnboardingWelcomeRoute;
  "/_authed/_shell/automations": typeof AuthedShellAutomationsRouteWithChildren;
  "/_authed/_shell/customize": typeof AuthedShellCustomizeRouteWithChildren;
  "/_authed/_shell/memory": typeof AuthedShellMemoryRouteWithChildren;
  "/_authed/_shell/new": typeof AuthedShellNewRoute;
  "/_authed/settings/activity": typeof AuthedSettingsActivityRoute;
  "/_authed/settings/analytics": typeof AuthedSettingsAnalyticsRoute;
  "/_authed/settings/artifacts": typeof AuthedSettingsArtifactsRouteWithChildren;
  "/_authed/settings/billing": typeof AuthedSettingsBillingRoute;
  "/_authed/settings/crm": typeof AuthedSettingsCrmRoute;
  "/_authed/settings/general": typeof AuthedSettingsGeneralRoute;
  "/_authed/settings/knowledge-graph": typeof AuthedSettingsKnowledgeGraphRoute;
  "/_authed/settings/local-workspace": typeof AuthedSettingsLocalWorkspaceRoute;
  "/_authed/settings/managed-applications": typeof AuthedSettingsManagedApplicationsRoute;
  "/_authed/settings/memory": typeof AuthedSettingsMemoryRouteWithChildren;
  "/_authed/settings/model-catalog": typeof AuthedSettingsModelCatalogRoute;
  "/_authed/settings/tools": typeof AuthedSettingsToolsRoute;
  "/_authed/settings/wiki": typeof AuthedSettingsWikiRoute;
  "/_authed/settings/": typeof AuthedSettingsIndexRoute;
  "/_authed/_shell/activity/$threadId": typeof AuthedShellActivityThreadIdRoute;
  "/_authed/_shell/approvals/$approvalId": typeof AuthedShellApprovalsApprovalIdRoute;
  "/_authed/_shell/artifacts/$id": typeof AuthedShellArtifactsIdRoute;
  "/_authed/_shell/automations/$scheduledJobId": typeof AuthedShellAutomationsScheduledJobIdRoute;
  "/_authed/_shell/customize/skills": typeof AuthedShellCustomizeSkillsRoute;
  "/_authed/_shell/customize/workflows": typeof AuthedShellCustomizeWorkflowsRoute;
  "/_authed/_shell/memory/brain": typeof AuthedShellMemoryBrainRoute;
  "/_authed/_shell/memory/kbs": typeof AuthedShellMemoryKbsRouteWithChildren;
  "/_authed/_shell/memory/pages": typeof AuthedShellMemoryPagesRoute;
  "/_authed/_shell/spaces/$spaceId": typeof AuthedShellSpacesSpaceIdRouteWithChildren;
  "/_authed/_shell/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/_authed/settings/activity_/$threadId": typeof AuthedSettingsActivityThreadIdRoute;
  "/_authed/settings/agents/$profileId": typeof AuthedSettingsAgentsProfileIdRoute;
  "/_authed/settings/applications/cognee": typeof AuthedSettingsApplicationsCogneeRoute;
  "/_authed/settings/applications/kestra": typeof AuthedSettingsApplicationsKestraRoute;
  "/_authed/settings/artifacts/$id": typeof AuthedSettingsArtifactsIdRoute;
  "/_authed/settings/automations/$scheduledJobId": typeof AuthedSettingsAutomationsScheduledJobIdRoute;
  "/_authed/settings/evaluations/$runId": typeof AuthedSettingsEvaluationsRunIdRoute;
  "/_authed/settings/knowledge-bases/$kbId": typeof AuthedSettingsKnowledgeBasesKbIdRoute;
  "/_authed/settings/mcp-servers/$serverId": typeof AuthedSettingsMcpServersServerIdRoute;
  "/_authed/settings/memory/knowledge-bases": typeof AuthedSettingsMemoryKnowledgeBasesRoute;
  "/_authed/settings/memory/knowledge-graph": typeof AuthedSettingsMemoryKnowledgeGraphRoute;
  "/_authed/settings/memory/wiki": typeof AuthedSettingsMemoryWikiRoute;
  "/_authed/settings/routines/$routineId": typeof AuthedSettingsRoutinesRoutineIdRoute;
  "/_authed/settings/skills/$skillSlug": typeof AuthedSettingsSkillsSkillSlugRoute;
  "/_authed/settings/spaces/$spaceId": typeof AuthedSettingsSpacesSpaceIdRoute;
  "/_authed/settings/users/$userId": typeof AuthedSettingsUsersUserIdRoute;
  "/_authed/settings/webhooks/$webhookId": typeof AuthedSettingsWebhooksWebhookIdRoute;
  "/_authed/_shell/approvals/": typeof AuthedShellApprovalsIndexRoute;
  "/_authed/_shell/artifacts/": typeof AuthedShellArtifactsIndexRoute;
  "/_authed/_shell/automations/": typeof AuthedShellAutomationsIndexRoute;
  "/_authed/_shell/customize/": typeof AuthedShellCustomizeIndexRoute;
  "/_authed/_shell/memory/": typeof AuthedShellMemoryIndexRoute;
  "/_authed/_shell/spaces/": typeof AuthedShellSpacesIndexRoute;
  "/_authed/_shell/threads/": typeof AuthedShellThreadsIndexRoute;
  "/_authed/settings/agents/": typeof AuthedSettingsAgentsIndexRoute;
  "/_authed/settings/artifacts/": typeof AuthedSettingsArtifactsIndexRoute;
  "/_authed/settings/automations/": typeof AuthedSettingsAutomationsIndexRoute;
  "/_authed/settings/evaluations/": typeof AuthedSettingsEvaluationsIndexRoute;
  "/_authed/settings/knowledge-bases/": typeof AuthedSettingsKnowledgeBasesIndexRoute;
  "/_authed/settings/mcp-servers/": typeof AuthedSettingsMcpServersIndexRoute;
  "/_authed/settings/routines/": typeof AuthedSettingsRoutinesIndexRoute;
  "/_authed/settings/skills/": typeof AuthedSettingsSkillsIndexRoute;
  "/_authed/settings/spaces/": typeof AuthedSettingsSpacesIndexRoute;
  "/_authed/settings/users/": typeof AuthedSettingsUsersIndexRoute;
  "/_authed/settings/webhooks/": typeof AuthedSettingsWebhooksIndexRoute;
  "/_authed/_shell/memory/kbs/$kbId": typeof AuthedShellMemoryKbsKbIdRoute;
  "/_authed/settings/evaluations/studio/$testCaseId": typeof AuthedSettingsEvaluationsStudioTestCaseIdRoute;
  "/_authed/settings/evaluations/studio/new": typeof AuthedSettingsEvaluationsStudioNewRoute;
  "/_authed/settings/evaluations/studio/": typeof AuthedSettingsEvaluationsStudioIndexRoute;
  "/_authed/_shell/spaces/$spaceId/threads/$threadId": typeof AuthedShellSpacesSpaceIdThreadsThreadIdRoute;
  "/_authed/settings/evaluations/studio/edit/$testCaseId": typeof AuthedSettingsEvaluationsStudioEditTestCaseIdRoute;
  "/_authed/settings/routines/$routineId_/executions/$executionId": typeof AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/deployment-profile"
    | "/sign-in"
    | "/settings"
    | "/auth/callback"
    | "/auth/desktop-callback"
    | "/onboarding/welcome"
    | "/automations"
    | "/customize"
    | "/memory"
    | "/new"
    | "/settings/activity"
    | "/settings/analytics"
    | "/settings/artifacts"
    | "/settings/billing"
    | "/settings/crm"
    | "/settings/general"
    | "/settings/knowledge-graph"
    | "/settings/local-workspace"
    | "/settings/managed-applications"
    | "/settings/memory"
    | "/settings/model-catalog"
    | "/settings/tools"
    | "/settings/wiki"
    | "/settings/"
    | "/activity/$threadId"
    | "/approvals/$approvalId"
    | "/artifacts/$id"
    | "/automations/$scheduledJobId"
    | "/customize/skills"
    | "/customize/workflows"
    | "/memory/brain"
    | "/memory/kbs"
    | "/memory/pages"
    | "/spaces/$spaceId"
    | "/threads/$id"
    | "/settings/activity/$threadId"
    | "/settings/agents/$profileId"
    | "/settings/applications/cognee"
    | "/settings/applications/kestra"
    | "/settings/artifacts/$id"
    | "/settings/automations/$scheduledJobId"
    | "/settings/evaluations/$runId"
    | "/settings/knowledge-bases/$kbId"
    | "/settings/mcp-servers/$serverId"
    | "/settings/memory/knowledge-bases"
    | "/settings/memory/knowledge-graph"
    | "/settings/memory/wiki"
    | "/settings/routines/$routineId"
    | "/settings/skills/$skillSlug"
    | "/settings/spaces/$spaceId"
    | "/settings/users/$userId"
    | "/settings/webhooks/$webhookId"
    | "/approvals/"
    | "/artifacts/"
    | "/automations/"
    | "/customize/"
    | "/memory/"
    | "/spaces/"
    | "/threads/"
    | "/settings/agents/"
    | "/settings/artifacts/"
    | "/settings/automations/"
    | "/settings/evaluations/"
    | "/settings/knowledge-bases/"
    | "/settings/mcp-servers/"
    | "/settings/routines/"
    | "/settings/skills/"
    | "/settings/spaces/"
    | "/settings/users/"
    | "/settings/webhooks/"
    | "/memory/kbs/$kbId"
    | "/settings/evaluations/studio/$testCaseId"
    | "/settings/evaluations/studio/new"
    | "/settings/evaluations/studio/"
    | "/spaces/$spaceId/threads/$threadId"
    | "/settings/evaluations/studio/edit/$testCaseId"
    | "/settings/routines/$routineId/executions/$executionId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/deployment-profile"
    | "/sign-in"
    | "/auth/callback"
    | "/auth/desktop-callback"
    | "/onboarding/welcome"
    | "/new"
    | "/settings/activity"
    | "/settings/analytics"
    | "/settings/billing"
    | "/settings/crm"
    | "/settings/general"
    | "/settings/knowledge-graph"
    | "/settings/local-workspace"
    | "/settings/managed-applications"
    | "/settings/memory"
    | "/settings/model-catalog"
    | "/settings/tools"
    | "/settings/wiki"
    | "/settings"
    | "/activity/$threadId"
    | "/approvals/$approvalId"
    | "/artifacts/$id"
    | "/automations/$scheduledJobId"
    | "/customize/skills"
    | "/customize/workflows"
    | "/memory/brain"
    | "/memory/kbs"
    | "/memory/pages"
    | "/spaces/$spaceId"
    | "/threads/$id"
    | "/settings/activity/$threadId"
    | "/settings/agents/$profileId"
    | "/settings/applications/cognee"
    | "/settings/applications/kestra"
    | "/settings/artifacts/$id"
    | "/settings/automations/$scheduledJobId"
    | "/settings/evaluations/$runId"
    | "/settings/knowledge-bases/$kbId"
    | "/settings/mcp-servers/$serverId"
    | "/settings/memory/knowledge-bases"
    | "/settings/memory/knowledge-graph"
    | "/settings/memory/wiki"
    | "/settings/routines/$routineId"
    | "/settings/skills/$skillSlug"
    | "/settings/spaces/$spaceId"
    | "/settings/users/$userId"
    | "/settings/webhooks/$webhookId"
    | "/approvals"
    | "/artifacts"
    | "/automations"
    | "/customize"
    | "/memory"
    | "/spaces"
    | "/threads"
    | "/settings/agents"
    | "/settings/artifacts"
    | "/settings/automations"
    | "/settings/evaluations"
    | "/settings/knowledge-bases"
    | "/settings/mcp-servers"
    | "/settings/routines"
    | "/settings/skills"
    | "/settings/spaces"
    | "/settings/users"
    | "/settings/webhooks"
    | "/memory/kbs/$kbId"
    | "/settings/evaluations/studio/$testCaseId"
    | "/settings/evaluations/studio/new"
    | "/settings/evaluations/studio"
    | "/spaces/$spaceId/threads/$threadId"
    | "/settings/evaluations/studio/edit/$testCaseId"
    | "/settings/routines/$routineId/executions/$executionId";
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/_authed"
    | "/deployment-profile"
    | "/sign-in"
    | "/_authed/_shell"
    | "/_authed/settings"
    | "/auth/callback"
    | "/auth/desktop-callback"
    | "/onboarding/welcome"
    | "/_authed/_shell/automations"
    | "/_authed/_shell/customize"
    | "/_authed/_shell/memory"
    | "/_authed/_shell/new"
    | "/_authed/settings/activity"
    | "/_authed/settings/analytics"
    | "/_authed/settings/artifacts"
    | "/_authed/settings/billing"
    | "/_authed/settings/crm"
    | "/_authed/settings/general"
    | "/_authed/settings/knowledge-graph"
    | "/_authed/settings/local-workspace"
    | "/_authed/settings/managed-applications"
    | "/_authed/settings/memory"
    | "/_authed/settings/model-catalog"
    | "/_authed/settings/tools"
    | "/_authed/settings/wiki"
    | "/_authed/settings/"
    | "/_authed/_shell/activity/$threadId"
    | "/_authed/_shell/approvals/$approvalId"
    | "/_authed/_shell/artifacts/$id"
    | "/_authed/_shell/automations/$scheduledJobId"
    | "/_authed/_shell/customize/skills"
    | "/_authed/_shell/customize/workflows"
    | "/_authed/_shell/memory/brain"
    | "/_authed/_shell/memory/kbs"
    | "/_authed/_shell/memory/pages"
    | "/_authed/_shell/spaces/$spaceId"
    | "/_authed/_shell/threads/$id"
    | "/_authed/settings/activity_/$threadId"
    | "/_authed/settings/agents/$profileId"
    | "/_authed/settings/applications/cognee"
    | "/_authed/settings/applications/kestra"
    | "/_authed/settings/artifacts/$id"
    | "/_authed/settings/automations/$scheduledJobId"
    | "/_authed/settings/evaluations/$runId"
    | "/_authed/settings/knowledge-bases/$kbId"
    | "/_authed/settings/mcp-servers/$serverId"
    | "/_authed/settings/memory/knowledge-bases"
    | "/_authed/settings/memory/knowledge-graph"
    | "/_authed/settings/memory/wiki"
    | "/_authed/settings/routines/$routineId"
    | "/_authed/settings/skills/$skillSlug"
    | "/_authed/settings/spaces/$spaceId"
    | "/_authed/settings/users/$userId"
    | "/_authed/settings/webhooks/$webhookId"
    | "/_authed/_shell/approvals/"
    | "/_authed/_shell/artifacts/"
    | "/_authed/_shell/automations/"
    | "/_authed/_shell/customize/"
    | "/_authed/_shell/memory/"
    | "/_authed/_shell/spaces/"
    | "/_authed/_shell/threads/"
    | "/_authed/settings/agents/"
    | "/_authed/settings/artifacts/"
    | "/_authed/settings/automations/"
    | "/_authed/settings/evaluations/"
    | "/_authed/settings/knowledge-bases/"
    | "/_authed/settings/mcp-servers/"
    | "/_authed/settings/routines/"
    | "/_authed/settings/skills/"
    | "/_authed/settings/spaces/"
    | "/_authed/settings/users/"
    | "/_authed/settings/webhooks/"
    | "/_authed/_shell/memory/kbs/$kbId"
    | "/_authed/settings/evaluations/studio/$testCaseId"
    | "/_authed/settings/evaluations/studio/new"
    | "/_authed/settings/evaluations/studio/"
    | "/_authed/_shell/spaces/$spaceId/threads/$threadId"
    | "/_authed/settings/evaluations/studio/edit/$testCaseId"
    | "/_authed/settings/routines/$routineId_/executions/$executionId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  DeploymentProfileRoute: typeof DeploymentProfileRoute;
  SignInRoute: typeof SignInRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
  AuthDesktopCallbackRoute: typeof AuthDesktopCallbackRoute;
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/deployment-profile": {
      id: "/deployment-profile";
      path: "/deployment-profile";
      fullPath: "/deployment-profile";
      preLoaderRoute: typeof DeploymentProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/onboarding/welcome": {
      id: "/onboarding/welcome";
      path: "/onboarding/welcome";
      fullPath: "/onboarding/welcome";
      preLoaderRoute: typeof OnboardingWelcomeRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/desktop-callback": {
      id: "/auth/desktop-callback";
      path: "/auth/desktop-callback";
      fullPath: "/auth/desktop-callback";
      preLoaderRoute: typeof AuthDesktopCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/settings": {
      id: "/_authed/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof AuthedSettingsRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/_shell": {
      id: "/_authed/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedShellRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/settings/": {
      id: "/_authed/settings/";
      path: "/";
      fullPath: "/settings/";
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/wiki": {
      id: "/_authed/settings/wiki";
      path: "/wiki";
      fullPath: "/settings/wiki";
      preLoaderRoute: typeof AuthedSettingsWikiRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/tools": {
      id: "/_authed/settings/tools";
      path: "/tools";
      fullPath: "/settings/tools";
      preLoaderRoute: typeof AuthedSettingsToolsRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/model-catalog": {
      id: "/_authed/settings/model-catalog";
      path: "/model-catalog";
      fullPath: "/settings/model-catalog";
      preLoaderRoute: typeof AuthedSettingsModelCatalogRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/memory": {
      id: "/_authed/settings/memory";
      path: "/memory";
      fullPath: "/settings/memory";
      preLoaderRoute: typeof AuthedSettingsMemoryRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/managed-applications": {
      id: "/_authed/settings/managed-applications";
      path: "/managed-applications";
      fullPath: "/settings/managed-applications";
      preLoaderRoute: typeof AuthedSettingsManagedApplicationsRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/local-workspace": {
      id: "/_authed/settings/local-workspace";
      path: "/local-workspace";
      fullPath: "/settings/local-workspace";
      preLoaderRoute: typeof AuthedSettingsLocalWorkspaceRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/knowledge-graph": {
      id: "/_authed/settings/knowledge-graph";
      path: "/knowledge-graph";
      fullPath: "/settings/knowledge-graph";
      preLoaderRoute: typeof AuthedSettingsKnowledgeGraphRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/general": {
      id: "/_authed/settings/general";
      path: "/general";
      fullPath: "/settings/general";
      preLoaderRoute: typeof AuthedSettingsGeneralRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/crm": {
      id: "/_authed/settings/crm";
      path: "/crm";
      fullPath: "/settings/crm";
      preLoaderRoute: typeof AuthedSettingsCrmRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/billing": {
      id: "/_authed/settings/billing";
      path: "/billing";
      fullPath: "/settings/billing";
      preLoaderRoute: typeof AuthedSettingsBillingRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/artifacts": {
      id: "/_authed/settings/artifacts";
      path: "/artifacts";
      fullPath: "/settings/artifacts";
      preLoaderRoute: typeof AuthedSettingsArtifactsRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/analytics": {
      id: "/_authed/settings/analytics";
      path: "/analytics";
      fullPath: "/settings/analytics";
      preLoaderRoute: typeof AuthedSettingsAnalyticsRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/activity": {
      id: "/_authed/settings/activity";
      path: "/activity";
      fullPath: "/settings/activity";
      preLoaderRoute: typeof AuthedSettingsActivityRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/_shell/new": {
      id: "/_authed/_shell/new";
      path: "/new";
      fullPath: "/new";
      preLoaderRoute: typeof AuthedShellNewRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/memory": {
      id: "/_authed/_shell/memory";
      path: "/memory";
      fullPath: "/memory";
      preLoaderRoute: typeof AuthedShellMemoryRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/customize": {
      id: "/_authed/_shell/customize";
      path: "/customize";
      fullPath: "/customize";
      preLoaderRoute: typeof AuthedShellCustomizeRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/automations": {
      id: "/_authed/_shell/automations";
      path: "/automations";
      fullPath: "/automations";
      preLoaderRoute: typeof AuthedShellAutomationsRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/settings/webhooks/": {
      id: "/_authed/settings/webhooks/";
      path: "/webhooks";
      fullPath: "/settings/webhooks/";
      preLoaderRoute: typeof AuthedSettingsWebhooksIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/users/": {
      id: "/_authed/settings/users/";
      path: "/users";
      fullPath: "/settings/users/";
      preLoaderRoute: typeof AuthedSettingsUsersIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/spaces/": {
      id: "/_authed/settings/spaces/";
      path: "/spaces";
      fullPath: "/settings/spaces/";
      preLoaderRoute: typeof AuthedSettingsSpacesIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/skills/": {
      id: "/_authed/settings/skills/";
      path: "/skills";
      fullPath: "/settings/skills/";
      preLoaderRoute: typeof AuthedSettingsSkillsIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/routines/": {
      id: "/_authed/settings/routines/";
      path: "/routines";
      fullPath: "/settings/routines/";
      preLoaderRoute: typeof AuthedSettingsRoutinesIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/mcp-servers/": {
      id: "/_authed/settings/mcp-servers/";
      path: "/mcp-servers";
      fullPath: "/settings/mcp-servers/";
      preLoaderRoute: typeof AuthedSettingsMcpServersIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/knowledge-bases/": {
      id: "/_authed/settings/knowledge-bases/";
      path: "/knowledge-bases";
      fullPath: "/settings/knowledge-bases/";
      preLoaderRoute: typeof AuthedSettingsKnowledgeBasesIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/evaluations/": {
      id: "/_authed/settings/evaluations/";
      path: "/evaluations";
      fullPath: "/settings/evaluations/";
      preLoaderRoute: typeof AuthedSettingsEvaluationsIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/automations/": {
      id: "/_authed/settings/automations/";
      path: "/automations";
      fullPath: "/settings/automations/";
      preLoaderRoute: typeof AuthedSettingsAutomationsIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/artifacts/": {
      id: "/_authed/settings/artifacts/";
      path: "/";
      fullPath: "/settings/artifacts/";
      preLoaderRoute: typeof AuthedSettingsArtifactsIndexRouteImport;
      parentRoute: typeof AuthedSettingsArtifactsRoute;
    };
    "/_authed/settings/agents/": {
      id: "/_authed/settings/agents/";
      path: "/agents";
      fullPath: "/settings/agents/";
      preLoaderRoute: typeof AuthedSettingsAgentsIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/_shell/threads/": {
      id: "/_authed/_shell/threads/";
      path: "/threads";
      fullPath: "/threads/";
      preLoaderRoute: typeof AuthedShellThreadsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/spaces/": {
      id: "/_authed/_shell/spaces/";
      path: "/spaces";
      fullPath: "/spaces/";
      preLoaderRoute: typeof AuthedShellSpacesIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/memory/": {
      id: "/_authed/_shell/memory/";
      path: "/";
      fullPath: "/memory/";
      preLoaderRoute: typeof AuthedShellMemoryIndexRouteImport;
      parentRoute: typeof AuthedShellMemoryRoute;
    };
    "/_authed/_shell/customize/": {
      id: "/_authed/_shell/customize/";
      path: "/";
      fullPath: "/customize/";
      preLoaderRoute: typeof AuthedShellCustomizeIndexRouteImport;
      parentRoute: typeof AuthedShellCustomizeRoute;
    };
    "/_authed/_shell/automations/": {
      id: "/_authed/_shell/automations/";
      path: "/";
      fullPath: "/automations/";
      preLoaderRoute: typeof AuthedShellAutomationsIndexRouteImport;
      parentRoute: typeof AuthedShellAutomationsRoute;
    };
    "/_authed/_shell/artifacts/": {
      id: "/_authed/_shell/artifacts/";
      path: "/artifacts";
      fullPath: "/artifacts/";
      preLoaderRoute: typeof AuthedShellArtifactsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/approvals/": {
      id: "/_authed/_shell/approvals/";
      path: "/approvals";
      fullPath: "/approvals/";
      preLoaderRoute: typeof AuthedShellApprovalsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/settings/webhooks/$webhookId": {
      id: "/_authed/settings/webhooks/$webhookId";
      path: "/webhooks/$webhookId";
      fullPath: "/settings/webhooks/$webhookId";
      preLoaderRoute: typeof AuthedSettingsWebhooksWebhookIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/users/$userId": {
      id: "/_authed/settings/users/$userId";
      path: "/users/$userId";
      fullPath: "/settings/users/$userId";
      preLoaderRoute: typeof AuthedSettingsUsersUserIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/spaces/$spaceId": {
      id: "/_authed/settings/spaces/$spaceId";
      path: "/spaces/$spaceId";
      fullPath: "/settings/spaces/$spaceId";
      preLoaderRoute: typeof AuthedSettingsSpacesSpaceIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/skills/$skillSlug": {
      id: "/_authed/settings/skills/$skillSlug";
      path: "/skills/$skillSlug";
      fullPath: "/settings/skills/$skillSlug";
      preLoaderRoute: typeof AuthedSettingsSkillsSkillSlugRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/routines/$routineId": {
      id: "/_authed/settings/routines/$routineId";
      path: "/routines/$routineId";
      fullPath: "/settings/routines/$routineId";
      preLoaderRoute: typeof AuthedSettingsRoutinesRoutineIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/memory/wiki": {
      id: "/_authed/settings/memory/wiki";
      path: "/wiki";
      fullPath: "/settings/memory/wiki";
      preLoaderRoute: typeof AuthedSettingsMemoryWikiRouteImport;
      parentRoute: typeof AuthedSettingsMemoryRoute;
    };
    "/_authed/settings/memory/knowledge-graph": {
      id: "/_authed/settings/memory/knowledge-graph";
      path: "/knowledge-graph";
      fullPath: "/settings/memory/knowledge-graph";
      preLoaderRoute: typeof AuthedSettingsMemoryKnowledgeGraphRouteImport;
      parentRoute: typeof AuthedSettingsMemoryRoute;
    };
    "/_authed/settings/memory/knowledge-bases": {
      id: "/_authed/settings/memory/knowledge-bases";
      path: "/knowledge-bases";
      fullPath: "/settings/memory/knowledge-bases";
      preLoaderRoute: typeof AuthedSettingsMemoryKnowledgeBasesRouteImport;
      parentRoute: typeof AuthedSettingsMemoryRoute;
    };
    "/_authed/settings/mcp-servers/$serverId": {
      id: "/_authed/settings/mcp-servers/$serverId";
      path: "/mcp-servers/$serverId";
      fullPath: "/settings/mcp-servers/$serverId";
      preLoaderRoute: typeof AuthedSettingsMcpServersServerIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/knowledge-bases/$kbId": {
      id: "/_authed/settings/knowledge-bases/$kbId";
      path: "/knowledge-bases/$kbId";
      fullPath: "/settings/knowledge-bases/$kbId";
      preLoaderRoute: typeof AuthedSettingsKnowledgeBasesKbIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/evaluations/$runId": {
      id: "/_authed/settings/evaluations/$runId";
      path: "/evaluations/$runId";
      fullPath: "/settings/evaluations/$runId";
      preLoaderRoute: typeof AuthedSettingsEvaluationsRunIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/automations/$scheduledJobId": {
      id: "/_authed/settings/automations/$scheduledJobId";
      path: "/automations/$scheduledJobId";
      fullPath: "/settings/automations/$scheduledJobId";
      preLoaderRoute: typeof AuthedSettingsAutomationsScheduledJobIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/artifacts/$id": {
      id: "/_authed/settings/artifacts/$id";
      path: "/$id";
      fullPath: "/settings/artifacts/$id";
      preLoaderRoute: typeof AuthedSettingsArtifactsIdRouteImport;
      parentRoute: typeof AuthedSettingsArtifactsRoute;
    };
    "/_authed/settings/applications/kestra": {
      id: "/_authed/settings/applications/kestra";
      path: "/applications/kestra";
      fullPath: "/settings/applications/kestra";
      preLoaderRoute: typeof AuthedSettingsApplicationsKestraRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/applications/cognee": {
      id: "/_authed/settings/applications/cognee";
      path: "/applications/cognee";
      fullPath: "/settings/applications/cognee";
      preLoaderRoute: typeof AuthedSettingsApplicationsCogneeRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/agents/$profileId": {
      id: "/_authed/settings/agents/$profileId";
      path: "/agents/$profileId";
      fullPath: "/settings/agents/$profileId";
      preLoaderRoute: typeof AuthedSettingsAgentsProfileIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/activity_/$threadId": {
      id: "/_authed/settings/activity_/$threadId";
      path: "/activity/$threadId";
      fullPath: "/settings/activity/$threadId";
      preLoaderRoute: typeof AuthedSettingsActivityThreadIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/_shell/threads/$id": {
      id: "/_authed/_shell/threads/$id";
      path: "/threads/$id";
      fullPath: "/threads/$id";
      preLoaderRoute: typeof AuthedShellThreadsIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/spaces/$spaceId": {
      id: "/_authed/_shell/spaces/$spaceId";
      path: "/spaces/$spaceId";
      fullPath: "/spaces/$spaceId";
      preLoaderRoute: typeof AuthedShellSpacesSpaceIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/memory/pages": {
      id: "/_authed/_shell/memory/pages";
      path: "/pages";
      fullPath: "/memory/pages";
      preLoaderRoute: typeof AuthedShellMemoryPagesRouteImport;
      parentRoute: typeof AuthedShellMemoryRoute;
    };
    "/_authed/_shell/memory/kbs": {
      id: "/_authed/_shell/memory/kbs";
      path: "/kbs";
      fullPath: "/memory/kbs";
      preLoaderRoute: typeof AuthedShellMemoryKbsRouteImport;
      parentRoute: typeof AuthedShellMemoryRoute;
    };
    "/_authed/_shell/memory/brain": {
      id: "/_authed/_shell/memory/brain";
      path: "/brain";
      fullPath: "/memory/brain";
      preLoaderRoute: typeof AuthedShellMemoryBrainRouteImport;
      parentRoute: typeof AuthedShellMemoryRoute;
    };
    "/_authed/_shell/customize/workflows": {
      id: "/_authed/_shell/customize/workflows";
      path: "/workflows";
      fullPath: "/customize/workflows";
      preLoaderRoute: typeof AuthedShellCustomizeWorkflowsRouteImport;
      parentRoute: typeof AuthedShellCustomizeRoute;
    };
    "/_authed/_shell/customize/skills": {
      id: "/_authed/_shell/customize/skills";
      path: "/skills";
      fullPath: "/customize/skills";
      preLoaderRoute: typeof AuthedShellCustomizeSkillsRouteImport;
      parentRoute: typeof AuthedShellCustomizeRoute;
    };
    "/_authed/_shell/automations/$scheduledJobId": {
      id: "/_authed/_shell/automations/$scheduledJobId";
      path: "/$scheduledJobId";
      fullPath: "/automations/$scheduledJobId";
      preLoaderRoute: typeof AuthedShellAutomationsScheduledJobIdRouteImport;
      parentRoute: typeof AuthedShellAutomationsRoute;
    };
    "/_authed/_shell/artifacts/$id": {
      id: "/_authed/_shell/artifacts/$id";
      path: "/artifacts/$id";
      fullPath: "/artifacts/$id";
      preLoaderRoute: typeof AuthedShellArtifactsIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/approvals/$approvalId": {
      id: "/_authed/_shell/approvals/$approvalId";
      path: "/approvals/$approvalId";
      fullPath: "/approvals/$approvalId";
      preLoaderRoute: typeof AuthedShellApprovalsApprovalIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/activity/$threadId": {
      id: "/_authed/_shell/activity/$threadId";
      path: "/activity/$threadId";
      fullPath: "/activity/$threadId";
      preLoaderRoute: typeof AuthedShellActivityThreadIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/settings/evaluations/studio/": {
      id: "/_authed/settings/evaluations/studio/";
      path: "/evaluations/studio";
      fullPath: "/settings/evaluations/studio/";
      preLoaderRoute: typeof AuthedSettingsEvaluationsStudioIndexRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/evaluations/studio/new": {
      id: "/_authed/settings/evaluations/studio/new";
      path: "/evaluations/studio/new";
      fullPath: "/settings/evaluations/studio/new";
      preLoaderRoute: typeof AuthedSettingsEvaluationsStudioNewRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/evaluations/studio/$testCaseId": {
      id: "/_authed/settings/evaluations/studio/$testCaseId";
      path: "/evaluations/studio/$testCaseId";
      fullPath: "/settings/evaluations/studio/$testCaseId";
      preLoaderRoute: typeof AuthedSettingsEvaluationsStudioTestCaseIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/_shell/memory/kbs/$kbId": {
      id: "/_authed/_shell/memory/kbs/$kbId";
      path: "/$kbId";
      fullPath: "/memory/kbs/$kbId";
      preLoaderRoute: typeof AuthedShellMemoryKbsKbIdRouteImport;
      parentRoute: typeof AuthedShellMemoryKbsRoute;
    };
    "/_authed/settings/routines/$routineId_/executions/$executionId": {
      id: "/_authed/settings/routines/$routineId_/executions/$executionId";
      path: "/routines/$routineId/executions/$executionId";
      fullPath: "/settings/routines/$routineId/executions/$executionId";
      preLoaderRoute: typeof AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/settings/evaluations/studio/edit/$testCaseId": {
      id: "/_authed/settings/evaluations/studio/edit/$testCaseId";
      path: "/evaluations/studio/edit/$testCaseId";
      fullPath: "/settings/evaluations/studio/edit/$testCaseId";
      preLoaderRoute: typeof AuthedSettingsEvaluationsStudioEditTestCaseIdRouteImport;
      parentRoute: typeof AuthedSettingsRoute;
    };
    "/_authed/_shell/spaces/$spaceId/threads/$threadId": {
      id: "/_authed/_shell/spaces/$spaceId/threads/$threadId";
      path: "/threads/$threadId";
      fullPath: "/spaces/$spaceId/threads/$threadId";
      preLoaderRoute: typeof AuthedShellSpacesSpaceIdThreadsThreadIdRouteImport;
      parentRoute: typeof AuthedShellSpacesSpaceIdRoute;
    };
  }
}

interface AuthedShellAutomationsRouteChildren {
  AuthedShellAutomationsScheduledJobIdRoute: typeof AuthedShellAutomationsScheduledJobIdRoute;
  AuthedShellAutomationsIndexRoute: typeof AuthedShellAutomationsIndexRoute;
}

const AuthedShellAutomationsRouteChildren: AuthedShellAutomationsRouteChildren =
  {
    AuthedShellAutomationsScheduledJobIdRoute:
      AuthedShellAutomationsScheduledJobIdRoute,
    AuthedShellAutomationsIndexRoute: AuthedShellAutomationsIndexRoute,
  };

const AuthedShellAutomationsRouteWithChildren =
  AuthedShellAutomationsRoute._addFileChildren(
    AuthedShellAutomationsRouteChildren,
  );

interface AuthedShellCustomizeRouteChildren {
  AuthedShellCustomizeSkillsRoute: typeof AuthedShellCustomizeSkillsRoute;
  AuthedShellCustomizeWorkflowsRoute: typeof AuthedShellCustomizeWorkflowsRoute;
  AuthedShellCustomizeIndexRoute: typeof AuthedShellCustomizeIndexRoute;
}

const AuthedShellCustomizeRouteChildren: AuthedShellCustomizeRouteChildren = {
  AuthedShellCustomizeSkillsRoute: AuthedShellCustomizeSkillsRoute,
  AuthedShellCustomizeWorkflowsRoute: AuthedShellCustomizeWorkflowsRoute,
  AuthedShellCustomizeIndexRoute: AuthedShellCustomizeIndexRoute,
};

const AuthedShellCustomizeRouteWithChildren =
  AuthedShellCustomizeRoute._addFileChildren(AuthedShellCustomizeRouteChildren);

interface AuthedShellMemoryKbsRouteChildren {
  AuthedShellMemoryKbsKbIdRoute: typeof AuthedShellMemoryKbsKbIdRoute;
}

const AuthedShellMemoryKbsRouteChildren: AuthedShellMemoryKbsRouteChildren = {
  AuthedShellMemoryKbsKbIdRoute: AuthedShellMemoryKbsKbIdRoute,
};

const AuthedShellMemoryKbsRouteWithChildren =
  AuthedShellMemoryKbsRoute._addFileChildren(AuthedShellMemoryKbsRouteChildren);

interface AuthedShellMemoryRouteChildren {
  AuthedShellMemoryBrainRoute: typeof AuthedShellMemoryBrainRoute;
  AuthedShellMemoryKbsRoute: typeof AuthedShellMemoryKbsRouteWithChildren;
  AuthedShellMemoryPagesRoute: typeof AuthedShellMemoryPagesRoute;
  AuthedShellMemoryIndexRoute: typeof AuthedShellMemoryIndexRoute;
}

const AuthedShellMemoryRouteChildren: AuthedShellMemoryRouteChildren = {
  AuthedShellMemoryBrainRoute: AuthedShellMemoryBrainRoute,
  AuthedShellMemoryKbsRoute: AuthedShellMemoryKbsRouteWithChildren,
  AuthedShellMemoryPagesRoute: AuthedShellMemoryPagesRoute,
  AuthedShellMemoryIndexRoute: AuthedShellMemoryIndexRoute,
};

const AuthedShellMemoryRouteWithChildren =
  AuthedShellMemoryRoute._addFileChildren(AuthedShellMemoryRouteChildren);

interface AuthedShellSpacesSpaceIdRouteChildren {
  AuthedShellSpacesSpaceIdThreadsThreadIdRoute: typeof AuthedShellSpacesSpaceIdThreadsThreadIdRoute;
}

const AuthedShellSpacesSpaceIdRouteChildren: AuthedShellSpacesSpaceIdRouteChildren =
  {
    AuthedShellSpacesSpaceIdThreadsThreadIdRoute:
      AuthedShellSpacesSpaceIdThreadsThreadIdRoute,
  };

const AuthedShellSpacesSpaceIdRouteWithChildren =
  AuthedShellSpacesSpaceIdRoute._addFileChildren(
    AuthedShellSpacesSpaceIdRouteChildren,
  );

interface AuthedShellRouteChildren {
  AuthedShellAutomationsRoute: typeof AuthedShellAutomationsRouteWithChildren;
  AuthedShellCustomizeRoute: typeof AuthedShellCustomizeRouteWithChildren;
  AuthedShellMemoryRoute: typeof AuthedShellMemoryRouteWithChildren;
  AuthedShellNewRoute: typeof AuthedShellNewRoute;
  AuthedShellActivityThreadIdRoute: typeof AuthedShellActivityThreadIdRoute;
  AuthedShellApprovalsApprovalIdRoute: typeof AuthedShellApprovalsApprovalIdRoute;
  AuthedShellArtifactsIdRoute: typeof AuthedShellArtifactsIdRoute;
  AuthedShellSpacesSpaceIdRoute: typeof AuthedShellSpacesSpaceIdRouteWithChildren;
  AuthedShellThreadsIdRoute: typeof AuthedShellThreadsIdRoute;
  AuthedShellApprovalsIndexRoute: typeof AuthedShellApprovalsIndexRoute;
  AuthedShellArtifactsIndexRoute: typeof AuthedShellArtifactsIndexRoute;
  AuthedShellSpacesIndexRoute: typeof AuthedShellSpacesIndexRoute;
  AuthedShellThreadsIndexRoute: typeof AuthedShellThreadsIndexRoute;
}

const AuthedShellRouteChildren: AuthedShellRouteChildren = {
  AuthedShellAutomationsRoute: AuthedShellAutomationsRouteWithChildren,
  AuthedShellCustomizeRoute: AuthedShellCustomizeRouteWithChildren,
  AuthedShellMemoryRoute: AuthedShellMemoryRouteWithChildren,
  AuthedShellNewRoute: AuthedShellNewRoute,
  AuthedShellActivityThreadIdRoute: AuthedShellActivityThreadIdRoute,
  AuthedShellApprovalsApprovalIdRoute: AuthedShellApprovalsApprovalIdRoute,
  AuthedShellArtifactsIdRoute: AuthedShellArtifactsIdRoute,
  AuthedShellSpacesSpaceIdRoute: AuthedShellSpacesSpaceIdRouteWithChildren,
  AuthedShellThreadsIdRoute: AuthedShellThreadsIdRoute,
  AuthedShellApprovalsIndexRoute: AuthedShellApprovalsIndexRoute,
  AuthedShellArtifactsIndexRoute: AuthedShellArtifactsIndexRoute,
  AuthedShellSpacesIndexRoute: AuthedShellSpacesIndexRoute,
  AuthedShellThreadsIndexRoute: AuthedShellThreadsIndexRoute,
};

const AuthedShellRouteWithChildren = AuthedShellRoute._addFileChildren(
  AuthedShellRouteChildren,
);

interface AuthedSettingsArtifactsRouteChildren {
  AuthedSettingsArtifactsIdRoute: typeof AuthedSettingsArtifactsIdRoute;
  AuthedSettingsArtifactsIndexRoute: typeof AuthedSettingsArtifactsIndexRoute;
}

const AuthedSettingsArtifactsRouteChildren: AuthedSettingsArtifactsRouteChildren =
  {
    AuthedSettingsArtifactsIdRoute: AuthedSettingsArtifactsIdRoute,
    AuthedSettingsArtifactsIndexRoute: AuthedSettingsArtifactsIndexRoute,
  };

const AuthedSettingsArtifactsRouteWithChildren =
  AuthedSettingsArtifactsRoute._addFileChildren(
    AuthedSettingsArtifactsRouteChildren,
  );

interface AuthedSettingsMemoryRouteChildren {
  AuthedSettingsMemoryKnowledgeBasesRoute: typeof AuthedSettingsMemoryKnowledgeBasesRoute;
  AuthedSettingsMemoryKnowledgeGraphRoute: typeof AuthedSettingsMemoryKnowledgeGraphRoute;
  AuthedSettingsMemoryWikiRoute: typeof AuthedSettingsMemoryWikiRoute;
}

const AuthedSettingsMemoryRouteChildren: AuthedSettingsMemoryRouteChildren = {
  AuthedSettingsMemoryKnowledgeBasesRoute:
    AuthedSettingsMemoryKnowledgeBasesRoute,
  AuthedSettingsMemoryKnowledgeGraphRoute:
    AuthedSettingsMemoryKnowledgeGraphRoute,
  AuthedSettingsMemoryWikiRoute: AuthedSettingsMemoryWikiRoute,
};

const AuthedSettingsMemoryRouteWithChildren =
  AuthedSettingsMemoryRoute._addFileChildren(AuthedSettingsMemoryRouteChildren);

interface AuthedSettingsRouteChildren {
  AuthedSettingsActivityRoute: typeof AuthedSettingsActivityRoute;
  AuthedSettingsAnalyticsRoute: typeof AuthedSettingsAnalyticsRoute;
  AuthedSettingsArtifactsRoute: typeof AuthedSettingsArtifactsRouteWithChildren;
  AuthedSettingsBillingRoute: typeof AuthedSettingsBillingRoute;
  AuthedSettingsCrmRoute: typeof AuthedSettingsCrmRoute;
  AuthedSettingsGeneralRoute: typeof AuthedSettingsGeneralRoute;
  AuthedSettingsKnowledgeGraphRoute: typeof AuthedSettingsKnowledgeGraphRoute;
  AuthedSettingsLocalWorkspaceRoute: typeof AuthedSettingsLocalWorkspaceRoute;
  AuthedSettingsManagedApplicationsRoute: typeof AuthedSettingsManagedApplicationsRoute;
  AuthedSettingsMemoryRoute: typeof AuthedSettingsMemoryRouteWithChildren;
  AuthedSettingsModelCatalogRoute: typeof AuthedSettingsModelCatalogRoute;
  AuthedSettingsToolsRoute: typeof AuthedSettingsToolsRoute;
  AuthedSettingsWikiRoute: typeof AuthedSettingsWikiRoute;
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute;
  AuthedSettingsActivityThreadIdRoute: typeof AuthedSettingsActivityThreadIdRoute;
  AuthedSettingsAgentsProfileIdRoute: typeof AuthedSettingsAgentsProfileIdRoute;
  AuthedSettingsApplicationsCogneeRoute: typeof AuthedSettingsApplicationsCogneeRoute;
  AuthedSettingsApplicationsKestraRoute: typeof AuthedSettingsApplicationsKestraRoute;
  AuthedSettingsAutomationsScheduledJobIdRoute: typeof AuthedSettingsAutomationsScheduledJobIdRoute;
  AuthedSettingsEvaluationsRunIdRoute: typeof AuthedSettingsEvaluationsRunIdRoute;
  AuthedSettingsKnowledgeBasesKbIdRoute: typeof AuthedSettingsKnowledgeBasesKbIdRoute;
  AuthedSettingsMcpServersServerIdRoute: typeof AuthedSettingsMcpServersServerIdRoute;
  AuthedSettingsRoutinesRoutineIdRoute: typeof AuthedSettingsRoutinesRoutineIdRoute;
  AuthedSettingsSkillsSkillSlugRoute: typeof AuthedSettingsSkillsSkillSlugRoute;
  AuthedSettingsSpacesSpaceIdRoute: typeof AuthedSettingsSpacesSpaceIdRoute;
  AuthedSettingsUsersUserIdRoute: typeof AuthedSettingsUsersUserIdRoute;
  AuthedSettingsWebhooksWebhookIdRoute: typeof AuthedSettingsWebhooksWebhookIdRoute;
  AuthedSettingsAgentsIndexRoute: typeof AuthedSettingsAgentsIndexRoute;
  AuthedSettingsAutomationsIndexRoute: typeof AuthedSettingsAutomationsIndexRoute;
  AuthedSettingsEvaluationsIndexRoute: typeof AuthedSettingsEvaluationsIndexRoute;
  AuthedSettingsKnowledgeBasesIndexRoute: typeof AuthedSettingsKnowledgeBasesIndexRoute;
  AuthedSettingsMcpServersIndexRoute: typeof AuthedSettingsMcpServersIndexRoute;
  AuthedSettingsRoutinesIndexRoute: typeof AuthedSettingsRoutinesIndexRoute;
  AuthedSettingsSkillsIndexRoute: typeof AuthedSettingsSkillsIndexRoute;
  AuthedSettingsSpacesIndexRoute: typeof AuthedSettingsSpacesIndexRoute;
  AuthedSettingsUsersIndexRoute: typeof AuthedSettingsUsersIndexRoute;
  AuthedSettingsWebhooksIndexRoute: typeof AuthedSettingsWebhooksIndexRoute;
  AuthedSettingsEvaluationsStudioTestCaseIdRoute: typeof AuthedSettingsEvaluationsStudioTestCaseIdRoute;
  AuthedSettingsEvaluationsStudioNewRoute: typeof AuthedSettingsEvaluationsStudioNewRoute;
  AuthedSettingsEvaluationsStudioIndexRoute: typeof AuthedSettingsEvaluationsStudioIndexRoute;
  AuthedSettingsEvaluationsStudioEditTestCaseIdRoute: typeof AuthedSettingsEvaluationsStudioEditTestCaseIdRoute;
  AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRoute: typeof AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRoute;
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsActivityRoute: AuthedSettingsActivityRoute,
  AuthedSettingsAnalyticsRoute: AuthedSettingsAnalyticsRoute,
  AuthedSettingsArtifactsRoute: AuthedSettingsArtifactsRouteWithChildren,
  AuthedSettingsBillingRoute: AuthedSettingsBillingRoute,
  AuthedSettingsCrmRoute: AuthedSettingsCrmRoute,
  AuthedSettingsGeneralRoute: AuthedSettingsGeneralRoute,
  AuthedSettingsKnowledgeGraphRoute: AuthedSettingsKnowledgeGraphRoute,
  AuthedSettingsLocalWorkspaceRoute: AuthedSettingsLocalWorkspaceRoute,
  AuthedSettingsManagedApplicationsRoute:
    AuthedSettingsManagedApplicationsRoute,
  AuthedSettingsMemoryRoute: AuthedSettingsMemoryRouteWithChildren,
  AuthedSettingsModelCatalogRoute: AuthedSettingsModelCatalogRoute,
  AuthedSettingsToolsRoute: AuthedSettingsToolsRoute,
  AuthedSettingsWikiRoute: AuthedSettingsWikiRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsActivityThreadIdRoute: AuthedSettingsActivityThreadIdRoute,
  AuthedSettingsAgentsProfileIdRoute: AuthedSettingsAgentsProfileIdRoute,
  AuthedSettingsApplicationsCogneeRoute: AuthedSettingsApplicationsCogneeRoute,
  AuthedSettingsApplicationsKestraRoute: AuthedSettingsApplicationsKestraRoute,
  AuthedSettingsAutomationsScheduledJobIdRoute:
    AuthedSettingsAutomationsScheduledJobIdRoute,
  AuthedSettingsEvaluationsRunIdRoute: AuthedSettingsEvaluationsRunIdRoute,
  AuthedSettingsKnowledgeBasesKbIdRoute: AuthedSettingsKnowledgeBasesKbIdRoute,
  AuthedSettingsMcpServersServerIdRoute: AuthedSettingsMcpServersServerIdRoute,
  AuthedSettingsRoutinesRoutineIdRoute: AuthedSettingsRoutinesRoutineIdRoute,
  AuthedSettingsSkillsSkillSlugRoute: AuthedSettingsSkillsSkillSlugRoute,
  AuthedSettingsSpacesSpaceIdRoute: AuthedSettingsSpacesSpaceIdRoute,
  AuthedSettingsUsersUserIdRoute: AuthedSettingsUsersUserIdRoute,
  AuthedSettingsWebhooksWebhookIdRoute: AuthedSettingsWebhooksWebhookIdRoute,
  AuthedSettingsAgentsIndexRoute: AuthedSettingsAgentsIndexRoute,
  AuthedSettingsAutomationsIndexRoute: AuthedSettingsAutomationsIndexRoute,
  AuthedSettingsEvaluationsIndexRoute: AuthedSettingsEvaluationsIndexRoute,
  AuthedSettingsKnowledgeBasesIndexRoute:
    AuthedSettingsKnowledgeBasesIndexRoute,
  AuthedSettingsMcpServersIndexRoute: AuthedSettingsMcpServersIndexRoute,
  AuthedSettingsRoutinesIndexRoute: AuthedSettingsRoutinesIndexRoute,
  AuthedSettingsSkillsIndexRoute: AuthedSettingsSkillsIndexRoute,
  AuthedSettingsSpacesIndexRoute: AuthedSettingsSpacesIndexRoute,
  AuthedSettingsUsersIndexRoute: AuthedSettingsUsersIndexRoute,
  AuthedSettingsWebhooksIndexRoute: AuthedSettingsWebhooksIndexRoute,
  AuthedSettingsEvaluationsStudioTestCaseIdRoute:
    AuthedSettingsEvaluationsStudioTestCaseIdRoute,
  AuthedSettingsEvaluationsStudioNewRoute:
    AuthedSettingsEvaluationsStudioNewRoute,
  AuthedSettingsEvaluationsStudioIndexRoute:
    AuthedSettingsEvaluationsStudioIndexRoute,
  AuthedSettingsEvaluationsStudioEditTestCaseIdRoute:
    AuthedSettingsEvaluationsStudioEditTestCaseIdRoute,
  AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRoute:
    AuthedSettingsRoutinesRoutineIdExecutionsExecutionIdRoute,
};

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
);

interface AuthedRouteChildren {
  AuthedShellRoute: typeof AuthedShellRouteWithChildren;
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedShellRoute: AuthedShellRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DeploymentProfileRoute: DeploymentProfileRoute,
  SignInRoute: SignInRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthDesktopCallbackRoute: AuthDesktopCallbackRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
