/**
 * The iOS app icon must have NO alpha channel.
 *
 * Apple rejects a 1024x1024 marketing icon that carries transparency, and the
 * failure is silent in the worst way: the build uploads, TestFlight works, and
 * App Store Connect just shows the grey placeholder grid where the icon should
 * be. That is what happened on 2026-08-07 — `assets/icon.png` was RGBA with a
 * fully-opaque alpha channel, so it looked correct everywhere except the one
 * place that matters.
 *
 * `ios/` is gitignored and regenerated by `expo prebuild` from the `icon`
 * field in app.json, and prebuild does NOT strip the channel — so this asset
 * is the only place the rule can be enforced.
 *
 * Android's adaptive icon is deliberately NOT checked: its foreground layer
 * needs transparency to be masked correctly.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

/** PNG colour types that carry an alpha channel (IHDR byte 25). */
const COLOUR_TYPE_GREY_ALPHA = 4;
const COLOUR_TYPE_RGBA = 6;

function readPng(path: string) {
  const buf = readFileSync(new URL(`../${path}`, import.meta.url));
  // IHDR is the first chunk: 8-byte signature, 4-byte length, 4-byte type,
  // then width(4) height(4) bitDepth(1) colourType(1).
  return {
    width: buf.readUInt32BE(16),
    height: buf.readUInt32BE(20),
    colourType: buf[25],
    // A palette image can still be transparent via a tRNS chunk.
    hasTrns: buf.includes(Buffer.from("tRNS")),
  };
}

describe("iOS app icon", () => {
  it("is 1024x1024 with no alpha channel", () => {
    const png = readPng("assets/icon.png");
    expect(png.width).toBe(1024);
    expect(png.height).toBe(1024);
    expect([COLOUR_TYPE_GREY_ALPHA, COLOUR_TYPE_RGBA]).not.toContain(
      png.colourType,
    );
    expect(png.hasTrns).toBe(false);
  });
});
