/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthCallbackRouteImport } from "./routes/auth/callback";
import { Route as AuthedShellRouteImport } from "./routes/_authed/_shell";
import { Route as AuthedShellMemoryRouteImport } from "./routes/_authed/_shell/memory";
import { Route as AuthedShellInboxRouteImport } from "./routes/_authed/_shell/inbox";
import { Route as AuthedShellCustomizeRouteImport } from "./routes/_authed/_shell/customize";
import { Route as AuthedShellComputerRouteImport } from "./routes/_authed/_shell/computer";
import { Route as AuthedShellAutomationsRouteImport } from "./routes/_authed/_shell/automations";
import { Route as AuthedShellThreadsIndexRouteImport } from "./routes/_authed/_shell/threads.index";
import { Route as AuthedShellAppsIndexRouteImport } from "./routes/_authed/_shell/apps.index";
import { Route as AuthedShellApprovalsIndexRouteImport } from "./routes/_authed/_shell/approvals.index";
import { Route as AuthedShellThreadsIdRouteImport } from "./routes/_authed/_shell/threads.$id";
import { Route as AuthedShellAppsIdRouteImport } from "./routes/_authed/_shell/apps.$id";
import { Route as AuthedShellApprovalsApprovalIdRouteImport } from "./routes/_authed/_shell/approvals.$approvalId";

const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedShellRoute = AuthedShellRouteImport.update({
  id: "/_shell",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedShellMemoryRoute = AuthedShellMemoryRouteImport.update({
  id: "/memory",
  path: "/memory",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellInboxRoute = AuthedShellInboxRouteImport.update({
  id: "/inbox",
  path: "/inbox",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellCustomizeRoute = AuthedShellCustomizeRouteImport.update({
  id: "/customize",
  path: "/customize",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellComputerRoute = AuthedShellComputerRouteImport.update({
  id: "/computer",
  path: "/computer",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellAutomationsRoute = AuthedShellAutomationsRouteImport.update({
  id: "/automations",
  path: "/automations",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellThreadsIndexRoute = AuthedShellThreadsIndexRouteImport.update({
  id: "/threads/",
  path: "/threads/",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellAppsIndexRoute = AuthedShellAppsIndexRouteImport.update({
  id: "/apps/",
  path: "/apps/",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellApprovalsIndexRoute =
  AuthedShellApprovalsIndexRouteImport.update({
    id: "/approvals/",
    path: "/approvals/",
    getParentRoute: () => AuthedShellRoute,
  } as any);
const AuthedShellThreadsIdRoute = AuthedShellThreadsIdRouteImport.update({
  id: "/threads/$id",
  path: "/threads/$id",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellAppsIdRoute = AuthedShellAppsIdRouteImport.update({
  id: "/apps/$id",
  path: "/apps/$id",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellApprovalsApprovalIdRoute =
  AuthedShellApprovalsApprovalIdRouteImport.update({
    id: "/approvals/$approvalId",
    path: "/approvals/$approvalId",
    getParentRoute: () => AuthedShellRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/sign-in": typeof SignInRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/automations": typeof AuthedShellAutomationsRoute;
  "/computer": typeof AuthedShellComputerRoute;
  "/customize": typeof AuthedShellCustomizeRoute;
  "/inbox": typeof AuthedShellInboxRoute;
  "/memory": typeof AuthedShellMemoryRoute;
  "/approvals/$approvalId": typeof AuthedShellApprovalsApprovalIdRoute;
  "/apps/$id": typeof AuthedShellAppsIdRoute;
  "/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/approvals/": typeof AuthedShellApprovalsIndexRoute;
  "/apps/": typeof AuthedShellAppsIndexRoute;
  "/threads/": typeof AuthedShellThreadsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/sign-in": typeof SignInRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/automations": typeof AuthedShellAutomationsRoute;
  "/computer": typeof AuthedShellComputerRoute;
  "/customize": typeof AuthedShellCustomizeRoute;
  "/inbox": typeof AuthedShellInboxRoute;
  "/memory": typeof AuthedShellMemoryRoute;
  "/approvals/$approvalId": typeof AuthedShellApprovalsApprovalIdRoute;
  "/apps/$id": typeof AuthedShellAppsIdRoute;
  "/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/approvals": typeof AuthedShellApprovalsIndexRoute;
  "/apps": typeof AuthedShellAppsIndexRoute;
  "/threads": typeof AuthedShellThreadsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/sign-in": typeof SignInRoute;
  "/_authed/_shell": typeof AuthedShellRouteWithChildren;
  "/auth/callback": typeof AuthCallbackRoute;
  "/_authed/_shell/automations": typeof AuthedShellAutomationsRoute;
  "/_authed/_shell/computer": typeof AuthedShellComputerRoute;
  "/_authed/_shell/customize": typeof AuthedShellCustomizeRoute;
  "/_authed/_shell/inbox": typeof AuthedShellInboxRoute;
  "/_authed/_shell/memory": typeof AuthedShellMemoryRoute;
  "/_authed/_shell/approvals/$approvalId": typeof AuthedShellApprovalsApprovalIdRoute;
  "/_authed/_shell/apps/$id": typeof AuthedShellAppsIdRoute;
  "/_authed/_shell/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/_authed/_shell/approvals/": typeof AuthedShellApprovalsIndexRoute;
  "/_authed/_shell/apps/": typeof AuthedShellAppsIndexRoute;
  "/_authed/_shell/threads/": typeof AuthedShellThreadsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/sign-in"
    | "/auth/callback"
    | "/automations"
    | "/computer"
    | "/customize"
    | "/inbox"
    | "/memory"
    | "/approvals/$approvalId"
    | "/apps/$id"
    | "/threads/$id"
    | "/approvals/"
    | "/apps/"
    | "/threads/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/sign-in"
    | "/auth/callback"
    | "/automations"
    | "/computer"
    | "/customize"
    | "/inbox"
    | "/memory"
    | "/approvals/$approvalId"
    | "/apps/$id"
    | "/threads/$id"
    | "/approvals"
    | "/apps"
    | "/threads";
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/_authed"
    | "/sign-in"
    | "/_authed/_shell"
    | "/auth/callback"
    | "/_authed/_shell/automations"
    | "/_authed/_shell/computer"
    | "/_authed/_shell/customize"
    | "/_authed/_shell/inbox"
    | "/_authed/_shell/memory"
    | "/_authed/_shell/approvals/$approvalId"
    | "/_authed/_shell/apps/$id"
    | "/_authed/_shell/threads/$id"
    | "/_authed/_shell/approvals/"
    | "/_authed/_shell/apps/"
    | "/_authed/_shell/threads/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  SignInRoute: typeof SignInRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/_shell": {
      id: "/_authed/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedShellRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/_shell/memory": {
      id: "/_authed/_shell/memory";
      path: "/memory";
      fullPath: "/memory";
      preLoaderRoute: typeof AuthedShellMemoryRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/inbox": {
      id: "/_authed/_shell/inbox";
      path: "/inbox";
      fullPath: "/inbox";
      preLoaderRoute: typeof AuthedShellInboxRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/customize": {
      id: "/_authed/_shell/customize";
      path: "/customize";
      fullPath: "/customize";
      preLoaderRoute: typeof AuthedShellCustomizeRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/computer": {
      id: "/_authed/_shell/computer";
      path: "/computer";
      fullPath: "/computer";
      preLoaderRoute: typeof AuthedShellComputerRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/automations": {
      id: "/_authed/_shell/automations";
      path: "/automations";
      fullPath: "/automations";
      preLoaderRoute: typeof AuthedShellAutomationsRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/threads/": {
      id: "/_authed/_shell/threads/";
      path: "/threads";
      fullPath: "/threads/";
      preLoaderRoute: typeof AuthedShellThreadsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/apps/": {
      id: "/_authed/_shell/apps/";
      path: "/apps";
      fullPath: "/apps/";
      preLoaderRoute: typeof AuthedShellAppsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/approvals/": {
      id: "/_authed/_shell/approvals/";
      path: "/approvals";
      fullPath: "/approvals/";
      preLoaderRoute: typeof AuthedShellApprovalsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/threads/$id": {
      id: "/_authed/_shell/threads/$id";
      path: "/threads/$id";
      fullPath: "/threads/$id";
      preLoaderRoute: typeof AuthedShellThreadsIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/apps/$id": {
      id: "/_authed/_shell/apps/$id";
      path: "/apps/$id";
      fullPath: "/apps/$id";
      preLoaderRoute: typeof AuthedShellAppsIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/approvals/$approvalId": {
      id: "/_authed/_shell/approvals/$approvalId";
      path: "/approvals/$approvalId";
      fullPath: "/approvals/$approvalId";
      preLoaderRoute: typeof AuthedShellApprovalsApprovalIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
  }
}

interface AuthedShellRouteChildren {
  AuthedShellAutomationsRoute: typeof AuthedShellAutomationsRoute;
  AuthedShellComputerRoute: typeof AuthedShellComputerRoute;
  AuthedShellCustomizeRoute: typeof AuthedShellCustomizeRoute;
  AuthedShellInboxRoute: typeof AuthedShellInboxRoute;
  AuthedShellMemoryRoute: typeof AuthedShellMemoryRoute;
  AuthedShellApprovalsApprovalIdRoute: typeof AuthedShellApprovalsApprovalIdRoute;
  AuthedShellAppsIdRoute: typeof AuthedShellAppsIdRoute;
  AuthedShellThreadsIdRoute: typeof AuthedShellThreadsIdRoute;
  AuthedShellApprovalsIndexRoute: typeof AuthedShellApprovalsIndexRoute;
  AuthedShellAppsIndexRoute: typeof AuthedShellAppsIndexRoute;
  AuthedShellThreadsIndexRoute: typeof AuthedShellThreadsIndexRoute;
}

const AuthedShellRouteChildren: AuthedShellRouteChildren = {
  AuthedShellAutomationsRoute: AuthedShellAutomationsRoute,
  AuthedShellComputerRoute: AuthedShellComputerRoute,
  AuthedShellCustomizeRoute: AuthedShellCustomizeRoute,
  AuthedShellInboxRoute: AuthedShellInboxRoute,
  AuthedShellMemoryRoute: AuthedShellMemoryRoute,
  AuthedShellApprovalsApprovalIdRoute: AuthedShellApprovalsApprovalIdRoute,
  AuthedShellAppsIdRoute: AuthedShellAppsIdRoute,
  AuthedShellThreadsIdRoute: AuthedShellThreadsIdRoute,
  AuthedShellApprovalsIndexRoute: AuthedShellApprovalsIndexRoute,
  AuthedShellAppsIndexRoute: AuthedShellAppsIndexRoute,
  AuthedShellThreadsIndexRoute: AuthedShellThreadsIndexRoute,
};

const AuthedShellRouteWithChildren = AuthedShellRoute._addFileChildren(
  AuthedShellRouteChildren,
);

interface AuthedRouteChildren {
  AuthedShellRoute: typeof AuthedShellRouteWithChildren;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedShellRoute: AuthedShellRouteWithChildren,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthCallbackRoute: AuthCallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
