/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthCallbackRouteImport } from "./routes/auth/callback";
import { Route as AuthedShellRouteImport } from "./routes/_authed/_shell";
import { Route as AuthedShellNewRouteImport } from "./routes/_authed/_shell/new";
import { Route as AuthedShellMemoryRouteImport } from "./routes/_authed/_shell/memory";
import { Route as AuthedShellCustomizeRouteImport } from "./routes/_authed/_shell/customize";
import { Route as AuthedShellAutomationsRouteImport } from "./routes/_authed/_shell/automations";
import { Route as AuthedShellThreadsIndexRouteImport } from "./routes/_authed/_shell/threads.index";
import { Route as AuthedShellMemoryIndexRouteImport } from "./routes/_authed/_shell/memory.index";
import { Route as AuthedShellCustomizeIndexRouteImport } from "./routes/_authed/_shell/customize.index";
import { Route as AuthedShellAutomationsIndexRouteImport } from "./routes/_authed/_shell/automations.index";
import { Route as AuthedShellArtifactsIndexRouteImport } from "./routes/_authed/_shell/artifacts.index";
import { Route as AuthedShellApprovalsIndexRouteImport } from "./routes/_authed/_shell/approvals.index";
import { Route as AuthedShellThreadsIdRouteImport } from "./routes/_authed/_shell/threads.$id";
import { Route as AuthedShellMemoryPagesRouteImport } from "./routes/_authed/_shell/memory.pages";
import { Route as AuthedShellMemoryKbsRouteImport } from "./routes/_authed/_shell/memory.kbs";
import { Route as AuthedShellMemoryBrainRouteImport } from "./routes/_authed/_shell/memory.brain";
import { Route as AuthedShellCustomizeWorkflowsRouteImport } from "./routes/_authed/_shell/customize.workflows";
import { Route as AuthedShellCustomizeSkillsRouteImport } from "./routes/_authed/_shell/customize.skills";
import { Route as AuthedShellCustomizeConnectorsRouteImport } from "./routes/_authed/_shell/customize.connectors";
import { Route as AuthedShellAutomationsScheduledJobIdRouteImport } from "./routes/_authed/_shell/automations.$scheduledJobId";
import { Route as AuthedShellArtifactsIdRouteImport } from "./routes/_authed/_shell/artifacts.$id";
import { Route as AuthedShellApprovalsApprovalIdRouteImport } from "./routes/_authed/_shell/approvals.$approvalId";
import { Route as AuthedShellMemoryKbsKbIdRouteImport } from "./routes/_authed/_shell/memory.kbs.$kbId";

const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedShellRoute = AuthedShellRouteImport.update({
  id: "/_shell",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedShellNewRoute = AuthedShellNewRouteImport.update({
  id: "/new",
  path: "/new",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellMemoryRoute = AuthedShellMemoryRouteImport.update({
  id: "/memory",
  path: "/memory",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellCustomizeRoute = AuthedShellCustomizeRouteImport.update({
  id: "/customize",
  path: "/customize",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellAutomationsRoute = AuthedShellAutomationsRouteImport.update({
  id: "/automations",
  path: "/automations",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellThreadsIndexRoute = AuthedShellThreadsIndexRouteImport.update({
  id: "/threads/",
  path: "/threads/",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellMemoryIndexRoute = AuthedShellMemoryIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthedShellMemoryRoute,
} as any);
const AuthedShellCustomizeIndexRoute =
  AuthedShellCustomizeIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedShellCustomizeRoute,
  } as any);
const AuthedShellAutomationsIndexRoute =
  AuthedShellAutomationsIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthedShellAutomationsRoute,
  } as any);
const AuthedShellArtifactsIndexRoute =
  AuthedShellArtifactsIndexRouteImport.update({
    id: "/artifacts/",
    path: "/artifacts/",
    getParentRoute: () => AuthedShellRoute,
  } as any);
const AuthedShellApprovalsIndexRoute =
  AuthedShellApprovalsIndexRouteImport.update({
    id: "/approvals/",
    path: "/approvals/",
    getParentRoute: () => AuthedShellRoute,
  } as any);
const AuthedShellThreadsIdRoute = AuthedShellThreadsIdRouteImport.update({
  id: "/threads/$id",
  path: "/threads/$id",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellMemoryPagesRoute = AuthedShellMemoryPagesRouteImport.update({
  id: "/pages",
  path: "/pages",
  getParentRoute: () => AuthedShellMemoryRoute,
} as any);
const AuthedShellMemoryKbsRoute = AuthedShellMemoryKbsRouteImport.update({
  id: "/kbs",
  path: "/kbs",
  getParentRoute: () => AuthedShellMemoryRoute,
} as any);
const AuthedShellMemoryBrainRoute = AuthedShellMemoryBrainRouteImport.update({
  id: "/brain",
  path: "/brain",
  getParentRoute: () => AuthedShellMemoryRoute,
} as any);
const AuthedShellCustomizeWorkflowsRoute =
  AuthedShellCustomizeWorkflowsRouteImport.update({
    id: "/workflows",
    path: "/workflows",
    getParentRoute: () => AuthedShellCustomizeRoute,
  } as any);
const AuthedShellCustomizeSkillsRoute =
  AuthedShellCustomizeSkillsRouteImport.update({
    id: "/skills",
    path: "/skills",
    getParentRoute: () => AuthedShellCustomizeRoute,
  } as any);
const AuthedShellCustomizeConnectorsRoute =
  AuthedShellCustomizeConnectorsRouteImport.update({
    id: "/connectors",
    path: "/connectors",
    getParentRoute: () => AuthedShellCustomizeRoute,
  } as any);
const AuthedShellAutomationsScheduledJobIdRoute =
  AuthedShellAutomationsScheduledJobIdRouteImport.update({
    id: "/$scheduledJobId",
    path: "/$scheduledJobId",
    getParentRoute: () => AuthedShellAutomationsRoute,
  } as any);
const AuthedShellArtifactsIdRoute = AuthedShellArtifactsIdRouteImport.update({
  id: "/artifacts/$id",
  path: "/artifacts/$id",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellApprovalsApprovalIdRoute =
  AuthedShellApprovalsApprovalIdRouteImport.update({
    id: "/approvals/$approvalId",
    path: "/approvals/$approvalId",
    getParentRoute: () => AuthedShellRoute,
  } as any);
const AuthedShellMemoryKbsKbIdRoute =
  AuthedShellMemoryKbsKbIdRouteImport.update({
    id: "/$kbId",
    path: "/$kbId",
    getParentRoute: () => AuthedShellMemoryKbsRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/sign-in": typeof SignInRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/automations": typeof AuthedShellAutomationsRouteWithChildren;
  "/customize": typeof AuthedShellCustomizeRouteWithChildren;
  "/memory": typeof AuthedShellMemoryRouteWithChildren;
  "/new": typeof AuthedShellNewRoute;
  "/approvals/$approvalId": typeof AuthedShellApprovalsApprovalIdRoute;
  "/artifacts/$id": typeof AuthedShellArtifactsIdRoute;
  "/automations/$scheduledJobId": typeof AuthedShellAutomationsScheduledJobIdRoute;
  "/customize/connectors": typeof AuthedShellCustomizeConnectorsRoute;
  "/customize/skills": typeof AuthedShellCustomizeSkillsRoute;
  "/customize/workflows": typeof AuthedShellCustomizeWorkflowsRoute;
  "/memory/brain": typeof AuthedShellMemoryBrainRoute;
  "/memory/kbs": typeof AuthedShellMemoryKbsRouteWithChildren;
  "/memory/pages": typeof AuthedShellMemoryPagesRoute;
  "/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/approvals/": typeof AuthedShellApprovalsIndexRoute;
  "/artifacts/": typeof AuthedShellArtifactsIndexRoute;
  "/automations/": typeof AuthedShellAutomationsIndexRoute;
  "/customize/": typeof AuthedShellCustomizeIndexRoute;
  "/memory/": typeof AuthedShellMemoryIndexRoute;
  "/threads/": typeof AuthedShellThreadsIndexRoute;
  "/memory/kbs/$kbId": typeof AuthedShellMemoryKbsKbIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/sign-in": typeof SignInRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/new": typeof AuthedShellNewRoute;
  "/approvals/$approvalId": typeof AuthedShellApprovalsApprovalIdRoute;
  "/artifacts/$id": typeof AuthedShellArtifactsIdRoute;
  "/automations/$scheduledJobId": typeof AuthedShellAutomationsScheduledJobIdRoute;
  "/customize/connectors": typeof AuthedShellCustomizeConnectorsRoute;
  "/customize/skills": typeof AuthedShellCustomizeSkillsRoute;
  "/customize/workflows": typeof AuthedShellCustomizeWorkflowsRoute;
  "/memory/brain": typeof AuthedShellMemoryBrainRoute;
  "/memory/kbs": typeof AuthedShellMemoryKbsRouteWithChildren;
  "/memory/pages": typeof AuthedShellMemoryPagesRoute;
  "/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/approvals": typeof AuthedShellApprovalsIndexRoute;
  "/artifacts": typeof AuthedShellArtifactsIndexRoute;
  "/automations": typeof AuthedShellAutomationsIndexRoute;
  "/customize": typeof AuthedShellCustomizeIndexRoute;
  "/memory": typeof AuthedShellMemoryIndexRoute;
  "/threads": typeof AuthedShellThreadsIndexRoute;
  "/memory/kbs/$kbId": typeof AuthedShellMemoryKbsKbIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/sign-in": typeof SignInRoute;
  "/_authed/_shell": typeof AuthedShellRouteWithChildren;
  "/auth/callback": typeof AuthCallbackRoute;
  "/_authed/_shell/automations": typeof AuthedShellAutomationsRouteWithChildren;
  "/_authed/_shell/customize": typeof AuthedShellCustomizeRouteWithChildren;
  "/_authed/_shell/memory": typeof AuthedShellMemoryRouteWithChildren;
  "/_authed/_shell/new": typeof AuthedShellNewRoute;
  "/_authed/_shell/approvals/$approvalId": typeof AuthedShellApprovalsApprovalIdRoute;
  "/_authed/_shell/artifacts/$id": typeof AuthedShellArtifactsIdRoute;
  "/_authed/_shell/automations/$scheduledJobId": typeof AuthedShellAutomationsScheduledJobIdRoute;
  "/_authed/_shell/customize/connectors": typeof AuthedShellCustomizeConnectorsRoute;
  "/_authed/_shell/customize/skills": typeof AuthedShellCustomizeSkillsRoute;
  "/_authed/_shell/customize/workflows": typeof AuthedShellCustomizeWorkflowsRoute;
  "/_authed/_shell/memory/brain": typeof AuthedShellMemoryBrainRoute;
  "/_authed/_shell/memory/kbs": typeof AuthedShellMemoryKbsRouteWithChildren;
  "/_authed/_shell/memory/pages": typeof AuthedShellMemoryPagesRoute;
  "/_authed/_shell/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/_authed/_shell/approvals/": typeof AuthedShellApprovalsIndexRoute;
  "/_authed/_shell/artifacts/": typeof AuthedShellArtifactsIndexRoute;
  "/_authed/_shell/automations/": typeof AuthedShellAutomationsIndexRoute;
  "/_authed/_shell/customize/": typeof AuthedShellCustomizeIndexRoute;
  "/_authed/_shell/memory/": typeof AuthedShellMemoryIndexRoute;
  "/_authed/_shell/threads/": typeof AuthedShellThreadsIndexRoute;
  "/_authed/_shell/memory/kbs/$kbId": typeof AuthedShellMemoryKbsKbIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/sign-in"
    | "/auth/callback"
    | "/automations"
    | "/customize"
    | "/memory"
    | "/new"
    | "/approvals/$approvalId"
    | "/artifacts/$id"
    | "/automations/$scheduledJobId"
    | "/customize/connectors"
    | "/customize/skills"
    | "/customize/workflows"
    | "/memory/brain"
    | "/memory/kbs"
    | "/memory/pages"
    | "/threads/$id"
    | "/approvals/"
    | "/artifacts/"
    | "/automations/"
    | "/customize/"
    | "/memory/"
    | "/threads/"
    | "/memory/kbs/$kbId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/sign-in"
    | "/auth/callback"
    | "/new"
    | "/approvals/$approvalId"
    | "/artifacts/$id"
    | "/automations/$scheduledJobId"
    | "/customize/connectors"
    | "/customize/skills"
    | "/customize/workflows"
    | "/memory/brain"
    | "/memory/kbs"
    | "/memory/pages"
    | "/threads/$id"
    | "/approvals"
    | "/artifacts"
    | "/automations"
    | "/customize"
    | "/memory"
    | "/threads"
    | "/memory/kbs/$kbId";
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/_authed"
    | "/sign-in"
    | "/_authed/_shell"
    | "/auth/callback"
    | "/_authed/_shell/automations"
    | "/_authed/_shell/customize"
    | "/_authed/_shell/memory"
    | "/_authed/_shell/new"
    | "/_authed/_shell/approvals/$approvalId"
    | "/_authed/_shell/artifacts/$id"
    | "/_authed/_shell/automations/$scheduledJobId"
    | "/_authed/_shell/customize/connectors"
    | "/_authed/_shell/customize/skills"
    | "/_authed/_shell/customize/workflows"
    | "/_authed/_shell/memory/brain"
    | "/_authed/_shell/memory/kbs"
    | "/_authed/_shell/memory/pages"
    | "/_authed/_shell/threads/$id"
    | "/_authed/_shell/approvals/"
    | "/_authed/_shell/artifacts/"
    | "/_authed/_shell/automations/"
    | "/_authed/_shell/customize/"
    | "/_authed/_shell/memory/"
    | "/_authed/_shell/threads/"
    | "/_authed/_shell/memory/kbs/$kbId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  SignInRoute: typeof SignInRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/_shell": {
      id: "/_authed/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedShellRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/_shell/new": {
      id: "/_authed/_shell/new";
      path: "/new";
      fullPath: "/new";
      preLoaderRoute: typeof AuthedShellNewRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/memory": {
      id: "/_authed/_shell/memory";
      path: "/memory";
      fullPath: "/memory";
      preLoaderRoute: typeof AuthedShellMemoryRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/customize": {
      id: "/_authed/_shell/customize";
      path: "/customize";
      fullPath: "/customize";
      preLoaderRoute: typeof AuthedShellCustomizeRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/automations": {
      id: "/_authed/_shell/automations";
      path: "/automations";
      fullPath: "/automations";
      preLoaderRoute: typeof AuthedShellAutomationsRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/threads/": {
      id: "/_authed/_shell/threads/";
      path: "/threads";
      fullPath: "/threads/";
      preLoaderRoute: typeof AuthedShellThreadsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/memory/": {
      id: "/_authed/_shell/memory/";
      path: "/";
      fullPath: "/memory/";
      preLoaderRoute: typeof AuthedShellMemoryIndexRouteImport;
      parentRoute: typeof AuthedShellMemoryRoute;
    };
    "/_authed/_shell/customize/": {
      id: "/_authed/_shell/customize/";
      path: "/";
      fullPath: "/customize/";
      preLoaderRoute: typeof AuthedShellCustomizeIndexRouteImport;
      parentRoute: typeof AuthedShellCustomizeRoute;
    };
    "/_authed/_shell/automations/": {
      id: "/_authed/_shell/automations/";
      path: "/";
      fullPath: "/automations/";
      preLoaderRoute: typeof AuthedShellAutomationsIndexRouteImport;
      parentRoute: typeof AuthedShellAutomationsRoute;
    };
    "/_authed/_shell/artifacts/": {
      id: "/_authed/_shell/artifacts/";
      path: "/artifacts";
      fullPath: "/artifacts/";
      preLoaderRoute: typeof AuthedShellArtifactsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/approvals/": {
      id: "/_authed/_shell/approvals/";
      path: "/approvals";
      fullPath: "/approvals/";
      preLoaderRoute: typeof AuthedShellApprovalsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/threads/$id": {
      id: "/_authed/_shell/threads/$id";
      path: "/threads/$id";
      fullPath: "/threads/$id";
      preLoaderRoute: typeof AuthedShellThreadsIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/memory/pages": {
      id: "/_authed/_shell/memory/pages";
      path: "/pages";
      fullPath: "/memory/pages";
      preLoaderRoute: typeof AuthedShellMemoryPagesRouteImport;
      parentRoute: typeof AuthedShellMemoryRoute;
    };
    "/_authed/_shell/memory/kbs": {
      id: "/_authed/_shell/memory/kbs";
      path: "/kbs";
      fullPath: "/memory/kbs";
      preLoaderRoute: typeof AuthedShellMemoryKbsRouteImport;
      parentRoute: typeof AuthedShellMemoryRoute;
    };
    "/_authed/_shell/memory/brain": {
      id: "/_authed/_shell/memory/brain";
      path: "/brain";
      fullPath: "/memory/brain";
      preLoaderRoute: typeof AuthedShellMemoryBrainRouteImport;
      parentRoute: typeof AuthedShellMemoryRoute;
    };
    "/_authed/_shell/customize/workflows": {
      id: "/_authed/_shell/customize/workflows";
      path: "/workflows";
      fullPath: "/customize/workflows";
      preLoaderRoute: typeof AuthedShellCustomizeWorkflowsRouteImport;
      parentRoute: typeof AuthedShellCustomizeRoute;
    };
    "/_authed/_shell/customize/skills": {
      id: "/_authed/_shell/customize/skills";
      path: "/skills";
      fullPath: "/customize/skills";
      preLoaderRoute: typeof AuthedShellCustomizeSkillsRouteImport;
      parentRoute: typeof AuthedShellCustomizeRoute;
    };
    "/_authed/_shell/customize/connectors": {
      id: "/_authed/_shell/customize/connectors";
      path: "/connectors";
      fullPath: "/customize/connectors";
      preLoaderRoute: typeof AuthedShellCustomizeConnectorsRouteImport;
      parentRoute: typeof AuthedShellCustomizeRoute;
    };
    "/_authed/_shell/automations/$scheduledJobId": {
      id: "/_authed/_shell/automations/$scheduledJobId";
      path: "/$scheduledJobId";
      fullPath: "/automations/$scheduledJobId";
      preLoaderRoute: typeof AuthedShellAutomationsScheduledJobIdRouteImport;
      parentRoute: typeof AuthedShellAutomationsRoute;
    };
    "/_authed/_shell/artifacts/$id": {
      id: "/_authed/_shell/artifacts/$id";
      path: "/artifacts/$id";
      fullPath: "/artifacts/$id";
      preLoaderRoute: typeof AuthedShellArtifactsIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/approvals/$approvalId": {
      id: "/_authed/_shell/approvals/$approvalId";
      path: "/approvals/$approvalId";
      fullPath: "/approvals/$approvalId";
      preLoaderRoute: typeof AuthedShellApprovalsApprovalIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/memory/kbs/$kbId": {
      id: "/_authed/_shell/memory/kbs/$kbId";
      path: "/$kbId";
      fullPath: "/memory/kbs/$kbId";
      preLoaderRoute: typeof AuthedShellMemoryKbsKbIdRouteImport;
      parentRoute: typeof AuthedShellMemoryKbsRoute;
    };
  }
}

interface AuthedShellAutomationsRouteChildren {
  AuthedShellAutomationsScheduledJobIdRoute: typeof AuthedShellAutomationsScheduledJobIdRoute;
  AuthedShellAutomationsIndexRoute: typeof AuthedShellAutomationsIndexRoute;
}

const AuthedShellAutomationsRouteChildren: AuthedShellAutomationsRouteChildren =
  {
    AuthedShellAutomationsScheduledJobIdRoute:
      AuthedShellAutomationsScheduledJobIdRoute,
    AuthedShellAutomationsIndexRoute: AuthedShellAutomationsIndexRoute,
  };

const AuthedShellAutomationsRouteWithChildren =
  AuthedShellAutomationsRoute._addFileChildren(
    AuthedShellAutomationsRouteChildren,
  );

interface AuthedShellCustomizeRouteChildren {
  AuthedShellCustomizeConnectorsRoute: typeof AuthedShellCustomizeConnectorsRoute;
  AuthedShellCustomizeSkillsRoute: typeof AuthedShellCustomizeSkillsRoute;
  AuthedShellCustomizeWorkflowsRoute: typeof AuthedShellCustomizeWorkflowsRoute;
  AuthedShellCustomizeIndexRoute: typeof AuthedShellCustomizeIndexRoute;
}

const AuthedShellCustomizeRouteChildren: AuthedShellCustomizeRouteChildren = {
  AuthedShellCustomizeConnectorsRoute: AuthedShellCustomizeConnectorsRoute,
  AuthedShellCustomizeSkillsRoute: AuthedShellCustomizeSkillsRoute,
  AuthedShellCustomizeWorkflowsRoute: AuthedShellCustomizeWorkflowsRoute,
  AuthedShellCustomizeIndexRoute: AuthedShellCustomizeIndexRoute,
};

const AuthedShellCustomizeRouteWithChildren =
  AuthedShellCustomizeRoute._addFileChildren(AuthedShellCustomizeRouteChildren);

interface AuthedShellMemoryKbsRouteChildren {
  AuthedShellMemoryKbsKbIdRoute: typeof AuthedShellMemoryKbsKbIdRoute;
}

const AuthedShellMemoryKbsRouteChildren: AuthedShellMemoryKbsRouteChildren = {
  AuthedShellMemoryKbsKbIdRoute: AuthedShellMemoryKbsKbIdRoute,
};

const AuthedShellMemoryKbsRouteWithChildren =
  AuthedShellMemoryKbsRoute._addFileChildren(AuthedShellMemoryKbsRouteChildren);

interface AuthedShellMemoryRouteChildren {
  AuthedShellMemoryBrainRoute: typeof AuthedShellMemoryBrainRoute;
  AuthedShellMemoryKbsRoute: typeof AuthedShellMemoryKbsRouteWithChildren;
  AuthedShellMemoryPagesRoute: typeof AuthedShellMemoryPagesRoute;
  AuthedShellMemoryIndexRoute: typeof AuthedShellMemoryIndexRoute;
}

const AuthedShellMemoryRouteChildren: AuthedShellMemoryRouteChildren = {
  AuthedShellMemoryBrainRoute: AuthedShellMemoryBrainRoute,
  AuthedShellMemoryKbsRoute: AuthedShellMemoryKbsRouteWithChildren,
  AuthedShellMemoryPagesRoute: AuthedShellMemoryPagesRoute,
  AuthedShellMemoryIndexRoute: AuthedShellMemoryIndexRoute,
};

const AuthedShellMemoryRouteWithChildren =
  AuthedShellMemoryRoute._addFileChildren(AuthedShellMemoryRouteChildren);

interface AuthedShellRouteChildren {
  AuthedShellAutomationsRoute: typeof AuthedShellAutomationsRouteWithChildren;
  AuthedShellCustomizeRoute: typeof AuthedShellCustomizeRouteWithChildren;
  AuthedShellMemoryRoute: typeof AuthedShellMemoryRouteWithChildren;
  AuthedShellNewRoute: typeof AuthedShellNewRoute;
  AuthedShellApprovalsApprovalIdRoute: typeof AuthedShellApprovalsApprovalIdRoute;
  AuthedShellArtifactsIdRoute: typeof AuthedShellArtifactsIdRoute;
  AuthedShellThreadsIdRoute: typeof AuthedShellThreadsIdRoute;
  AuthedShellApprovalsIndexRoute: typeof AuthedShellApprovalsIndexRoute;
  AuthedShellArtifactsIndexRoute: typeof AuthedShellArtifactsIndexRoute;
  AuthedShellThreadsIndexRoute: typeof AuthedShellThreadsIndexRoute;
}

const AuthedShellRouteChildren: AuthedShellRouteChildren = {
  AuthedShellAutomationsRoute: AuthedShellAutomationsRouteWithChildren,
  AuthedShellCustomizeRoute: AuthedShellCustomizeRouteWithChildren,
  AuthedShellMemoryRoute: AuthedShellMemoryRouteWithChildren,
  AuthedShellNewRoute: AuthedShellNewRoute,
  AuthedShellApprovalsApprovalIdRoute: AuthedShellApprovalsApprovalIdRoute,
  AuthedShellArtifactsIdRoute: AuthedShellArtifactsIdRoute,
  AuthedShellThreadsIdRoute: AuthedShellThreadsIdRoute,
  AuthedShellApprovalsIndexRoute: AuthedShellApprovalsIndexRoute,
  AuthedShellArtifactsIndexRoute: AuthedShellArtifactsIndexRoute,
  AuthedShellThreadsIndexRoute: AuthedShellThreadsIndexRoute,
};

const AuthedShellRouteWithChildren = AuthedShellRoute._addFileChildren(
  AuthedShellRouteChildren,
);

interface AuthedRouteChildren {
  AuthedShellRoute: typeof AuthedShellRouteWithChildren;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedShellRoute: AuthedShellRouteWithChildren,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthCallbackRoute: AuthCallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
