/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SignInRouteImport } from "./routes/sign-in";
import { Route as AuthedRouteImport } from "./routes/_authed";
import { Route as SplatRouteImport } from "./routes/$";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthCallbackRouteImport } from "./routes/auth/callback";
import { Route as AuthedShellRouteImport } from "./routes/_authed/_shell";
import { Route as AuthedShellInboxRouteImport } from "./routes/_authed/_shell/inbox";
import { Route as AuthedShellComputerRouteImport } from "./routes/_authed/_shell/computer";
import { Route as AuthedShellAutomationsRouteImport } from "./routes/_authed/_shell/automations";
import { Route as AuthedShellTasksIndexRouteImport } from "./routes/_authed/_shell/tasks.index";
import { Route as AuthedShellAppsIndexRouteImport } from "./routes/_authed/_shell/apps.index";
import { Route as AuthedShellThreadsIdRouteImport } from "./routes/_authed/_shell/threads.$id";
import { Route as AuthedShellTasksIdRouteImport } from "./routes/_authed/_shell/tasks.$id";
import { Route as AuthedShellAppsIdRouteImport } from "./routes/_authed/_shell/apps.$id";

const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: "/$",
  path: "/$",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: "/auth/callback",
  path: "/auth/callback",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedShellRoute = AuthedShellRouteImport.update({
  id: "/_shell",
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedShellInboxRoute = AuthedShellInboxRouteImport.update({
  id: "/inbox",
  path: "/inbox",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellComputerRoute = AuthedShellComputerRouteImport.update({
  id: "/computer",
  path: "/computer",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellAutomationsRoute = AuthedShellAutomationsRouteImport.update({
  id: "/automations",
  path: "/automations",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellTasksIndexRoute = AuthedShellTasksIndexRouteImport.update({
  id: "/tasks/",
  path: "/tasks/",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellAppsIndexRoute = AuthedShellAppsIndexRouteImport.update({
  id: "/apps/",
  path: "/apps/",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellThreadsIdRoute = AuthedShellThreadsIdRouteImport.update({
  id: "/threads/$id",
  path: "/threads/$id",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellTasksIdRoute = AuthedShellTasksIdRouteImport.update({
  id: "/tasks/$id",
  path: "/tasks/$id",
  getParentRoute: () => AuthedShellRoute,
} as any);
const AuthedShellAppsIdRoute = AuthedShellAppsIdRouteImport.update({
  id: "/apps/$id",
  path: "/apps/$id",
  getParentRoute: () => AuthedShellRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/sign-in": typeof SignInRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/automations": typeof AuthedShellAutomationsRoute;
  "/computer": typeof AuthedShellComputerRoute;
  "/inbox": typeof AuthedShellInboxRoute;
  "/apps/$id": typeof AuthedShellAppsIdRoute;
  "/tasks/$id": typeof AuthedShellTasksIdRoute;
  "/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/apps/": typeof AuthedShellAppsIndexRoute;
  "/tasks/": typeof AuthedShellTasksIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/sign-in": typeof SignInRoute;
  "/auth/callback": typeof AuthCallbackRoute;
  "/automations": typeof AuthedShellAutomationsRoute;
  "/computer": typeof AuthedShellComputerRoute;
  "/inbox": typeof AuthedShellInboxRoute;
  "/apps/$id": typeof AuthedShellAppsIdRoute;
  "/tasks/$id": typeof AuthedShellTasksIdRoute;
  "/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/apps": typeof AuthedShellAppsIndexRoute;
  "/tasks": typeof AuthedShellTasksIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$": typeof SplatRoute;
  "/_authed": typeof AuthedRouteWithChildren;
  "/sign-in": typeof SignInRoute;
  "/_authed/_shell": typeof AuthedShellRouteWithChildren;
  "/auth/callback": typeof AuthCallbackRoute;
  "/_authed/_shell/automations": typeof AuthedShellAutomationsRoute;
  "/_authed/_shell/computer": typeof AuthedShellComputerRoute;
  "/_authed/_shell/inbox": typeof AuthedShellInboxRoute;
  "/_authed/_shell/apps/$id": typeof AuthedShellAppsIdRoute;
  "/_authed/_shell/tasks/$id": typeof AuthedShellTasksIdRoute;
  "/_authed/_shell/threads/$id": typeof AuthedShellThreadsIdRoute;
  "/_authed/_shell/apps/": typeof AuthedShellAppsIndexRoute;
  "/_authed/_shell/tasks/": typeof AuthedShellTasksIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$"
    | "/sign-in"
    | "/auth/callback"
    | "/automations"
    | "/computer"
    | "/inbox"
    | "/apps/$id"
    | "/tasks/$id"
    | "/threads/$id"
    | "/apps/"
    | "/tasks/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/$"
    | "/sign-in"
    | "/auth/callback"
    | "/automations"
    | "/computer"
    | "/inbox"
    | "/apps/$id"
    | "/tasks/$id"
    | "/threads/$id"
    | "/apps"
    | "/tasks";
  id:
    | "__root__"
    | "/"
    | "/$"
    | "/_authed"
    | "/sign-in"
    | "/_authed/_shell"
    | "/auth/callback"
    | "/_authed/_shell/automations"
    | "/_authed/_shell/computer"
    | "/_authed/_shell/inbox"
    | "/_authed/_shell/apps/$id"
    | "/_authed/_shell/tasks/$id"
    | "/_authed/_shell/threads/$id"
    | "/_authed/_shell/apps/"
    | "/_authed/_shell/tasks/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  SignInRoute: typeof SignInRoute;
  AuthCallbackRoute: typeof AuthCallbackRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-in": {
      id: "/sign-in";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed": {
      id: "/_authed";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$": {
      id: "/$";
      path: "/$";
      fullPath: "/$";
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/callback": {
      id: "/auth/callback";
      path: "/auth/callback";
      fullPath: "/auth/callback";
      preLoaderRoute: typeof AuthCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authed/_shell": {
      id: "/_authed/_shell";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthedShellRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    "/_authed/_shell/inbox": {
      id: "/_authed/_shell/inbox";
      path: "/inbox";
      fullPath: "/inbox";
      preLoaderRoute: typeof AuthedShellInboxRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/computer": {
      id: "/_authed/_shell/computer";
      path: "/computer";
      fullPath: "/computer";
      preLoaderRoute: typeof AuthedShellComputerRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/automations": {
      id: "/_authed/_shell/automations";
      path: "/automations";
      fullPath: "/automations";
      preLoaderRoute: typeof AuthedShellAutomationsRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/tasks/": {
      id: "/_authed/_shell/tasks/";
      path: "/tasks";
      fullPath: "/tasks/";
      preLoaderRoute: typeof AuthedShellTasksIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/apps/": {
      id: "/_authed/_shell/apps/";
      path: "/apps";
      fullPath: "/apps/";
      preLoaderRoute: typeof AuthedShellAppsIndexRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/threads/$id": {
      id: "/_authed/_shell/threads/$id";
      path: "/threads/$id";
      fullPath: "/threads/$id";
      preLoaderRoute: typeof AuthedShellThreadsIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/tasks/$id": {
      id: "/_authed/_shell/tasks/$id";
      path: "/tasks/$id";
      fullPath: "/tasks/$id";
      preLoaderRoute: typeof AuthedShellTasksIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
    "/_authed/_shell/apps/$id": {
      id: "/_authed/_shell/apps/$id";
      path: "/apps/$id";
      fullPath: "/apps/$id";
      preLoaderRoute: typeof AuthedShellAppsIdRouteImport;
      parentRoute: typeof AuthedShellRoute;
    };
  }
}

interface AuthedShellRouteChildren {
  AuthedShellAutomationsRoute: typeof AuthedShellAutomationsRoute;
  AuthedShellComputerRoute: typeof AuthedShellComputerRoute;
  AuthedShellInboxRoute: typeof AuthedShellInboxRoute;
  AuthedShellAppsIdRoute: typeof AuthedShellAppsIdRoute;
  AuthedShellTasksIdRoute: typeof AuthedShellTasksIdRoute;
  AuthedShellThreadsIdRoute: typeof AuthedShellThreadsIdRoute;
  AuthedShellAppsIndexRoute: typeof AuthedShellAppsIndexRoute;
  AuthedShellTasksIndexRoute: typeof AuthedShellTasksIndexRoute;
}

const AuthedShellRouteChildren: AuthedShellRouteChildren = {
  AuthedShellAutomationsRoute: AuthedShellAutomationsRoute,
  AuthedShellComputerRoute: AuthedShellComputerRoute,
  AuthedShellInboxRoute: AuthedShellInboxRoute,
  AuthedShellAppsIdRoute: AuthedShellAppsIdRoute,
  AuthedShellTasksIdRoute: AuthedShellTasksIdRoute,
  AuthedShellThreadsIdRoute: AuthedShellThreadsIdRoute,
  AuthedShellAppsIndexRoute: AuthedShellAppsIndexRoute,
  AuthedShellTasksIndexRoute: AuthedShellTasksIndexRoute,
};

const AuthedShellRouteWithChildren = AuthedShellRoute._addFileChildren(
  AuthedShellRouteChildren,
);

interface AuthedRouteChildren {
  AuthedShellRoute: typeof AuthedShellRouteWithChildren;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedShellRoute: AuthedShellRouteWithChildren,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthCallbackRoute: AuthCallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
