import { describe, expect, it } from "vitest";
import {
  ALL_KINDS,
  TAB_ALL,
  filterArtifactItems,
  toArtifactItem,
  uniqueKinds,
  type ArtifactItem,
} from "./artifacts-filtering";
import type { AppArtifactPreview } from "@/lib/app-artifacts";

const items: ArtifactItem[] = [
  {
    id: "a1",
    title: "LastMile CRM pipeline risk",
    kind: "applet",
    modelId: "claude-opus-4-7",
    stdlibVersion: "0.1.0",
    generatedAt: "2026-05-09T10:00:00.000Z",
    version: 1,
  },
  {
    id: "a2",
    title: "Austin Map",
    kind: "applet",
    modelId: "claude-sonnet-4-6",
    stdlibVersion: "0.1.0",
    generatedAt: "2026-05-09T11:00:00.000Z",
    version: 2,
  },
  {
    id: "c1",
    title: "Pipeline chart",
    kind: "chart",
    modelId: null,
    stdlibVersion: null,
    generatedAt: "",
    version: null,
  },
];

describe("filterArtifactItems", () => {
  it("returns all items when no filters are active", () => {
    expect(
      filterArtifactItems({
        items,
        search: "",
        kind: ALL_KINDS,
        tab: TAB_ALL,
      }),
    ).toHaveLength(3);
  });

  it("matches title case-insensitively", () => {
    expect(
      filterArtifactItems({
        items,
        search: "lastmile",
        kind: ALL_KINDS,
        tab: TAB_ALL,
      }).map((r) => r.id),
    ).toEqual(["a1"]);
  });

  it("matches modelId substring even when title does not contain it", () => {
    expect(
      filterArtifactItems({
        items,
        search: "sonnet",
        kind: ALL_KINDS,
        tab: TAB_ALL,
      }).map((r) => r.id),
    ).toEqual(["a2"]);
  });

  it("tab filter excludes non-matching kinds", () => {
    expect(
      filterArtifactItems({
        items,
        search: "",
        kind: ALL_KINDS,
        tab: "applet",
      }).map((r) => r.id),
    ).toEqual(["a1", "a2"]);
  });

  it("kind dropdown filter applies on top of tab=all", () => {
    expect(
      filterArtifactItems({
        items,
        search: "",
        kind: "chart",
        tab: TAB_ALL,
      }).map((r) => r.id),
    ).toEqual(["c1"]);
  });

  it("returns empty when filters exclude everything", () => {
    expect(
      filterArtifactItems({
        items,
        search: "nothing-matches",
        kind: ALL_KINDS,
        tab: TAB_ALL,
      }),
    ).toEqual([]);
  });

  it("handles an empty input list", () => {
    expect(
      filterArtifactItems({
        items: [],
        search: "anything",
        kind: ALL_KINDS,
        tab: TAB_ALL,
      }),
    ).toEqual([]);
  });
});

describe("uniqueKinds", () => {
  it("returns sorted unique kinds", () => {
    expect(uniqueKinds(items)).toEqual(["applet", "chart"]);
  });

  it("returns [] for empty input", () => {
    expect(uniqueKinds([])).toEqual([]);
  });
});

describe("toArtifactItem", () => {
  it("preserves identifying fields and coerces missing optionals to null/empty", () => {
    const preview: AppArtifactPreview = {
      id: "33333333-3333-4333-8333-333333333333",
      title: "LastMile CRM pipeline risk",
      kind: "applet",
      summary: "Pipeline-risk applet generated by Computer.",
      href: "/artifacts/33333333-3333-4333-8333-333333333333",
      generatedAt: "2026-05-08T16:00:00.000Z",
      version: 1,
      modelId: "claude-opus-4-7",
      stdlibVersionAtGeneration: "0.1.0",
    };
    expect(toArtifactItem(preview)).toEqual({
      id: preview.id,
      title: preview.title,
      kind: "applet",
      modelId: "claude-opus-4-7",
      stdlibVersion: "0.1.0",
      generatedAt: "2026-05-08T16:00:00.000Z",
      version: 1,
    });
  });

  it("coerces missing optional fields to null/empty", () => {
    const preview: AppArtifactPreview = {
      id: "x",
      title: "X",
      kind: "applet",
      summary: "",
      href: "/artifacts/x",
      generatedAt: "",
    };
    const item = toArtifactItem(preview);
    expect(item.modelId).toBeNull();
    expect(item.stdlibVersion).toBeNull();
    expect(item.version).toBeNull();
    expect(item.generatedAt).toBe("");
  });
});
