// Generated by plugins/catalog/scripts/generate-plugin-registry.ts.
// Do not edit by hand. Update plugins/*/package.json, then run:
//   pnpm --filter @thinkwork/plugin-catalog generate:plugins

import { defineFirstPartyPluginPackage } from "../plugin-package";
import { companyBrainPluginPackage as rawCompanyBrainPluginPackage } from "@thinkwork/plugin-company-brain";
import { lastmilePluginPackage as rawLastmilePluginPackage } from "@thinkwork/plugin-lastmile";
import { planePluginPackage as rawPlanePluginPackage } from "@thinkwork/plugin-plane";
import { twentyPluginPackage as rawTwentyPluginPackage } from "@thinkwork/plugin-twenty";

export const companyBrainPluginPackage = defineFirstPartyPluginPackage(
  rawCompanyBrainPluginPackage,
);
export const lastmilePluginPackage = defineFirstPartyPluginPackage(
  rawLastmilePluginPackage,
);
export const planePluginPackage = defineFirstPartyPluginPackage(
  rawPlanePluginPackage,
);
export const twentyPluginPackage = defineFirstPartyPluginPackage(
  rawTwentyPluginPackage,
);

export const companyBrainManifest = companyBrainPluginPackage.manifest;
export const lastmileManifest = lastmilePluginPackage.manifest;
export const planeManifest = planePluginPackage.manifest;
export const twentyManifest = twentyPluginPackage.manifest;

export const firstPartyPluginPackages = [
  companyBrainPluginPackage,
  lastmilePluginPackage,
  planePluginPackage,
  twentyPluginPackage,
] as const;

/**
 * Every repo-authored manifest published to the catalog.
 */
export const allPluginManifests = firstPartyPluginPackages
  .map((pluginPackage) => pluginPackage.manifest)
  .sort((a, b) => a.pluginKey.localeCompare(b.pluginKey));
