// Generated by plugins/catalog/scripts/generate-plugin-registry.ts.
// Do not edit by hand. Update plugins/*/package.json, then run:
//   pnpm --filter @thinkwork/plugin-catalog generate:plugins

import { defineFirstPartyPluginPackage } from "../plugin-package";
import { emailChannelPluginPackage as rawEmailChannelPluginPackage } from "@thinkwork/plugin-email-channel";
import { n8nPluginPackage as rawN8nPluginPackage } from "@thinkwork/plugin-n8n";
import { sendgridPluginPackage as rawSendgridPluginPackage } from "@thinkwork/plugin-sendgrid";
import { twentyPluginPackage as rawTwentyPluginPackage } from "@thinkwork/plugin-twenty";

export const emailChannelPluginPackage = defineFirstPartyPluginPackage(
  rawEmailChannelPluginPackage,
);
export const n8nPluginPackage = defineFirstPartyPluginPackage(
  rawN8nPluginPackage,
);
export const sendgridPluginPackage = defineFirstPartyPluginPackage(
  rawSendgridPluginPackage,
);
export const twentyPluginPackage = defineFirstPartyPluginPackage(
  rawTwentyPluginPackage,
);

export const emailChannelManifest = emailChannelPluginPackage.manifest;
export const n8nManifest = n8nPluginPackage.manifest;
export const sendgridManifest = sendgridPluginPackage.manifest;
export const twentyManifest = twentyPluginPackage.manifest;

export const firstPartyPluginPackages = [
  emailChannelPluginPackage,
  n8nPluginPackage,
  sendgridPluginPackage,
  twentyPluginPackage,
] as const;

/**
 * Every repo-authored manifest published to the catalog.
 */
export const allPluginManifests = firstPartyPluginPackages
  .map((pluginPackage) => pluginPackage.manifest)
  .sort((a, b) => {
    const byName = a.displayName.localeCompare(b.displayName, undefined, {
      sensitivity: "base",
    });
    return byName === 0 ? a.pluginKey.localeCompare(b.pluginKey) : byName;
  });
