// Generated by plugins/catalog/scripts/generate-plugin-registry.ts.
// Do not edit by hand. Update plugins/*/package.json, then run:
//   pnpm --filter @thinkwork/plugin-catalog generate:plugins

import { defineFirstPartyPluginPackage } from "../plugin-package";
import { companyBrainPluginPackage as rawCompanyBrainPluginPackage } from "@thinkwork/plugin-company-brain";
import { emailChannelPluginPackage as rawEmailChannelPluginPackage } from "@thinkwork/plugin-email-channel";
import { lakehousePluginPackage as rawLakehousePluginPackage } from "@thinkwork/plugin-lakehouse";
import { lastmilePluginPackage as rawLastmilePluginPackage } from "@thinkwork/plugin-lastmile";
import { planePluginPackage as rawPlanePluginPackage } from "@thinkwork/plugin-plane";
import { sendgridPluginPackage as rawSendgridPluginPackage } from "@thinkwork/plugin-sendgrid";
import { twentyPluginPackage as rawTwentyPluginPackage } from "@thinkwork/plugin-twenty";

export const companyBrainPluginPackage = defineFirstPartyPluginPackage(
  rawCompanyBrainPluginPackage,
);
export const emailChannelPluginPackage = defineFirstPartyPluginPackage(
  rawEmailChannelPluginPackage,
);
export const lakehousePluginPackage = defineFirstPartyPluginPackage(
  rawLakehousePluginPackage,
);
export const lastmilePluginPackage = defineFirstPartyPluginPackage(
  rawLastmilePluginPackage,
);
export const planePluginPackage = defineFirstPartyPluginPackage(
  rawPlanePluginPackage,
);
export const sendgridPluginPackage = defineFirstPartyPluginPackage(
  rawSendgridPluginPackage,
);
export const twentyPluginPackage = defineFirstPartyPluginPackage(
  rawTwentyPluginPackage,
);

export const companyBrainManifest = companyBrainPluginPackage.manifest;
export const emailChannelManifest = emailChannelPluginPackage.manifest;
export const lakehouseManifest = lakehousePluginPackage.manifest;
export const lastmileManifest = lastmilePluginPackage.manifest;
export const planeManifest = planePluginPackage.manifest;
export const sendgridManifest = sendgridPluginPackage.manifest;
export const twentyManifest = twentyPluginPackage.manifest;

export const firstPartyPluginPackages = [
  companyBrainPluginPackage,
  emailChannelPluginPackage,
  lakehousePluginPackage,
  lastmilePluginPackage,
  planePluginPackage,
  sendgridPluginPackage,
  twentyPluginPackage,
] as const;

/**
 * Every repo-authored manifest published to the catalog.
 */
export const allPluginManifests = firstPartyPluginPackages
  .map((pluginPackage) => pluginPackage.manifest)
  .sort((a, b) => a.pluginKey.localeCompare(b.pluginKey));
