import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

export interface PluginRegistryEntry {
  packageKey: string;
  packageName: string;
  exportName: string;
  manifestExportName: string;
  rawExportName: string;
}

const GENERATED_PATH = new URL(
  "../src/registry/generated-first-party.ts",
  import.meta.url,
);

export function discoverPluginRegistryEntries({
  repoRoot = resolve(fileURLToPath(new URL("../../..", import.meta.url))),
} = {}): PluginRegistryEntry[] {
  const pluginsRoot = resolve(repoRoot, "plugins");
  return readdirSync(pluginsRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const packageKey = entry.name;
      const packageJsonPath = resolve(pluginsRoot, packageKey, "package.json");
      if (!existsSync(packageJsonPath)) return null;
      const packageJson = JSON.parse(readFileSync(packageJsonPath, "utf8")) as {
        name?: string;
        thinkworkPlugin?: {
          catalogPublication?: string;
        };
      };
      if (!packageJson.name?.startsWith("@thinkwork/plugin-")) return null;
      if (packageJson.name === "@thinkwork/plugin-catalog") return null;
      if (packageJson.thinkworkPlugin?.catalogPublication === "deferred") {
        return null;
      }
      const exportName = `${camelCase(packageKey)}PluginPackage`;
      return {
        packageKey,
        packageName: packageJson.name,
        exportName,
        manifestExportName: `${camelCase(packageKey)}Manifest`,
        rawExportName: `raw${pascalCase(packageKey)}PluginPackage`,
      };
    })
    .filter((entry): entry is PluginRegistryEntry => entry !== null)
    .sort((a, b) => a.packageKey.localeCompare(b.packageKey));
}

export function renderPluginRegistry(entries: readonly PluginRegistryEntry[]) {
  const imports = entries
    .map(
      (entry) =>
        `import { ${entry.exportName} as ${entry.rawExportName} } from "${entry.packageName}";`,
    )
    .join("\n");
  const packages = entries
    .map(
      (entry) =>
        `export const ${entry.exportName} = defineFirstPartyPluginPackage(
  ${entry.rawExportName},
);`,
    )
    .join("\n");
  const manifests = entries
    .map(
      (entry) =>
        `export const ${entry.manifestExportName} = ${entry.exportName}.manifest;`,
    )
    .join("\n");
  const packageList = entries
    .map((entry) => `  ${entry.exportName},`)
    .join("\n");

  return `// Generated by plugins/catalog/scripts/generate-plugin-registry.ts.
// Do not edit by hand. Update plugins/*/package.json, then run:
//   pnpm --filter @thinkwork/plugin-catalog generate:plugins

import { defineFirstPartyPluginPackage } from "../plugin-package";
${imports}

${packages}

${manifests}

export const firstPartyPluginPackages = [
${packageList}
] as const;

/**
 * Every repo-authored manifest published to the catalog.
 */
export const allPluginManifests = firstPartyPluginPackages
  .map((pluginPackage) => pluginPackage.manifest)
  .sort((a, b) => a.pluginKey.localeCompare(b.pluginKey));
`;
}

export function expectedPluginRegistry({
  repoRoot,
}: { repoRoot?: string } = {}) {
  return renderPluginRegistry(discoverPluginRegistryEntries({ repoRoot }));
}

function camelCase(value: string) {
  return value.replace(/-([a-z0-9])/g, (_match, char: string) =>
    char.toUpperCase(),
  );
}

function pascalCase(value: string) {
  const camel = camelCase(value);
  return `${camel[0]?.toUpperCase() ?? ""}${camel.slice(1)}`;
}

function main() {
  const generatedPath = fileURLToPath(GENERATED_PATH);
  const expected = expectedPluginRegistry();
  if (process.argv.includes("--check")) {
    const actual = readFileSync(generatedPath, "utf8");
    if (actual !== expected) {
      throw new Error(
        `${generatedPath} is stale; run pnpm --filter @thinkwork/plugin-catalog generate:plugins`,
      );
    }
    return;
  }
  writeFileSync(generatedPath, expected, "utf8");
  console.log(`Wrote ${generatedPath}`);
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  main();
}
