import { createHash } from "node:crypto";
import type {
  LearningCandidate,
  LearningCandidateSummary,
  RejectedLearningCandidate,
} from "./learner.js";
import type { RequesterMemoryHindsightSyncResult } from "./hindsight-sync.js";

export function renderCandidateAppendSection(input: {
  runId: string;
  threadId: string;
  scheduledFor: string;
  candidates: LearningCandidate[];
}): string {
  const lines = [
    `## Thread idle run ${input.runId}`,
    "",
    `- Thread: ${input.threadId}`,
    `- Scheduled for: ${input.scheduledFor}`,
    "",
  ];

  for (const candidate of input.candidates) {
    lines.push(
      `- [${candidate.category}] score=${candidate.score.toFixed(2)} message=${candidate.evidenceMessageIds.join(", ")} hash=${candidate.hash}`,
      `  ${candidate.text}`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

export function appendMarkdownSection(
  existing: string | null,
  section: string,
): string {
  const base = existing?.trimEnd();
  if (!base) return `${section.trimEnd()}\n`;
  return `${base}\n\n${section.trimEnd()}\n`;
}

export function renderDurableMemoryAppendSection(input: {
  runId: string;
  threadId: string;
  scheduledFor: string;
  candidates: LearningCandidate[];
}): string {
  const lines = [
    `## Learned from thread ${input.threadId}`,
    "",
    `- Run: ${input.runId}`,
    `- Learned at: ${input.scheduledFor}`,
    "",
  ];

  for (const candidate of input.candidates) {
    lines.push(
      `- [${candidate.category}] ${candidate.text}`,
      `  Evidence: ${candidate.evidenceMessageIds.join(", ")}; score=${candidate.score.toFixed(2)}; hash=${candidate.hash}`,
    );
  }

  lines.push("");
  return lines.join("\n");
}

export function renderIdleLearningReport(input: {
  runId: string;
  tenantId: string;
  userId: string;
  threadId: string;
  computerId: string;
  scheduledJobId: string;
  scheduledFor: string;
  lastActivityAt: string;
  candidateSummary: LearningCandidateSummary;
  candidates: LearningCandidate[];
  rejectedCandidates: RejectedLearningCandidate[];
  changedPaths: string[];
  transcriptMessageCount: number;
  attachmentCount: number;
  hindsightSync?: RequesterMemoryHindsightSyncResult;
}): string {
  const reportJson = {
    runId: input.runId,
    tenantId: input.tenantId,
    userId: input.userId,
    threadId: input.threadId,
    computerId: input.computerId,
    scheduledJobId: input.scheduledJobId,
    scheduledFor: input.scheduledFor,
    lastActivityAt: input.lastActivityAt,
    candidateSummary: input.candidateSummary,
    changedPaths: input.changedPaths,
    transcriptMessageCount: input.transcriptMessageCount,
    attachmentCount: input.attachmentCount,
    hindsightSync: input.hindsightSync ?? null,
  };

  return [
    "# Requester Idle-Learning Report",
    "",
    "Generated by requester idle memory learner.",
    "",
    "```json",
    JSON.stringify(reportJson, null, 2),
    "```",
    "",
    "## Candidates",
    "",
    ...renderCandidateLines(input.candidates),
    "",
    "## Rejected",
    "",
    ...renderRejectedLines(input.rejectedCandidates),
    "",
  ].join("\n");
}

function renderCandidateLines(candidates: LearningCandidate[]): string[] {
  if (candidates.length === 0) return ["- None"];
  return candidates.map(
    (candidate) =>
      `- [${candidate.category}] score=${candidate.score.toFixed(2)} hash=${candidate.hash}: ${candidate.text}`,
  );
}

function renderRejectedLines(rejected: RejectedLearningCandidate[]): string[] {
  if (rejected.length === 0) return ["- None"];
  return rejected.map(
    (candidate) =>
      `- [${candidate.reason}] message=${candidate.evidenceMessageId} hash=${shortHash(candidate.text)}`,
  );
}

function shortHash(text: string): string {
  return createHash("sha256").update(text).digest("hex").slice(0, 12);
}
